"""
Extracted handler implementations: auto_rules
Auto-generated by refactor_main.py
"""
import json
import sys
import time
import asyncio
import traceback
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

from service_context import get_service_context

# All handlers receive (self, payload) where self is BackendService instance.
# They are called via: await handler_impl(self, payload)
# Inside, use self.db, self.send_event(), self.telegram_manager, etc.
# This is a transitional pattern - later, replace self.xxx with ctx.xxx


# ==================== 流程自動化 Handlers (Phase C) ====================

async def handle_get_automation_rules(self, payload: Dict[str, Any]):
    """獲取自動化規則"""
    try:
        from automation_rules import get_automation_engine
        
        engine = get_automation_engine()
        rules_data = engine.to_dict()
        
        self.send_event("automation-rules", {
            "success": True,
            **rules_data
        })
    except Exception as e:
        print(f"[Backend] Error getting automation rules: {e}", file=sys.stderr)
        self.send_event("automation-rules", {"success": False, "error": str(e)})


async def handle_add_automation_rule(self, payload: Dict[str, Any]):
    """添加自動化規則"""
    try:
        from automation_rules import get_automation_engine, AutomationRule, Trigger, Action, TriggerType, ActionType, Condition, ConditionOperator
        
        engine = get_automation_engine()
        
        # 構建規則
        triggers = []
        for t in payload.get("triggers", []):
            conditions = [
                Condition(c["field"], ConditionOperator(c["operator"]), c["value"])
                for c in t.get("conditions", [])
            ]
            triggers.append(Trigger(TriggerType(t["type"]), conditions, t.get("params", {})))
        
        actions = [
            Action(ActionType(a["type"]), a.get("params", {}), a.get("delay_seconds", 0))
            for a in payload.get("actions", [])
        ]
        
        rule = AutomationRule(
            id=payload.get("id", f"rule_{len(engine.rules)}"),
            name=payload.get("name", "新規則"),
            description=payload.get("description", ""),
            triggers=triggers,
            actions=actions,
            enabled=payload.get("enabled", True),
            priority=payload.get("priority", 0)
        )
        
        engine.add_rule(rule)
        
        self.send_event("automation-rule-added", {"success": True, "ruleId": rule.id})
    except Exception as e:
        print(f"[Backend] Error adding automation rule: {e}", file=sys.stderr)
        self.send_event("automation-rule-added", {"success": False, "error": str(e)})


async def handle_update_automation_rule(self, payload: Dict[str, Any]):
    """更新自動化規則"""
    try:
        from automation_rules import get_automation_engine
        
        engine = get_automation_engine()
        rule_id = payload.get("ruleId")
        updates = payload.get("updates", {})
        
        engine.update_rule(rule_id, updates)
        
        self.send_event("automation-rule-updated", {"success": True, "ruleId": rule_id})
    except Exception as e:
        print(f"[Backend] Error updating automation rule: {e}", file=sys.stderr)
        self.send_event("automation-rule-updated", {"success": False, "error": str(e)})


async def handle_delete_automation_rule(self, payload: Dict[str, Any]):
    """刪除自動化規則"""
    try:
        from automation_rules import get_automation_engine
        
        engine = get_automation_engine()
        rule_id = payload.get("ruleId")
        
        engine.remove_rule(rule_id)
        
        self.send_event("automation-rule-deleted", {"success": True, "ruleId": rule_id})
    except Exception as e:
        print(f"[Backend] Error deleting automation rule: {e}", file=sys.stderr)
        self.send_event("automation-rule-deleted", {"success": False, "error": str(e)})

