"""
Extracted handler implementations: scheduler
Auto-generated by refactor_main.py
"""
import json
import sys
import time
import asyncio
import traceback
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

from service_context import get_service_context

from service_locator import scheduler
# All handlers receive (self, payload) where self is BackendService instance.
# They are called via: await handler_impl(self, payload)
# Inside, use self.db, self.send_event(), self.telegram_manager, etc.
# This is a transitional pattern - later, replace self.xxx with ctx.xxx


# ==================== Scheduler Handlers ====================

async def handle_schedule_follow_up(self, payload: Dict[str, Any]):
    """排程跟進任務"""
    try:
        user_id = payload.get('userId', '')
        scheduled_at_str = payload.get('scheduledAt', '')
        message_template = payload.get('messageTemplate')
        task_type = payload.get('taskType', 'reminder')
        
        # Parse datetime
        scheduled_at = datetime.fromisoformat(scheduled_at_str.replace('Z', '+00:00'))
        
        task_id = await scheduler.schedule_follow_up(
            user_id=user_id,
            scheduled_at=scheduled_at,
            message_template=message_template,
            task_type=task_type
        )
        
        self.send_event("follow-up-scheduled", {
            "success": True,
            "taskId": task_id
        })
    except Exception as e:
        self.send_event("follow-up-scheduled", {
            "success": False,
            "error": str(e)
        })


async def handle_get_pending_tasks(self, payload: Dict[str, Any]):
    """獲取待執行任務"""
    try:
        limit = payload.get('limit', 50)
        tasks = await scheduler.get_pending_tasks(limit=limit)
        
        self.send_event("pending-tasks", {
            "success": True,
            "tasks": tasks
        })
    except Exception as e:
        self.send_event("pending-tasks", {
            "success": False,
            "error": str(e)
        })


async def handle_cancel_scheduled_task(self, payload: Dict[str, Any]):
    """取消排程任務"""
    try:
        task_id = payload.get('taskId')
        await scheduler.cancel_task(task_id)
        
        self.send_event("task-cancelled", {
            "success": True,
            "taskId": task_id
        })
    except Exception as e:
        self.send_event("task-cancelled", {
            "success": False,
            "error": str(e)
        })


async def handle_get_scheduler_stats(self):
    """獲取調度器統計"""
    try:
        stats = await scheduler.get_scheduler_stats()
        
        self.send_event("scheduler-stats", {
            "success": True,
            **stats
        })
    except Exception as e:
        self.send_event("scheduler-stats", {
            "success": False,
            "error": str(e)
        })


async def handle_get_reminders(self, payload: Dict[str, Any]):
    """獲取提醒列表"""
    try:
        from follow_up_reminder import get_reminder_system
        
        system = get_reminder_system()
        reminders = system.get_all_reminders()
        stats = system.get_stats()
        
        self.send_event("reminders", {
            "success": True,
            "reminders": [
                {
                    "id": r.id,
                    "leadId": r.lead_id,
                    "leadName": r.lead_name,
                    "type": r.type.value,
                    "priority": r.priority.value,
                    "message": r.message,
                    "dueAt": r.due_at.isoformat(),
                    "isDue": r.is_due(),
                    "snoozeCount": r.snooze_count
                }
                for r in reminders
            ],
            "stats": stats
        })
    except Exception as e:
        print(f"[Backend] Error getting reminders: {e}", file=sys.stderr)
        self.send_event("reminders", {"success": False, "error": str(e)})


async def handle_create_reminder(self, payload: Dict[str, Any]):
    """創建提醒"""
    try:
        from follow_up_reminder import create_follow_up_reminder
        
        result = await create_follow_up_reminder(
            lead_id=payload.get("leadId"),
            lead_name=payload.get("leadName", ""),
            message=payload.get("message", ""),
            priority=payload.get("priority", "medium"),
            due_in_minutes=payload.get("dueInMinutes", 0)
        )
        
        self.send_event("reminder-created", {"success": True, **result})
    except Exception as e:
        print(f"[Backend] Error creating reminder: {e}", file=sys.stderr)
        self.send_event("reminder-created", {"success": False, "error": str(e)})


async def handle_snooze_reminder(self, payload: Dict[str, Any]):
    """延後提醒"""
    try:
        from follow_up_reminder import get_reminder_system
        
        system = get_reminder_system()
        system.snooze_reminder(
            payload.get("reminderId"),
            payload.get("minutes", 30)
        )
        
        self.send_event("reminder-snoozed", {"success": True})
    except Exception as e:
        print(f"[Backend] Error snoozing reminder: {e}", file=sys.stderr)
        self.send_event("reminder-snoozed", {"success": False, "error": str(e)})


async def handle_complete_reminder(self, payload: Dict[str, Any]):
    """完成提醒"""
    try:
        from follow_up_reminder import get_reminder_system
        
        system = get_reminder_system()
        system.complete_reminder(payload.get("reminderId"))
        
        self.send_event("reminder-completed", {"success": True})
    except Exception as e:
        print(f"[Backend] Error completing reminder: {e}", file=sys.stderr)
        self.send_event("reminder-completed", {"success": False, "error": str(e)})

