"""
Extracted handler implementations: triggers
Auto-generated by refactor_main.py
"""
import json
import sys
import time
import asyncio
import traceback
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

from service_context import get_service_context
from database import db

# All handlers receive (self, payload) where self is BackendService instance.
# They are called via: await handler_impl(self, payload)
# Inside, use self.db, self.send_event(), self.telegram_manager, etc.
# This is a transitional pattern - later, replace self.xxx with ctx.xxx


# ==================== Trigger Rules Handlers ====================

def _trigger_rule_overlap_hint(rules: List[Dict]) -> None:
    """P2：為每條規則附加重疊提示（相同關鍵詞集+同一模板時可能重複發送）。原地修改 rules。"""
    def _kw_set(r):
        ids = r.get('keyword_set_ids') or r.get('keywordSetIds') or []
        return tuple(sorted(ids)) if isinstance(ids, list) else ()
    def _tpl_id(r):
        cfg = r.get('response_config') or r.get('responseConfig') or {}
        if isinstance(cfg, str):
            try:
                cfg = json.loads(cfg)
            except Exception:
                cfg = {}
        return cfg.get('templateId') or cfg.get('template_id')
    for r in rules:
        r['overlapWarning'] = ''
        my_kw = _kw_set(r)
        my_tpl = _tpl_id(r)
        if not my_kw and my_tpl is None:
            continue
        others = [o for o in rules if o.get('id') != r.get('id') and (o.get('is_active') or o.get('isActive'))]
        overlap_names = []
        for o in others:
            if _kw_set(o) == my_kw and _tpl_id(o) == my_tpl:
                overlap_names.append(o.get('name', o.get('id', '')))
        if overlap_names:
            r['overlapWarning'] = f"與規則「{'」「'.join(overlap_names[:3])}{'等' if len(overlap_names) > 3 else ''}」使用相同關鍵詞集與模板，同一事件僅會執行優先級最高的一條。"


async def handle_get_trigger_rules(self):
    """獲取所有觸發規則。P2：附加 overlapWarning 供前端顯示重疊提示。"""
    import sys
    print("[Backend] handle_get_trigger_rules called", file=sys.stderr)
    try:
        rules = await db.get_all_trigger_rules()
        _trigger_rule_overlap_hint(rules)
        print(f"[Backend] Loaded {len(rules)} trigger rules", file=sys.stderr)
        self.send_event("trigger-rules-result", {
            "success": True,
            "rules": rules
        })
        return {"success": True, "rules": rules}
    except Exception as e:
        import traceback
        print(f"[Backend] ❌ Error getting trigger rules: {e}", file=sys.stderr)
        traceback.print_exc(file=sys.stderr)
        self.send_log(f"❌ 獲取觸發規則失敗: {e}", "error")
        self.send_event("trigger-rules-result", {
            "success": False,
            "rules": [],
            "error": str(e)
        })
        return {"success": False, "rules": [], "error": str(e)}


async def handle_get_trigger_rule(self, payload: Dict[str, Any]):
    """獲取單個觸發規則"""
    try:
        rule_id = payload.get('id')
        if not rule_id:
            self.send_event("trigger-rule-result", {
                "success": False,
                "error": "缺少規則 ID"
            })
            return
        
        rule = await db.get_trigger_rule(rule_id)
        self.send_event("trigger-rule-result", {
            "success": True,
            "rule": rule
        })
    except Exception as e:
        self.send_log(f"❌ 獲取觸發規則失敗: {e}", "error")
        self.send_event("trigger-rule-result", {
            "success": False,
            "error": str(e)
        })


async def handle_save_trigger_rule(self, payload: Dict[str, Any]):
    """保存觸發規則（新增或更新）"""
    import sys
    print(f"[Backend] handle_save_trigger_rule called with payload: {payload}", file=sys.stderr)
    try:
        rule_id = payload.get('id')
        name = payload.get('name', '')
        
        if not name:
            self.send_event("save-trigger-rule-result", {
                "success": False,
                "error": "規則名稱不能為空"
            })
            return
        
        if not payload.get('keywordSetIds') or len(payload.get('keywordSetIds', [])) == 0:
            self.send_event("save-trigger-rule-result", {
                "success": False,
                "error": "請至少選擇一個關鍵詞集"
            })
            return
        
        if rule_id:
            # 更新（僅可更新當前用戶的規則）
            existing = await db.get_trigger_rule(rule_id)
            if not existing:
                self.send_event("save-trigger-rule-result", {
                    "success": False,
                    "error": "無權限修改該規則或規則不存在"
                })
                return
            success = await db.update_trigger_rule(rule_id, payload)
            if success:
                self.send_log(f"✅ 已更新觸發規則: {name}", "success")
                self.send_event("save-trigger-rule-result", {
                    "success": True,
                    "id": rule_id,
                    "message": "規則已更新"
                })
            else:
                self.send_event("save-trigger-rule-result", {
                    "success": False,
                    "error": "更新失敗"
                })
        else:
            # 新增
            new_id = await db.add_trigger_rule(payload)
            self.send_log(f"✅ 已創建觸發規則: {name}", "success")
            self.send_event("save-trigger-rule-result", {
                "success": True,
                "id": new_id,
                "message": "規則已創建"
            })
        
        # 刷新規則列表
        await self.handle_get_trigger_rules()
        
    except Exception as e:
        self.send_log(f"❌ 保存觸發規則失敗: {e}", "error")
        self.send_event("save-trigger-rule-result", {
            "success": False,
            "error": str(e)
        })


async def handle_delete_trigger_rule(self, payload: Dict[str, Any]):
    """刪除觸發規則"""
    try:
        rule_id = payload.get('id')
        
        if not rule_id:
            self.send_event("delete-trigger-rule-result", {
                "success": False,
                "error": "缺少規則 ID"
            })
            return
        
        success = await db.delete_trigger_rule(rule_id)
        
        self.send_event("delete-trigger-rule-result", {"success": success})
        
        if success:
            self.send_log(f"🗑️ 已刪除觸發規則 ID: {rule_id}", "success")
            await self.handle_get_trigger_rules()
            
    except Exception as e:
        self.send_log(f"❌ 刪除觸發規則失敗: {e}", "error")
        self.send_event("delete-trigger-rule-result", {
            "success": False,
            "error": str(e)
        })


async def handle_toggle_trigger_rule(self, payload: Dict[str, Any]):
    """啟用/停用觸發規則"""
    try:
        rule_id = payload.get('id')
        is_active = payload.get('isActive', True)
        
        if not rule_id:
            self.send_event("toggle-trigger-rule-result", {
                "success": False,
                "error": "缺少規則 ID"
            })
            return
        
        success = await db.toggle_trigger_rule(rule_id, is_active)
        
        self.send_event("toggle-trigger-rule-result", {"success": success})
        
        if success:
            status = "啟用" if is_active else "停用"
            self.send_log(f"✅ 已{status}觸發規則 ID: {rule_id}", "success")
            await self.handle_get_trigger_rules()
            
    except Exception as e:
        self.send_log(f"❌ 切換觸發規則狀態失敗: {e}", "error")
        self.send_event("toggle-trigger-rule-result", {
            "success": False,
            "error": str(e)
        })

