"""
Extracted handler implementations: ab_testing
Auto-generated by refactor_main.py
"""
import json
import sys
import time
import asyncio
import traceback
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

from service_context import get_service_context

# All handlers receive (self, payload) where self is BackendService instance.
# They are called via: await handler_impl(self, payload)
# Inside, use self.db, self.send_event(), self.telegram_manager, etc.
# This is a transitional pattern - later, replace self.xxx with ctx.xxx


async def handle_create_ab_test(self, payload: Dict[str, Any]):
    """創建 A/B 測試"""
    try:
        from experiments.ab_testing import create_ab_test
        
        result = await create_ab_test(
            name=payload.get("name", "新測試"),
            variants=payload.get("variants", []),
            description=payload.get("description", ""),
            primary_metric=payload.get("primaryMetric", "response_rate")
        )
        
        self.send_event("ab-test-created", {"success": True, **result})
    except Exception as e:
        print(f"[Backend] Error creating A/B test: {e}", file=sys.stderr)
        self.send_event("ab-test-created", {"success": False, "error": str(e)})


async def handle_start_ab_test(self, payload: Dict[str, Any]):
    """開始 A/B 測試"""
    try:
        from experiments.ab_testing import get_ab_testing_manager
        
        manager = get_ab_testing_manager()
        success = manager.start_experiment(payload.get("testId"))
        
        self.send_event("ab-test-started", {"success": success})
    except Exception as e:
        print(f"[Backend] Error starting A/B test: {e}", file=sys.stderr)
        self.send_event("ab-test-started", {"success": False, "error": str(e)})


async def handle_get_ab_test_results(self, payload: Dict[str, Any]):
    """獲取 A/B 測試結果"""
    try:
        from experiments.ab_testing import get_ab_testing_manager
        
        manager = get_ab_testing_manager()
        result = manager.analyze_experiment(payload.get("testId"))
        results = {
            "winner": result.winner if result else None,
            "significance": result.statistical_significance if result else 0,
            "recommendations": result.recommendations if result else []
        } if result else None
        
        self.send_event("ab-test-results", {
            "success": True,
            "results": results
        })
    except Exception as e:
        print(f"[Backend] Error getting A/B test results: {e}", file=sys.stderr)
        self.send_event("ab-test-results", {"success": False, "error": str(e)})

