"""
Extracted handler implementations: ai_chat
Auto-generated by refactor_main.py
"""
import json
import sys
import time
import asyncio
import traceback
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

from service_context import get_service_context
from database import db

# All handlers receive (self, payload) where self is BackendService instance.
# They are called via: await handler_impl(self, payload)
# Inside, use self.db, self.send_event(), self.telegram_manager, etc.
# This is a transitional pattern - later, replace self.xxx with ctx.xxx


# ==================== AI Auto Chat Handlers ====================

async def handle_get_ai_chat_settings(self):
    """Get AI auto chat settings"""
    try:
        settings = await db.get_ai_settings()
        self.send_event("ai-chat-settings", {
            "success": True,
            "settings": settings
        })
    except Exception as e:
        self.send_event("ai-chat-settings", {
            "success": False,
            "error": str(e)
        })


async def handle_update_ai_chat_settings(self, payload: Dict[str, Any]):
    """Update AI auto chat settings"""
    try:
        settings = payload.get('settings', {})
        await db.update_ai_settings(settings)
        
        # Update AI auto chat service
        await ai_auto_chat.update_settings(settings)
        
        # Update AI endpoint if provided
        if 'localAiEndpoint' in payload:
            ai_auto_chat.set_ai_config(
                payload.get('localAiEndpoint', ''),
                payload.get('localAiModel', '')
            )
        
        self.send_event("ai-chat-settings-updated", {"success": True})
        self.send_log("AI 自動聊天設置已更新", "success")
    except Exception as e:
        self.send_event("ai-chat-settings-updated", {
            "success": False,
            "error": str(e)
        })
        self.send_log(f"更新 AI 設置失敗: {str(e)}", "error")


async def handle_get_chat_history(self, payload: Dict[str, Any]):
    """Get chat history for a user"""
    try:
        user_id = payload.get('userId', '')
        limit = payload.get('limit', 50)
        
        if not user_id:
            self.send_event("chat-history", {"success": False, "error": "Missing userId"})
            return
        
        history = await db.get_chat_history(user_id, limit=limit)
        stats = await db.get_chat_stats(user_id)
        
        self.send_event("chat-history", {
            "success": True,
            "userId": user_id,
            "history": history,
            "stats": stats
        })
    except Exception as e:
        self.send_event("chat-history", {
            "success": False,
            "error": str(e)
        })


async def handle_get_user_context(self, payload: Dict[str, Any]):
    """Get full user context"""
    try:
        user_id = payload.get('userId', '')
        
        if not user_id:
            self.send_event("user-context", {"success": False, "error": "Missing userId"})
            return
        
        context = await ai_context.get_user_context(user_id)
        
        self.send_event("user-context", {
            "success": True,
            "userId": user_id,
            "context": context
        })
    except Exception as e:
        self.send_event("user-context", {
            "success": False,
            "error": str(e)
        })


async def handle_generate_ai_response(self, payload: Dict[str, Any]):
    """Generate AI response for a user message"""
    import time
    import sys
    start_time = time.time()
    
    print(f"[AI] handle_generate_ai_response called with payload keys: {payload.keys()}", file=sys.stderr)
    try:
        user_id = payload.get('userId', '')
        message = payload.get('message', '')
        system_prompt = payload.get('systemPrompt', '')
        endpoint = payload.get('localAiEndpoint', '')
        model = payload.get('localAiModel', '')
        
        print(f"[AI] Endpoint: {endpoint}, Model: {model}", file=sys.stderr)
        print(f"[AI] Message length: {len(message)}, System prompt length: {len(system_prompt)}", file=sys.stderr)
        
        if not message:
            self.send_event("ai-response", {"success": False, "error": "缺少消息內容"})
            return
        
        if not endpoint:
            self.send_event("ai-response", {"success": False, "error": "未配置 AI 服務端點"})
            return
        
        # 如果提供了端點，直接調用本地 AI
        if endpoint:
            print(f"[AI] Calling local AI service at {endpoint}...", file=sys.stderr)
            response = await self._call_local_ai(endpoint, model, system_prompt, message)
        else:
            # 使用 ai_auto_chat 服務
            print(f"[AI] Using ai_auto_chat service...", file=sys.stderr)
            ai_auto_chat.set_ai_config(endpoint, model)
            response = await ai_auto_chat.get_suggested_response(user_id, message)
        
        elapsed = time.time() - start_time
        print(f"[AI] AI generation completed in {elapsed:.2f}s", file=sys.stderr)
        
        if response:
            print(f"[AI] Successfully generated response (length: {len(response)})", file=sys.stderr)
            self.send_event("ai-response", {
                "success": True,
                "userId": user_id,
                "response": response
            })
        else:
            print(f"[AI] AI returned empty response", file=sys.stderr)
            self.send_event("ai-response", {
                "success": False,
                "error": "AI 生成失敗，返回為空。請檢查服務配置和日誌"
            })
    except asyncio.TimeoutError:
        elapsed = time.time() - start_time
        error_msg = f"AI 生成超時（{elapsed:.1f}秒），請檢查服務連接"
        print(f"[AI] {error_msg}", file=sys.stderr)
        self.send_event("ai-response", {
            "success": False,
            "error": error_msg
        })
    except Exception as e:
        import traceback
        elapsed = time.time() - start_time
        error_details = traceback.format_exc()
        error_msg = f"AI 生成錯誤: {str(e)}"
        print(f"[AI] Error after {elapsed:.2f}s: {error_details}", file=sys.stderr)
        self.send_event("ai-response", {
            "success": False,
            "error": error_msg
        })


async def handle_add_ai_memory(self, payload: Dict[str, Any]):
    """Add an AI memory for a user"""
    try:
        user_id = payload.get('userId', '')
        memory_type = payload.get('memoryType', 'fact')
        content = payload.get('content', '')
        importance = payload.get('importance', 0.5)
        
        if not user_id or not content:
            self.send_event("ai-memory-added", {"success": False, "error": "Missing userId or content"})
            return
        
        memory_id = await db.add_ai_memory(user_id, memory_type, content, importance)
        
        self.send_event("ai-memory-added", {
            "success": True,
            "memoryId": memory_id
        })
        self.send_log(f"為用戶 {user_id} 添加了記憶", "success")
    except Exception as e:
        self.send_event("ai-memory-added", {
            "success": False,
            "error": str(e)
        })


async def handle_get_ai_memories(self, payload: Dict[str, Any]):
    """Get AI memories for a user"""
    try:
        user_id = payload.get('userId', '')
        memory_type = payload.get('memoryType')
        limit = payload.get('limit', 10)
        
        if not user_id:
            self.send_event("ai-memories", {"success": False, "error": "Missing userId"})
            return
        
        memories = await db.get_ai_memories(user_id, memory_type, limit)
        
        self.send_event("ai-memories", {
            "success": True,
            "userId": user_id,
            "memories": memories
        })
    except Exception as e:
        self.send_event("ai-memories", {
            "success": False,
            "error": str(e)
        })


async def handle_analyze_conversation(self, payload: Dict[str, Any]):
    """Analyze conversation and provide insights"""
    try:
        user_id = payload.get('userId', '')
        lead_id = payload.get('leadId')
        
        if not user_id:
            self.send_event("conversation-analysis", {"success": False, "error": "Missing userId"})
            return
        
        # Get conversation history
        history = await db.get_chat_history(user_id, limit=50)
        
        # Analyze conversation
        analysis = await ai_context.analyze_conversation_stage(user_id, history)
        
        self.send_event("conversation-analysis", {
            "success": True,
            "userId": user_id,
            "leadId": lead_id,
            "analysis": analysis
        })
    except Exception as e:
        self.send_event("conversation-analysis", {
            "success": False,
            "error": str(e)
        })


# ==================== AI Marketing Strategy Handlers ====================

async def handle_generate_ai_strategy(self, payload: Dict[str, Any]):
    """使用 AI 生成營銷策略"""
    try:
        user_input = payload.get('userInput', '')
        
        if not user_input:
            self.send_event("ai-strategy-generated", {
                "success": False,
                "error": "請輸入您的需求"
            })
            return
        
        # 嘗試使用 AI 生成策略
        try:
            from ai_context import ai_context
            
            prompt = f"""
            根據用戶的營銷需求，生成詳細的營銷策略。

            用戶需求：{user_input}

            請返回 JSON 格式的策略，包含：
            1. industry: 識別的目標行業
            2. targetAudience: 目標受眾描述
            3. keywords: 分為 highIntent（高意向）、mediumIntent（中意向）、extended（擴展）三類關鍵詞
            4. customerProfile: 客戶畫像，包含 identity（身份）、features（特徵）、needs（需求）
            5. recommendedGroups: 建議搜索的群組類型
            6. messageTemplates: 消息模板，包含 firstTouch（首次觸達）、followUp（跟進）、closing（促成）
            """
            
            response = await ai_context.generate_response(
                user_id="system",
                message=prompt,
                context=[]
            )
            
            # 嘗試解析 AI 返回的 JSON
            import json
            import re
            
            # 提取 JSON
            json_match = re.search(r'\{[\s\S]*\}', response)
            if json_match:
                strategy = json.loads(json_match.group())
                self.send_event("ai-strategy-generated", {
                    "success": True,
                    "strategy": strategy
                })
                return
                
        except Exception as ai_error:
            print(f"[AI Strategy] AI generation failed: {ai_error}", file=sys.stderr)
        
        # 如果 AI 生成失敗，返回錯誤讓前端使用本地模板
        self.send_event("ai-strategy-generated", {
            "success": False,
            "error": "AI 服務暫時不可用，已使用本地模板"
        })
        
    except Exception as e:
        self.send_event("ai-strategy-generated", {
            "success": False,
            "error": str(e)
        })


async def handle_save_ai_strategy(self, payload: Dict[str, Any]):
    """保存 AI 策略"""
    try:
        name = payload.get('name', f"策略_{datetime.now().strftime('%Y%m%d_%H%M%S')}")
        strategy = payload.get('strategy', {})
        
        # 保存到數據庫
        await db.execute(
            """INSERT INTO ai_strategies (name, strategy_json, created_at) 
               VALUES (?, ?, CURRENT_TIMESTAMP)
               ON CONFLICT(name) DO UPDATE SET strategy_json = ?, updated_at = CURRENT_TIMESTAMP""",
            (name, json.dumps(strategy), json.dumps(strategy))
        )
        
        self.send_log(f"✅ 策略已保存: {name}", "success")
        self.send_event("ai-strategy-saved", {"success": True, "name": name})
        
    except Exception as e:
        self.send_log(f"❌ 保存策略失敗: {e}", "error")
        self.send_event("ai-strategy-saved", {"success": False, "error": str(e)})


async def handle_get_ai_strategies(self, payload: Dict[str, Any]):
    """獲取已保存的策略列表"""
    try:
        strategies = await db.fetch_all(
            "SELECT * FROM ai_strategies ORDER BY created_at DESC LIMIT 50"
        )
        
        result = []
        for s in strategies:
            try:
                result.append({
                    "id": s.get('id'),
                    "name": s.get('name'),
                    "strategy": json.loads(s.get('strategy_json', '{}')),
                    "createdAt": s.get('created_at'),
                    "stats": {
                        "totalLeads": 0,
                        "contacted": 0,
                        "converted": 0
                    }
                })
            except:
                pass
        
        self.send_event("ai-strategies-list", {"success": True, "strategies": result})
        
    except Exception as e:
        self.send_event("ai-strategies-list", {"success": False, "error": str(e)})


async def handle_execute_ai_strategy(self, payload: Dict[str, Any]):
    """執行 AI 營銷策略"""
    try:
        strategy = payload.get('strategy', {})
        
        self.send_log(f"🚀 開始執行 AI 策略: {strategy.get('industry', '未知')}", "info")
        
        # 1. 創建關鍵詞集
        keywords = strategy.get('keywords', {})
        all_keywords = (
            keywords.get('highIntent', []) + 
            keywords.get('mediumIntent', []) + 
            keywords.get('extended', [])
        )
        
        if all_keywords:
            # 保存為關鍵詞集
            keyword_set_name = f"AI策略_{strategy.get('industry', '自定義')}"
            await db.execute(
                """INSERT INTO keyword_sets (name, keywords, is_active, created_at)
                   VALUES (?, ?, 1, CURRENT_TIMESTAMP)
                   ON CONFLICT(name) DO UPDATE SET keywords = ?, is_active = 1""",
                (keyword_set_name, json.dumps(all_keywords), json.dumps(all_keywords))
            )
            self.send_log(f"✅ 已創建關鍵詞集: {keyword_set_name} ({len(all_keywords)} 個關鍵詞)", "success")
        
        # 2. 保存消息模板
        templates = strategy.get('messageTemplates', {})
        for template_type, content in templates.items():
            if content:
                template_name = f"AI_{strategy.get('industry', '')}_{template_type}"
                await db.execute(
                    """INSERT INTO message_templates (name, content, template_type, created_at)
                       VALUES (?, ?, ?, CURRENT_TIMESTAMP)
                       ON CONFLICT(name) DO UPDATE SET content = ?""",
                    (template_name, content, template_type, content)
                )
        self.send_log(f"✅ 已創建消息模板", "success")
        
        # 3. 發送執行狀態
        self.send_event("ai-execution-status", {
            "isExecuting": True,
            "phase": "initialized",
            "message": "策略已初始化，準備開始搜索群組..."
        })
        
        # 4. 開始搜索群組（異步執行）
        asyncio.create_task(self._execute_ai_group_search(strategy))
        
        self.send_event("ai-strategy-executed", {"success": True})
        
    except Exception as e:
        self.send_log(f"❌ 執行策略失敗: {e}", "error")
        self.send_event("ai-strategy-executed", {"success": False, "error": str(e)})


async def handle_save_conversation_strategy(self, payload: Dict[str, Any]):
    """🔧 保存對話策略"""
    try:
        style = payload.get('style', 'friendly')
        response_length = payload.get('responseLength', 'medium')
        use_emoji = payload.get('useEmoji', True)
        custom_persona = payload.get('customPersona', '')
        
        # 保存到 ai_settings 表
        await db.execute("""
            INSERT INTO ai_settings (key, value) VALUES ('conversation_strategy', ?)
            ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = CURRENT_TIMESTAMP
        """, (json.dumps({
            'style': style,
            'responseLength': response_length,
            'useEmoji': use_emoji,
            'customPersona': custom_persona
        }),))
        
        # 同時更新 system_prompt（如果有自定義人設）
        if custom_persona:
            await db.execute("""
                INSERT INTO ai_settings (key, value) VALUES ('system_prompt', ?)
                ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = CURRENT_TIMESTAMP
            """, (custom_persona,))
        
        print(f"[AI] 對話策略已保存: style={style}, length={response_length}, emoji={use_emoji}", file=sys.stderr)
        self.send_event("conversation-strategy-saved", {"success": True})
        
    except Exception as e:
        print(f"[AI] 保存對話策略失敗: {e}", file=sys.stderr)
        self.send_event("conversation-strategy-saved", {"success": False, "error": str(e)})


async def handle_get_conversation_strategy(self):
    """🔧 獲取對話策略"""
    try:
        row = await db.fetch_one(
            "SELECT value FROM ai_settings WHERE key = 'conversation_strategy'"
        )
        
        if row and row.get('value'):
            strategy = json.loads(row['value'])
        else:
            strategy = {
                'style': 'friendly',
                'responseLength': 'medium',
                'useEmoji': True,
                'customPersona': ''
            }
        
        print(f"[AI] 對話策略已加載: {strategy}", file=sys.stderr)
        self.send_event("conversation-strategy-loaded", {"success": True, "strategy": strategy})
        
    except Exception as e:
        print(f"[AI] 獲取對話策略失敗: {e}", file=sys.stderr)
        self.send_event("conversation-strategy-loaded", {"success": False, "error": str(e)})


# ==================== Chat History Handlers ====================

async def handle_get_chat_history_full(self, payload: Dict[str, Any]):
    """獲取完整聊天記錄（支持分頁和緩存）"""
    try:
        import sys
        user_id = payload.get('userId', '')
        limit = payload.get('limit', 50)
        offset = payload.get('offset', 0)
        
        print(f"[Backend] Getting chat history for user {user_id}, limit={limit}, offset={offset}", file=sys.stderr)
        
        # 優化：只查詢一次，獲取 limit+1 條來判斷是否有更多
        history = await db.get_chat_history_paginated(
            user_id=user_id,
            limit=limit + 1,  # 多取一條來判斷是否有更多
            offset=offset
        )
        
        # 判斷是否有更多消息
        has_more = len(history) > limit
        # 只返回 limit 條
        if has_more:
            history = history[:limit]
        
        # 獲取總數（使用更快的查詢，只在需要時執行）
        # 如果 offset=0 且沒有更多消息，總數就是當前數量
        if offset == 0 and not has_more:
            total_count = len(history)
        else:
            # 需要查詢總數
            try:
                cursor = await db._connection.execute("""
                    SELECT COUNT(*) as total FROM chat_history WHERE user_id = ?
                """, (user_id,))
                total_row = await cursor.fetchone()
                total_count = total_row['total'] if total_row else len(history)
            except Exception as count_err:
                print(f"[Backend] Error getting total count: {count_err}", file=sys.stderr)
                total_count = len(history)  # 降級：使用當前數量
        
        # 獲取用戶資料
        profile = await db.get_user_profile(user_id)
        
        # 獲取用戶標籤
        cursor = await db._connection.execute("""
            SELECT tag, tag_type, confidence FROM user_tags WHERE user_id = ?
        """, (user_id,))
        tags = [dict(row) for row in await cursor.fetchall()]
        
        # 格式化消息（反轉順序，從舊到新）
        formatted_messages = []
        for msg in reversed(history):  # 反轉為從舊到新
            formatted_messages.append({
                "id": msg.get('id'),
                "role": msg.get('role'),
                "content": msg.get('content'),
                "timestamp": msg.get('timestamp'),
                "accountPhone": msg.get('account_phone'),
                "sourceGroup": msg.get('source_group'),
            })
        
        print(f"[Backend] Sending chat history: {len(formatted_messages)} messages, hasMore={has_more}, total={total_count}", file=sys.stderr)
        
        self.send_event("chat-history-full", {
            "success": True,
            "userId": user_id,
            "messages": formatted_messages,
            "profile": profile,
            "tags": tags,
            "total": total_count,
            "hasMore": has_more  # 添加 hasMore 字段
        })
    except Exception as e:
        import traceback
        import sys
        error_details = traceback.format_exc()
        print(f"[Backend] Error getting chat history: {error_details}", file=sys.stderr)
        self.send_event("chat-history-full", {
            "success": False,
            "error": str(e),
            "userId": payload.get('userId', '')
        })

