"""
Extracted handler implementations: ai_generation
Auto-generated by refactor_main.py
"""
import json
import sys
import time
import asyncio
import traceback
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

from service_context import get_service_context
from database import db

# All handlers receive (self, payload) where self is BackendService instance.
# They are called via: await handler_impl(self, payload)
# Inside, use self.db, self.send_event(), self.telegram_manager, etc.
# This is a transitional pattern - later, replace self.xxx with ctx.xxx


# ==================== AI Generation Handlers ====================

async def handle_ai_generate_message(self, payload: Dict[str, Any]):
    """AI 生成批量發送消息 - 優先使用配置的 AI，回退到本地模板"""
    import sys
    import random
    import aiohttp
    
    try:
        topic = payload.get('topic', '打招呼')
        style = payload.get('style', 'friendly')
        count = payload.get('count', 5)
        context = payload.get('context', {})
        owner_user_id = payload.get('ownerUserId')
        
        # 配額檢查（根據生成數量計算消耗）
        ai_cost = max(1, count // 3)  # 每 3 條消息消耗 1 次 AI 配額
        quota_check = await self.check_quota('ai_calls', ai_cost, owner_user_id)
        if not quota_check.get('allowed', True):
            self.send_quota_exceeded_error('ai-generate-message-result', 'ai_calls', quota_check.get('result', {}))
            return
        
        print(f"[AI] 生成消息: topic={topic}, style={style}, count={count}", file=sys.stderr)
        
        # 嘗試獲取配置的 AI 模型
        ai_model = await self._get_default_ai_model()
        
        if ai_model:
            print(f"[AI] 使用配置的 AI: {ai_model.get('displayName')} ({ai_model.get('provider')})", file=sys.stderr)
            self.send_log(f"🤖 使用 {ai_model.get('displayName')} 生成消息...", "info")
            
            # 嘗試調用真正的 AI
            try:
                messages = await self._generate_messages_with_ai(
                    ai_model, topic, style, count
                )
                if messages:
                    self.send_event("ai-generate-message-result", {
                        "success": True,
                        "messages": messages,
                        "source": "ai",
                        "model": ai_model.get('displayName')
                    })
                    return
            except Exception as ai_error:
                print(f"[AI] AI 調用失敗，回退到本地模板: {ai_error}", file=sys.stderr)
                self.send_log(f"⚠️ AI 調用失敗，使用本地模板: {ai_error}", "warning")
        else:
            print(f"[AI] 未配置 AI 模型，使用本地模板", file=sys.stderr)
        
        # 回退：使用本地模板
        messages = self._get_local_message_templates(topic, style, count)
        
        self.send_event("ai-generate-message-result", {
            "success": True,
            "messages": messages,
            "source": "local",
            "model": None
        })
        
    except Exception as e:
        print(f"[AI] 生成消息失敗: {e}", file=sys.stderr)
        self.send_event("ai-generate-message-result", {
            "success": False,
            "error": str(e)
        })


async def handle_ai_generate_text(self, payload: Dict[str, Any]):
    """
    🆕 P0: 通用 AI 文本生成 handler
    支持多角色協作等模塊調用 AI 生成文本
    🔧 P1: 添加重試機制
    🔧 P4.3: 添加配額檢查
    """
    import sys
    import aiohttp
    
    # 🔧 調試：立即打印確認收到命令
    print(f"[AI] ========== handle_ai_generate_text 被調用 ==========", file=sys.stderr)
    print(f"[AI] payload keys: {list(payload.keys()) if payload else 'None'}", file=sys.stderr)
    
    try:
        prompt = payload.get('prompt', '')
        max_tokens = payload.get('maxTokens', 500)
        callback = payload.get('callback', 'ai:generate-text-result')
        response_format = payload.get('responseFormat', 'text')  # text 或 json
        owner_user_id = payload.get('ownerUserId')
        
        # 配額檢查
        quota_check = await self.check_quota('ai_calls', 1, owner_user_id)
        if not quota_check.get('allowed', True):
            self.send_event(callback, {
                "success": False,
                "error": "AI 調用配額已用盡",
                "code": "QUOTA_EXCEEDED",
                "quota": quota_check.get('result', {})
            })
            return
        
        print(f"[AI] callback={callback}, prompt長度={len(prompt)}", file=sys.stderr)
        
        if not prompt:
            print(f"[AI] 錯誤：缺少 prompt 參數", file=sys.stderr)
            self.send_event(callback, {"success": False, "error": "缺少 prompt 參數"})
            return
        
        print(f"[AI] 通用文本生成: prompt長度={len(prompt)}, callback={callback}", file=sys.stderr)
        
        # 獲取 AI 模型
        ai_model = await self._get_default_ai_model()
        
        if not ai_model:
            print(f"[AI] 未配置 AI 模型，無法生成", file=sys.stderr)
            self.send_event(callback, {
                "success": False,
                "error": "未配置 AI 模型",
                "text": None
            })
            return
        
        print(f"[AI] 使用模型: {ai_model.get('displayName')} ({ai_model.get('provider')})", file=sys.stderr)
        
        # 🔧 P1: 添加重試機制（使用配置常量）
        from config import AIConfig
        result_text = None
        last_error = None
        
        for attempt in range(AIConfig.MAX_RETRIES + 1):
            if attempt > 0:
                print(f"[AI] 重試第 {attempt} 次...", file=sys.stderr)
                await asyncio.sleep(AIConfig.RETRY_DELAY_SECONDS)
            
            result_text = await self._call_ai_for_text(ai_model, prompt, max_tokens)
            
            if result_text:
                break
            else:
                last_error = "AI 生成失敗"
        
        if result_text:
            print(f"[AI] 生成成功，長度: {len(result_text)}", file=sys.stderr)
            self.send_event(callback, {
                "success": True,
                "text": result_text,
                "model": ai_model.get('displayName'),
                "provider": ai_model.get('provider')
            })
        else:
            print(f"[AI] 所有嘗試都失敗", file=sys.stderr)
            self.send_event(callback, {
                "success": False,
                "error": last_error or "AI 生成失敗",
                "text": None
            })
            
    except Exception as e:
        print(f"[AI] 通用文本生成錯誤: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        callback = payload.get('callback', 'ai:generate-text-result')
        self.send_event(callback, {
            "success": False,
            "error": str(e),
            "text": None
        })


async def handle_ai_generate_group_names(self, payload: Dict[str, Any]):
    """AI 生成群組名稱"""
    import sys
    import random
    
    try:
        keywords = payload.get('keywords', '')
        style = payload.get('style', 'professional')
        count = payload.get('count', 5)
        
        print(f"[AI] 生成群名: keywords={keywords}, style={style}", file=sys.stderr)
        
        # 根據風格和關鍵詞生成群名
        prefixes = {
            'professional': ['🏢', '💼', '📊', '🎯', '⚡'],
            'lively': ['🔥', '🎉', '✨', '💫', '🌟'],
            'mysterious': ['🌙', '💎', '🔮', '👑', '🎭'],
            'simple': ['📌', '📎', '🔗', '•', '→']
        }
        
        suffixes = {
            'professional': ['交流群', '研討會', '精英社', '聯盟', '商務圈'],
            'lively': ['嗨皮群', '歡樂營', '狂歡派', '趴體', '快樂屋'],
            'mysterious': ['內部群', 'VIP專屬', '私密圈', '秘密基地', '核心群'],
            'simple': ['群', '交流', '討論組', '社區', '頻道']
        }
        
        prefix_list = prefixes.get(style, prefixes['professional'])
        suffix_list = suffixes.get(style, suffixes['professional'])
        
        names = []
        keyword_parts = [k.strip() for k in keywords.split(',') if k.strip()]
        main_keyword = keyword_parts[0] if keyword_parts else '交流'
        
        for i in range(count):
            prefix = prefix_list[i % len(prefix_list)]
            suffix = suffix_list[i % len(suffix_list)]
            
            # 生成不同組合
            if i == 0:
                name = f"{prefix} {main_keyword}{suffix}"
            elif i == 1:
                name = f"{prefix} 2026{main_keyword}精英{suffix}"
            elif i == 2:
                year_suffix = ['俱樂部', '聯盟', '圈子'][i % 3]
                name = f"{prefix} {main_keyword}{year_suffix}"
            elif i == 3:
                name = f"{prefix} {main_keyword}愛好者{suffix}"
            else:
                name = f"{prefix} {main_keyword}達人{suffix}"
            
            names.append(name)
        
        self.send_event("ai-generate-group-names-result", {
            "success": True,
            "names": names
        })
        
    except Exception as e:
        print(f"[AI] 生成群名失敗: {e}", file=sys.stderr)
        self.send_event("ai-generate-group-names-result", {
            "success": False,
            "error": str(e)
        })


async def handle_ai_generate_welcome(self, payload: Dict[str, Any]):
    """AI 生成歡迎消息"""
    import sys
    import random
    
    try:
        topic = payload.get('topic', '歡迎')
        group_name = payload.get('groupName', '我們的群組')
        
        print(f"[AI] 生成歡迎消息: topic={topic}, group={group_name}", file=sys.stderr)
        
        # 歡迎消息模板
        templates = [
            f"🎉 歡迎 {{name}} 加入「{group_name}」！很高興認識你，有任何問題隨時提問哦~",
            f"👋 Hi {{name}}！歡迎來到「{group_name}」！希望你在這裡能找到志同道合的朋友！",
            f"✨ {{name}} 你好！歡迎加入我們！這裡是「{group_name}」，大家都很友善的~",
            f"🌟 熱烈歡迎 {{name}}！「{group_name}」又多了一位小夥伴！",
            f"💫 {{name}} 歡迎入群！「{group_name}」期待與你一起成長！"
        ]
        
        message = random.choice(templates)
        
        self.send_event("ai-generate-welcome-result", {
            "success": True,
            "message": message
        })
        
    except Exception as e:
        print(f"[AI] 生成歡迎消息失敗: {e}", file=sys.stderr)
        self.send_event("ai-generate-welcome-result", {
            "success": False,
            "error": str(e)
        })


# ==================== Local AI & Voice Services Handlers ====================

async def handle_test_local_ai(self, payload: Dict[str, Any]):
    """Test connection to local AI service with detailed diagnostics"""
    import aiohttp
    import socket
    import time
    from urllib.parse import urlparse
    
    endpoint = payload.get('endpoint', 'http://localhost:3002')
    model = payload.get('model', '')
    
    diagnostics = {
        "endpoint": endpoint,
        "tcp_connection": False,
        "http_connection": False,
        "ai_response": False,
        "errors": []
    }
    
    try:
        # 解析端點
        parsed = urlparse(endpoint)
        host = parsed.hostname
        port = parsed.port or (443 if parsed.scheme == 'https' else 80)
        
        print(f"[AI Test] Testing connection to {host}:{port}...", file=sys.stderr)
        
        # 步驟 1: 測試 TCP 連接
        try:
            sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            sock.settimeout(5)
            result = sock.connect_ex((host, port))
            sock.close()
            
            if result == 0:
                diagnostics["tcp_connection"] = True
                print(f"[AI Test] ✓ TCP connection to {host}:{port} successful", file=sys.stderr)
            else:
                diagnostics["errors"].append(f"TCP 連接失敗 (錯誤代碼: {result})")
                print(f"[AI Test] ✗ TCP connection failed (error code: {result})", file=sys.stderr)
                self.send_event("local-ai-test-result", {
                    "success": False,
                    "endpoint": endpoint,
                    "diagnostics": diagnostics,
                    "error": f"無法連接到 {host}:{port}。請檢查：\n1. AI 服務是否正在運行\n2. 防火牆是否允許連接\n3. 網絡是否正常"
                })
                return
        except socket.gaierror as e:
            diagnostics["errors"].append(f"DNS 解析失敗: {str(e)}")
            print(f"[AI Test] ✗ DNS resolution failed: {e}", file=sys.stderr)
            self.send_event("local-ai-test-result", {
                "success": False,
                "endpoint": endpoint,
                "diagnostics": diagnostics,
                "error": f"無法解析主機名 {host}。請檢查網絡設置"
            })
            return
        except socket.timeout:
            diagnostics["errors"].append("TCP 連接超時")
            print(f"[AI Test] ✗ TCP connection timeout", file=sys.stderr)
            self.send_event("local-ai-test-result", {
                "success": False,
                "endpoint": endpoint,
                "diagnostics": diagnostics,
                "error": f"連接 {host}:{port} 超時。請檢查防火牆設置"
            })
            return
        except Exception as e:
            diagnostics["errors"].append(f"TCP 連接錯誤: {str(e)}")
            print(f"[AI Test] ✗ TCP connection error: {e}", file=sys.stderr)
        
        # 步驟 2: 測試 HTTP 連接
        timeout = aiohttp.ClientTimeout(total=30, connect=5)
        async with aiohttp.ClientSession(timeout=timeout) as session:
            # 嘗試 GET 請求（Ollama 健康檢查）
            try:
                health_url = endpoint.rstrip('/')
                if not health_url.endswith('/api/tags') and not health_url.endswith('/v1/models'):
                    # 嘗試 Ollama 健康檢查端點
                    health_endpoints = [
                        f"{health_url}",
                        f"{health_url}/api/tags",
                        f"{health_url}/v1/models"
                    ]
                else:
                    health_endpoints = [health_url]
                
                for health_endpoint in health_endpoints:
                    try:
                        async with session.get(health_endpoint, timeout=aiohttp.ClientTimeout(total=5)) as resp:
                            if resp.status in [200, 404, 405]:
                                diagnostics["http_connection"] = True
                                print(f"[AI Test] ✓ HTTP connection successful: {health_endpoint} (status: {resp.status})", file=sys.stderr)
                                break
                    except:
                        continue
            except Exception as e:
                diagnostics["errors"].append(f"HTTP 連接測試失敗: {str(e)}")
                print(f"[AI Test] HTTP connection test failed: {e}", file=sys.stderr)
            
            # 步驟 3: 測試實際 AI 請求
            try:
                chat_url = endpoint.rstrip('/')
                if not chat_url.endswith('/v1/chat/completions'):
                    chat_url = chat_url.rstrip('/') + '/v1/chat/completions'
                
                test_payload = {
                    "messages": [{"role": "user", "content": "test"}],
                    "max_tokens": 10
                }
                if model:
                    test_payload["model"] = model
                
                print(f"[AI Test] Testing AI request to {chat_url}...", file=sys.stderr)
                start_time = time.time()
                
                async with session.post(chat_url, json=test_payload, timeout=aiohttp.ClientTimeout(total=30)) as resp:
                    elapsed = time.time() - start_time
                    print(f"[AI Test] Response received in {elapsed:.2f}s, status: {resp.status}", file=sys.stderr)
                    
                    if resp.status == 200:
                        data = await resp.json()
                        if 'choices' in data or 'response' in data or 'content' in data:
                            diagnostics["ai_response"] = True
                            print(f"[AI Test] ✓ AI service responded successfully", file=sys.stderr)
                            self.send_event("local-ai-test-result", {
                                "success": True,
                                "endpoint": endpoint,
                                "diagnostics": diagnostics,
                                "response_time": elapsed
                            })
                            self.send_log(f"✓ 本地 AI 連接成功: {endpoint} (響應時間: {elapsed:.2f}秒)", "success")
                            return
                        else:
                            diagnostics["errors"].append(f"AI 響應格式異常: {list(data.keys())}")
                    else:
                        error_text = await resp.text()
                        diagnostics["errors"].append(f"HTTP {resp.status}: {error_text[:200]}")
                        print(f"[AI Test] ✗ AI service returned error: {resp.status}", file=sys.stderr)
                        
            except asyncio.TimeoutError:
                elapsed = time.time() - start_time if 'start_time' in locals() else 30
                diagnostics["errors"].append(f"AI 請求超時 ({elapsed:.1f}秒)")
                print(f"[AI Test] ✗ AI request timeout after {elapsed:.2f}s", file=sys.stderr)
            except aiohttp.ClientConnectorError as e:
                diagnostics["errors"].append(f"無法連接到端點: {str(e)}")
                print(f"[AI Test] ✗ Connection error: {e}", file=sys.stderr)
            except Exception as e:
                diagnostics["errors"].append(f"AI 請求錯誤: {str(e)}")
                print(f"[AI Test] ✗ AI request error: {e}", file=sys.stderr)
        
        # 如果所有測試都失敗
        self.send_event("local-ai-test-result", {
            "success": False,
            "endpoint": endpoint,
            "diagnostics": diagnostics,
            "error": f"無法連接到本地 AI 服務。診斷信息：\n" + "\n".join(diagnostics["errors"])
        })
        self.send_log(f"✗ 本地 AI 連接失敗: {endpoint}", "error")
            
    except Exception as e:
        import traceback
        error_details = traceback.format_exc()
        print(f"[AI Test] Unexpected error: {error_details}", file=sys.stderr)
        diagnostics["errors"].append(f"未預期的錯誤: {str(e)}")
        self.send_event("local-ai-test-result", {
            "success": False,
            "endpoint": endpoint,
            "diagnostics": diagnostics,
            "error": str(e)
        })
        self.send_log(f"✗ 本地 AI 測試錯誤: {str(e)}", "error")


async def handle_test_tts_service(self, payload: Dict[str, Any]):
    """Test connection to TTS service (GPT-SoVITS) - 🔧 P2 優化：真正的語音生成測試"""
    import time as time_module
    endpoint = payload.get('endpoint', 'http://localhost:9881')
    
    diagnostics = {
        "endpoint": endpoint,
        "http_reachable": False,
        "tts_available": False,
        "voice_generation": False,
        "latency_ms": 0,
        "errors": []
    }
    
    try:
        import aiohttp
        start_time = time_module.time()
        
        async with aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=30)) as session:
            # 步驟 1: 測試 HTTP 可達性
            try:
                async with session.get(f"{endpoint}/") as resp:
                    if resp.status in [200, 404, 405]:
                        diagnostics["http_reachable"] = True
                        print(f"[TTS Test] ✓ HTTP 可達", file=sys.stderr)
            except Exception as e:
                diagnostics["errors"].append(f"HTTP 連接失敗: {str(e)}")
                print(f"[TTS Test] ✗ HTTP 連接失敗: {e}", file=sys.stderr)
            
            # 步驟 2: 嘗試獲取 TTS 服務狀態/可用語音列表
            tts_api_endpoints = [
                f"{endpoint}/",  # GPT-SoVITS 根端點
                f"{endpoint}/tts",
                f"{endpoint}/api/tts",
                f"{endpoint}/v1/audio/speech",  # OpenAI 兼容
            ]
            
            for api_url in tts_api_endpoints:
                try:
                    async with session.get(api_url, timeout=aiohttp.ClientTimeout(total=5)) as resp:
                        if resp.status in [200, 405]:  # GET 可能返回 405，但說明端點存在
                            diagnostics["tts_available"] = True
                            print(f"[TTS Test] ✓ TTS API 可用: {api_url}", file=sys.stderr)
                            break
                except:
                    continue
            
            # 步驟 3: 嘗試真正的語音生成測試
            if diagnostics["tts_available"] or diagnostics["http_reachable"]:
                test_text = "測試"
                tts_endpoints = [
                    (f"{endpoint}/", {"text": test_text, "text_language": "zh"}),  # GPT-SoVITS
                    (f"{endpoint}/tts", {"text": test_text}),
                    (f"{endpoint}/api/tts", {"text": test_text}),
                ]
                
                for tts_url, payload_data in tts_endpoints:
                    try:
                        gen_start = time_module.time()
                        async with session.post(tts_url, json=payload_data, timeout=aiohttp.ClientTimeout(total=20)) as resp:
                            if resp.status == 200:
                                content_type = resp.headers.get('content-type', '')
                                if 'audio' in content_type or 'octet-stream' in content_type:
                                    diagnostics["voice_generation"] = True
                                    diagnostics["latency_ms"] = int((time_module.time() - gen_start) * 1000)
                                    print(f"[TTS Test] ✓ 語音生成成功，延遲: {diagnostics['latency_ms']}ms", file=sys.stderr)
                                    break
                                else:
                                    # 可能返回 JSON 錯誤
                                    try:
                                        data = await resp.json()
                                        if 'audio' in data or 'wav' in str(data):
                                            diagnostics["voice_generation"] = True
                                            diagnostics["latency_ms"] = int((time_module.time() - gen_start) * 1000)
                                            break
                                    except:
                                        pass
                    except asyncio.TimeoutError:
                        diagnostics["errors"].append(f"語音生成超時")
                    except Exception as e:
                        # 繼續嘗試其他端點
                        continue
            
            # 計算總延遲
            total_latency = int((time_module.time() - start_time) * 1000)
            if diagnostics["latency_ms"] == 0:
                diagnostics["latency_ms"] = total_latency
            
            # 判斷成功標準
            if diagnostics["voice_generation"]:
                self.send_event("tts-test-result", {
                    "success": True,
                    "endpoint": endpoint,
                    "diagnostics": diagnostics,
                    "latencyMs": diagnostics["latency_ms"],
                    "message": f"語音服務正常，生成延遲 {diagnostics['latency_ms']}ms"
                })
                self.send_log(f"✓ TTS 服務完全正常: {endpoint} (延遲: {diagnostics['latency_ms']}ms)", "success")
            elif diagnostics["tts_available"] or diagnostics["http_reachable"]:
                self.send_event("tts-test-result", {
                    "success": True,
                    "endpoint": endpoint,
                    "diagnostics": diagnostics,
                    "latencyMs": total_latency,
                    "message": "服務可達，但無法驗證語音生成（可能需要配置語音模型）"
                })
                self.send_log(f"⚠ TTS 服務可達但未驗證語音生成: {endpoint}", "warning")
            else:
                self.send_event("tts-test-result", {
                    "success": False,
                    "endpoint": endpoint,
                    "diagnostics": diagnostics,
                    "error": "無法連接到 TTS 服務\n" + "\n".join(diagnostics["errors"])
                })
                self.send_log(f"✗ TTS 服務連接失敗: {endpoint}", "error")
            
    except Exception as e:
        import traceback
        print(f"[TTS Test] 異常: {traceback.format_exc()}", file=sys.stderr)
        self.send_event("tts-test-result", {
            "success": False,
            "endpoint": endpoint,
            "diagnostics": diagnostics,
            "error": str(e)
        })
        self.send_log(f"✗ TTS 測試錯誤: {str(e)}", "error")


async def handle_test_stt_service(self, payload: Dict[str, Any]):
    """Test connection to STT service (Whisper)"""
    endpoint = payload.get('endpoint', 'http://localhost:9000')
    
    try:
        import aiohttp
        
        async with aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=10)) as session:
            test_urls = [
                f"{endpoint}/",
                f"{endpoint}/transcribe",
                f"{endpoint}/api/transcribe",
            ]
            
            for test_url in test_urls:
                try:
                    async with session.get(test_url) as response:
                        if response.status in [200, 404, 405]:
                            self.send_event("stt-test-result", {
                                "success": True,
                                "endpoint": endpoint,
                                "status": response.status
                            })
                            self.send_log(f"✓ STT 服務連接成功: {endpoint}", "success")
                            return
                except:
                    continue
            
            self.send_event("stt-test-result", {
                "success": False,
                "endpoint": endpoint,
                "error": "無法連接到 STT 服務"
            })
            self.send_log(f"✗ STT 服務連接失敗: {endpoint}", "error")
            
    except Exception as e:
        self.send_event("stt-test-result", {
            "success": False,
            "endpoint": endpoint,
            "error": str(e)
        })
        self.send_log(f"✗ STT 測試錯誤: {str(e)}", "error")


async def handle_get_ai_settings(self, payload: Dict[str, Any] = None):
    """獲取 AI 設置（包括 Gemini API Key）"""
    try:
        # 從數據庫獲取設置
        settings = await db.get_ai_settings()
        
        result = {
            'geminiApiKey': settings.get('gemini_api_key', ''),
            'localAiEndpoint': settings.get('local_ai_endpoint', 'http://localhost:11434'),
            'localAiModel': settings.get('local_ai_model', ''),
            'apiType': settings.get('api_type', 'gemini'),
        }
        
        self.send_event("ai-settings-loaded", result)
        
    except Exception as e:
        import sys
        print(f"[Backend] Error loading AI settings: {e}", file=sys.stderr)
        self.send_event("ai-settings-loaded", {})


async def handle_save_ai_settings(self, payload: Dict[str, Any]):
    """Save AI and voice service settings"""
    try:
        # Store settings in memory (for legacy compatibility)
        settings = {
            "apiType": payload.get('apiType', 'gemini'),
            "apiKey": payload.get('apiKey', ''),
            "endpoint": payload.get('endpoint', ''),
            "localAiEndpoint": payload.get('localAiEndpoint', 'http://localhost:3002'),
            "localAiModel": payload.get('localAiModel', ''),
            "ttsEndpoint": payload.get('ttsEndpoint', 'http://localhost:9881'),
            "ttsEnabled": payload.get('ttsEnabled', False),
            "ttsVoice": payload.get('ttsVoice', ''),
            "sttEndpoint": payload.get('sttEndpoint', 'http://localhost:9000'),
            "sttEnabled": payload.get('sttEnabled', False)
        }
        
        # Store in self for later use
        self.ai_settings = settings
        
        # 🔧 關鍵修復：同時保存到數據庫（使用 snake_case 鍵名）
        db_settings = {
            'local_ai_endpoint': payload.get('localAiEndpoint', ''),
            'local_ai_model': payload.get('localAiModel', ''),
            'gemini_api_key': payload.get('geminiApiKey', ''),  # 添加 Gemini API Key 保存
            'api_type': payload.get('apiType', 'gemini'),
        }
        await db.update_ai_settings(db_settings)
        
        # 重新載入 AI 服務設置
        await ai_auto_chat.initialize()
        
        # 設置 AI 配置
        endpoint = payload.get('localAiEndpoint', '')
        model = payload.get('localAiModel', '')
        if endpoint:
            ai_auto_chat.set_ai_config(endpoint, model)
            self.send_log(f"✓ AI 端點已配置: {endpoint}", "success")
        
        self.send_event("ai-settings-saved", {"success": True})
        self.send_log("AI 和語音服務設置已保存到數據庫", "success")
        
    except Exception as e:
        import traceback
        traceback.print_exc(file=sys.stderr)
        self.send_event("ai-settings-saved", {"success": False, "error": str(e)})
        self.send_log(f"保存 AI 設置失敗: {str(e)}", "error")


async def handle_set_autonomous_mode(self, payload: Dict[str, Any]):
    """🆕 設置 AI 自主模式開關"""
    enabled = payload.get('enabled', False)
    
    try:
        # 保存到數據庫
        await db.execute("""
            INSERT INTO ai_settings (key, value) VALUES ('autonomous_mode', ?)
            ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = CURRENT_TIMESTAMP
        """, ('1' if enabled else '0',))
        
        # 更新 AI 服務
        if ai_auto_chat:
            ai_auto_chat.autonomous_mode = enabled
            self.send_log(f"AI 自主模式已{'啟用' if enabled else '關閉'}", "success")
        
        self.send_event("autonomous-mode-updated", {
            "success": True,
            "enabled": enabled
        })
        
    except Exception as e:
        print(f"[Backend] Error setting autonomous mode: {e}", file=sys.stderr)
        self.send_event("autonomous-mode-updated", {
            "success": False,
            "error": str(e)
        })


async def handle_generate_with_local_ai(self, payload: Dict[str, Any]):
    """Generate text using local AI service"""
    endpoint = payload.get('endpoint', getattr(self, 'ai_settings', {}).get('localAiEndpoint', 'http://localhost:3002'))
    prompt = payload.get('prompt', '')
    model = payload.get('model', '')
    
    try:
        import aiohttp
        
        # Try OpenAI-compatible API format
        request_data = {
            "model": model or "default",
            "messages": [{"role": "user", "content": prompt}],
            "max_tokens": 500,
            "temperature": 0.7
        }
        
        async with aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=60)) as session:
            async with session.post(f"{endpoint}/v1/chat/completions", json=request_data) as response:
                if response.status == 200:
                    result = await response.json()
                    generated_text = result.get('choices', [{}])[0].get('message', {}).get('content', '')
                    
                    self.send_event("local-ai-generation-result", {
                        "success": True,
                        "text": generated_text
                    })
                    return
                else:
                    error_text = await response.text()
                    self.send_event("local-ai-generation-result", {
                        "success": False,
                        "error": f"API 返回 {response.status}: {error_text}"
                    })
                    
    except Exception as e:
        self.send_event("local-ai-generation-result", {
            "success": False,
            "error": str(e)
        })


async def handle_summarize_conversation(self, payload: Dict[str, Any]):
    """生成對話摘要"""
    try:
        user_id = payload.get('userId', '')
        max_messages = payload.get('maxMessages', 50)
        
        result = await vector_memory.summarize_conversation(
            user_id=user_id,
            max_messages=max_messages
        )
        
        self.send_event("conversation-summarized", result)
    except Exception as e:
        self.send_event("conversation-summarized", {
            "success": False,
            "error": str(e)
        })


async def handle_ai_analyze_interest(self, payload: Dict[str, Any]):
    """AI 分析興趣信號"""
    import sys
    
    try:
        from automation_workflow import get_automation_workflow_service
        
        service = get_automation_workflow_service()
        result = await service.handle_analyze_interest(payload)
        
        self.send_event("ai:analyze-interest-result", result)
        print(f"[AutomationWorkflow] 興趣分析: hasInterest={result.get('hasInterest')}", file=sys.stderr)
        
    except Exception as e:
        print(f"[AutomationWorkflow] 興趣分析錯誤: {e}", file=sys.stderr)
        self.send_event("ai:analyze-interest-result", {"success": False, "error": str(e)})


# ============ 🆕 AI Team 執行相關 ============

async def handle_ai_execution_save(self, payload: Dict[str, Any]):
    """🔧 Phase 4: 持久化 AI 執行狀態到數據庫"""
    import sys
    
    try:
        execution_id = payload.get('id')
        if not execution_id:
            return
        
        # 確保表存在
        await db.execute("""
            CREATE TABLE IF NOT EXISTS ai_executions (
                id TEXT PRIMARY KEY,
                execution_type TEXT NOT NULL,
                status TEXT DEFAULT 'running',
                mode TEXT,
                goal TEXT,
                target_users TEXT,
                role_accounts TEXT,
                group_id TEXT,
                group_name TEXT,
                message_history TEXT DEFAULT '[]',
                stats TEXT DEFAULT '{}',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                completed_at TIMESTAMP
            )
        """)
        
        # 插入或更新
        await db.execute("""
            INSERT OR REPLACE INTO ai_executions 
            (id, execution_type, status, mode, goal, target_users, role_accounts, 
             group_id, group_name, message_history, stats, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
        """, (
            execution_id,
            payload.get('executionType', 'private'),
            payload.get('status', 'running'),
            payload.get('mode', 'hybrid'),
            payload.get('goal', ''),
            payload.get('targetUsers', '[]'),
            payload.get('roleAccounts', '[]'),
            payload.get('groupId'),
            payload.get('groupName'),
            payload.get('messageHistory', '[]'),
            payload.get('stats', '{}')
        ))
        
        print(f"[AIExecution] ✓ 已保存執行狀態: {execution_id}", file=sys.stderr)
        
    except Exception as e:
        print(f"[AIExecution] 保存執行狀態失敗: {e}", file=sys.stderr)


async def handle_ai_execution_get_active(self, payload: Dict[str, Any]):
    """🔧 Phase 4: 獲取活躍的 AI 執行任務"""
    import sys
    
    try:
        executions = []
        
        # 確保表存在
        try:
            cursor = await db.execute("""
                SELECT * FROM ai_executions 
                WHERE status IN ('running', 'executing', 'paused')
                ORDER BY updated_at DESC
                LIMIT 10
            """)
            rows = await cursor.fetchall()
            
            for row in rows:
                executions.append({
                    'id': row['id'],
                    'executionType': row['execution_type'],
                    'status': row['status'],
                    'mode': row['mode'],
                    'goal': row['goal'],
                    'targetUsers': row['target_users'],
                    'roleAccounts': row['role_accounts'],
                    'groupId': row['group_id'],
                    'groupName': row['group_name'],
                    'messageHistory': row['message_history'],
                    'stats': row['stats']
                })
            
            print(f"[AIExecution] 找到 {len(executions)} 個活躍執行", file=sys.stderr)
            
        except Exception as query_err:
            if 'no such table' not in str(query_err).lower():
                print(f"[AIExecution] 查詢失敗: {query_err}", file=sys.stderr)
        
        # 🔧 發送事件返回結果
        self.send_event("ai-execution:active-list", {"executions": executions})
        
    except Exception as e:
        print(f"[AIExecution] 獲取活躍執行失敗: {e}", file=sys.stderr)
        self.send_event("ai-execution:active-list", {"executions": [], "error": str(e)})
        return {"executions": [], "error": str(e)}

