"""
Extracted handler implementations: qa
Auto-generated by refactor_main.py
"""
import json
import sys
import time
import asyncio
import traceback
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

from service_context import get_service_context
from service_locator import get_knowledge_search_engine

# All handlers receive (self, payload) where self is BackendService instance.
# They are called via: await handler_impl(self, payload)
# Inside, use self.db, self.send_event(), self.telegram_manager, etc.
# This is a transitional pattern - later, replace self.xxx with ctx.xxx


async def handle_add_qa_pair(self, payload: Dict[str, Any]):
    """Add a QA pair"""
    try:
        question = payload.get('question')
        answer = payload.get('answer')
        category = payload.get('category', 'general')
        keywords = payload.get('keywords', [])
        media_ids = payload.get('mediaIds', [])
        
        if not question or not answer:
            self.send_event("qa-pair-added", {"success": False, "error": "Question and answer required"})
            return
        
        search_engine = get_knowledge_search_engine()
        qa_id = await search_engine.add_qa_pair(
            question=question,
            answer=answer,
            category=category,
            keywords=keywords,
            media_ids=media_ids
        )
        
        self.send_event("qa-pair-added", {
            "success": True,
            "id": qa_id
        })
        self.send_log("問答對已添加", "success")
    except Exception as e:
        self.send_event("qa-pair-added", {
            "success": False,
            "error": str(e)
        })


async def handle_get_qa_pairs(self, payload: Dict[str, Any]):
    """Get all QA pairs"""
    try:
        category = payload.get('category')
        search_engine = get_knowledge_search_engine()
        qa_pairs = await search_engine.get_all_qa_pairs(category)
        
        self.send_event("qa-pairs-list", {
            "success": True,
            "qaPairs": qa_pairs
        })
    except Exception as e:
        self.send_event("qa-pairs-list", {
            "success": False,
            "error": str(e)
        })


async def handle_import_qa(self, payload: Dict[str, Any]):
    """Import QA pairs from file"""
    try:
        file_path = payload.get('filePath')
        file_type = payload.get('fileType', 'csv')
        
        search_engine = get_knowledge_search_engine()
        if file_type == 'csv':
            result = await search_engine.import_qa_from_csv(file_path)
        else:
            result = await search_engine.import_qa_from_json(file_path)
        
        self.send_event("qa-imported", result)
        if result.get('success'):
            self.send_log(f"導入了 {result.get('imported', 0)} 條問答對", "success")
    except Exception as e:
        self.send_event("qa-imported", {
            "success": False,
            "error": str(e)
        })

