"""
Extracted handler implementations: ai_team
Auto-generated by refactor_main.py
"""
import json
import sys
import time
import asyncio
import traceback
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

from service_context import get_service_context
from database import db

from service_locator import ai_auto_chat
# All handlers receive (self, payload) where self is BackendService instance.
# They are called via: await handler_impl(self, payload)
# Inside, use self.db, self.send_event(), self.telegram_manager, etc.
# This is a transitional pattern - later, replace self.xxx with ctx.xxx


async def handle_get_customer_state(self, payload: Dict[str, Any]):
    """🆕 獲取客戶狀態（AI 自主引擎）"""
    user_id = payload.get('userId', '')
    
    try:
        if ai_auto_chat and ai_auto_chat.autonomous_engine:
            state = await ai_auto_chat.autonomous_engine.get_customer_state(user_id)
            if state:
                from dataclasses import asdict
                state_dict = asdict(state)
                # 轉換枚舉為字符串
                state_dict['conversion_stage'] = state.conversion_stage.value
                state_dict['customer_style'] = state.customer_style.value
                self.send_event("customer-state", {
                    "success": True,
                    "state": state_dict
                })
            else:
                self.send_event("customer-state", {
                    "success": True,
                    "state": None
                })
        else:
            self.send_event("customer-state", {
                "success": False,
                "error": "AI 自主引擎未初始化"
            })
    except Exception as e:
        print(f"[Backend] Error getting customer state: {e}", file=sys.stderr)
        self.send_event("customer-state", {
            "success": False,
            "error": str(e)
        })


async def handle_get_smart_system_stats(self, payload: Dict[str, Any]):
    """🆕 獲取智能系統統計"""
    stats = {
        'memories': 0,
        'tags': 0,
        'emotions': 0,
        'workflows': 0,
        'followups': 0,
        'knowledge': 0
    }
    
    try:
        # 記憶統計
        try:
            result = await db.fetch_one("SELECT COUNT(*) as count FROM conversation_memories")
            stats['memories'] = result['count'] if result else 0
        except:
            pass
        
        # 標籤統計
        try:
            result = await db.fetch_one("SELECT COUNT(*) as count FROM customer_tags")
            stats['tags'] = result['count'] if result else 0
        except:
            pass
        
        # 情緒統計
        try:
            result = await db.fetch_one("SELECT COUNT(*) as count FROM emotion_records")
            stats['emotions'] = result['count'] if result else 0
        except:
            pass
        
        # 工作流統計
        try:
            result = await db.fetch_one("SELECT COUNT(*) as count FROM workflow_executions")
            stats['workflows'] = result['count'] if result else 0
        except:
            pass
        
        # 跟進任務統計
        try:
            result = await db.fetch_one("SELECT COUNT(*) as count FROM followup_tasks WHERE status = 'pending'")
            stats['followups'] = result['count'] if result else 0
        except:
            pass
        
        # 知識學習統計
        try:
            result = await db.fetch_one("SELECT COUNT(*) as count FROM learned_knowledge")
            stats['knowledge'] = result['count'] if result else 0
        except:
            pass
        
        self.send_event("smart-system-stats", stats)
        print(f"[Backend] Smart system stats: {stats}", file=sys.stderr)
        
    except Exception as e:
        print(f"[Backend] Error getting smart system stats: {e}", file=sys.stderr)
        self.send_event("smart-system-stats", stats)



async def handle_ai_team_pause_execution(self, payload: Dict[str, Any]):
    """暫停 AI 團隊執行"""
    executor = self.get_ai_team_executor()
    execution_id = payload.get('executionId')
    executor.pause_execution(execution_id)


async def handle_ai_team_resume_execution(self, payload: Dict[str, Any]):
    """恢復 AI 團隊執行"""
    executor = self.get_ai_team_executor()
    execution_id = payload.get('executionId')
    executor.resume_execution(execution_id)


async def handle_ai_team_stop_execution(self, payload: Dict[str, Any]):
    """停止 AI 團隊執行"""
    executor = self.get_ai_team_executor()
    execution_id = payload.get('executionId')
    executor.stop_execution(execution_id)


async def handle_ai_team_add_targets(self, payload: Dict[str, Any]):
    """添加目標用戶到 AI 團隊隊列"""
    import sys
    targets = payload.get('targets', [])
    print(f"[AITeam] 添加 {len(targets)} 個目標用戶", file=sys.stderr)
    self.send_log(f"🎯 已添加 {len(targets)} 個目標用戶到 AI 銷售隊列", "info")


async def handle_ai_team_start_execution(self, payload: Dict[str, Any]):
    """啟動 AI 團隊執行（支持劇本/無劇本/混合模式）"""
    import sys
    
    try:
        execution_id = payload.get('executionId')
        goal = payload.get('goal', '')
        intent = payload.get('intent', {})
        strategy = payload.get('strategy', {})
        roles = payload.get('roles', [])
        mode = payload.get('mode', 'hybrid')  # scripted / scriptless / hybrid
        account_matches = payload.get('accountMatches', [])
        scriptless_config = payload.get('scriptlessConfig', {})
        analysis_interval = payload.get('analysisInterval', 10)
        target_users = payload.get('targetUsers', [])  # 🆕 目標用戶列表
        
        print(f"[AITeam] 啟動執行: {execution_id}, 模式: {mode}", file=sys.stderr)
        print(f"[AITeam] 目標: {goal}", file=sys.stderr)
        print(f"[AITeam] 角色數量: {len(roles)}, 帳號匹配: {len(account_matches)}, 目標用戶: {len(target_users)}", file=sys.stderr)
        
        # 存儲執行狀態
        if not hasattr(self, '_ai_team_executions'):
            self._ai_team_executions = {}
        
        self._ai_team_executions[execution_id] = {
            'id': execution_id,
            'goal': goal,
            'intent': intent,
            'strategy': strategy,
            'roles': roles,
            'mode': mode,
            'account_matches': account_matches,
            'scriptless_config': scriptless_config,
            'analysis_interval': analysis_interval,
            'target_users': target_users,  # 🆕 保存目標用戶
            'current_target_index': 0,     # 🆕 當前處理的目標用戶索引
            'status': 'running',
            'message_count': 0,
            'response_count': 0,
            'current_phase': 0,
            'message_history': [],  # 🆕 消息歷史
            'created_at': datetime.now().isoformat()
        }
        
        target_info = f"，目標 {len(target_users)} 人" if target_users else ""
        self.send_log(f"🚀 AI 團隊開始執行: {goal[:30]}...{target_info}", "info")
        self.send_event("ai-team:execution-started", {
            "executionId": execution_id,
            "mode": mode,
            "roleCount": len(roles),
            "targetCount": len(target_users)
        })
        
        # 🔧 Phase 3 修復：確保私聊輪詢器運行以接收目標用戶回覆
        await self._ensure_private_poller_running(account_matches)
        
        # 根據模式啟動執行
        if mode == 'scriptless':
            # 無劇本模式：等待前端觸發消息生成
            self.send_log(f"📝 無劇本模式已就緒，等待對話開始...", "info")
        else:
            # 劇本或混合模式：按階段執行
            asyncio.create_task(self._execute_scripted_phase(execution_id))
        
    except Exception as e:
        print(f"[AITeam] Start execution error: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc(file=sys.stderr)
        self.send_event("ai-team:execution-error", {
            "executionId": payload.get('executionId'),
            "error": str(e)
        })


    # TODO: 實現具體的階段消息發送邏輯
    # 這裡可以與 script_engine 整合

async def handle_ai_team_adjust_strategy(self, payload: Dict[str, Any]):
    """調整 AI 團隊策略（動態分析觸發）"""
    import sys
    
    try:
        execution_id = payload.get('executionId')
        adjustment = payload.get('adjustment', {})
        
        print(f"[AITeam] 調整策略: {execution_id}", file=sys.stderr)
        print(f"[AITeam] 調整動作: {adjustment.get('action')}, 原因: {adjustment.get('reason')}", file=sys.stderr)
        
        execution = self._ai_team_executions.get(execution_id) if hasattr(self, '_ai_team_executions') else None
        if not execution:
            return
        
        action = adjustment.get('action')
        
        if action == 'advance_phase':
            # 推進階段
            new_phase = adjustment.get('newPhase', execution.get('current_phase', 0) + 1)
            execution['current_phase'] = new_phase
            asyncio.create_task(self._execute_scripted_phase(execution_id))
            
        elif action == 'switch_role':
            # 切換角色
            new_role = adjustment.get('newRole')
            self.send_event("ai-team:role-switched", {
                "executionId": execution_id,
                "newRole": new_role,
                "reason": adjustment.get('reason')
            })
            
        elif action == 'activate_atmosphere':
            # 活躍氣氛
            self.send_log("💬 引入活躍角色帶動氣氛...", "info")
            
        elif action == 'handle_objection':
            # 處理異議
            self.send_log("🎯 引入專家處理客戶顧慮...", "info")
        
        self.send_event("ai-team:strategy-adjusted", {
            "executionId": execution_id,
            "adjustment": adjustment
        })
        
    except Exception as e:
        print(f"[AITeam] Adjust strategy error: {e}", file=sys.stderr)


async def handle_ai_team_generate_scriptless_message(self, payload: Dict[str, Any]):
    """無劇本模式：AI 自主生成對話"""
    import sys
    
    try:
        execution_id = payload.get('executionId')
        role_id = payload.get('roleId')
        role_name = payload.get('roleName', '')
        role_personality = payload.get('rolePersonality', '')
        role_speaking_style = payload.get('roleSpeakingStyle', '')
        prompt = payload.get('prompt', '')
        context = payload.get('context', {})
        
        print(f"[AITeam] 無劇本生成消息: {role_name}", file=sys.stderr)
        
        # 使用 AI 生成消息
        generated_content = await self._generate_ai_message(
            role_name=role_name,
            role_personality=role_personality,
            role_speaking_style=role_speaking_style,
            prompt=prompt,
            context=context
        )
        
        if generated_content:
            self.send_event("ai-team:scriptless-message-generated", {
                "executionId": execution_id,
                "roleId": role_id,
                "content": generated_content,
                "reasoning": f"根據 {context.get('currentStage', '對話')} 階段自動生成"
            })
        else:
            self.send_event("ai-team:scriptless-message-generated", {
                "executionId": execution_id,
                "roleId": role_id,
                "content": None,
                "error": "生成失敗"
            })
        
    except Exception as e:
        print(f"[AITeam] Generate scriptless message error: {e}", file=sys.stderr)
        self.send_event("ai-team:scriptless-message-generated", {
            "executionId": payload.get('executionId'),
            "content": None,
            "error": str(e)
        })


async def handle_ai_team_send_scriptless_message(self, payload: Dict[str, Any]):
    """發送無劇本模式生成的消息到目標用戶"""
    import sys
    
    try:
        execution_id = payload.get('executionId')
        role_id = payload.get('roleId')
        content = payload.get('content')
        target_user_id = payload.get('targetUserId')  # 可選：指定目標用戶
        
        execution = self._ai_team_executions.get(execution_id) if hasattr(self, '_ai_team_executions') else None
        if not execution:
            print(f"[AITeam] 未找到執行 {execution_id}", file=sys.stderr)
            return
        
        # 找到對應的帳號
        account_match = next(
            (m for m in execution.get('account_matches', []) if m.get('roleId') == role_id),
            None
        )
        
        if not account_match:
            print(f"[AITeam] 未找到角色 {role_id} 對應的帳號", file=sys.stderr)
            return
        
        account_id = account_match.get('accountId')
        account_phone = account_match.get('accountPhone')
        
        # 🆕 獲取目標用戶
        target_users = execution.get('target_users', [])
        current_target_index = execution.get('current_target_index', 0)
        
        if target_user_id:
            # 使用指定的目標用戶
            target_user = next((u for u in target_users if str(u.get('id')) == str(target_user_id) or str(u.get('telegramId')) == str(target_user_id)), None)
        elif target_users and current_target_index < len(target_users):
            # 使用當前索引的目標用戶
            target_user = target_users[current_target_index]
        else:
            target_user = None
        
        send_success = False
        
        if target_user:
            telegram_id = target_user.get('telegramId') or target_user.get('id')
            target_name = target_user.get('firstName') or target_user.get('username') or telegram_id
            
            print(f"[AITeam] 準備發送消息到 {target_name} (ID: {telegram_id}), 使用帳號 {account_phone}", file=sys.stderr)
            
            # 實際發送消息（帶擬人化延遲）
            try:
                # 🔧 修復: 使用正確的客戶端獲取方式
                client = None
                if account_phone and account_phone in self.telegram_manager.clients:
                    client = self.telegram_manager.clients[account_phone]
                
                if client and client.is_connected:
                    # 🆕 擬人化延遲：模擬打字時間
                    import random
                    typing_delay = self._calculate_typing_delay(content)
                    
                    # 發送「正在輸入」狀態
                    try:
                        from pyrogram.raw.functions.messages import SetTyping
                        from pyrogram.raw.types import SendMessageTypingAction
                        await client.invoke(
                            SetTyping(
                                peer=await client.resolve_peer(int(telegram_id)),
                                action=SendMessageTypingAction()
                            )
                        )
                    except Exception as typing_err:
                        print(f"[AITeam] 發送輸入狀態失敗: {typing_err}", file=sys.stderr)
                    
                    # 等待打字延遲
                    self.send_log(f"⌨️ 正在輸入... ({typing_delay:.1f}秒)", "info")
                    await asyncio.sleep(typing_delay)
                    
                    # 發送私聊消息
                    await client.send_message(int(telegram_id), content)
                    send_success = True
                    
                    # 記錄消息歷史
                    if 'message_history' not in execution:
                        execution['message_history'] = []
                    execution['message_history'].append({
                        'role': account_match.get('roleName'),
                        'content': content,
                        'targetUser': target_name,
                        'timestamp': datetime.now().isoformat(),
                        'isFromCustomer': False
                    })
                    
                    self.send_log(f"📤 [{account_match.get('roleName')}] → {target_name}: {content[:30]}...", "success")
                else:
                    self.send_log(f"⚠️ 帳號 {account_phone} 未連接", "warning")
            except Exception as send_error:
                print(f"[AITeam] 發送消息失敗: {send_error}", file=sys.stderr)
                self.send_log(f"❌ 發送失敗: {str(send_error)[:50]}", "error")
        else:
            print(f"[AITeam] 無目標用戶，消息僅記錄", file=sys.stderr)
            # 僅記錄消息（用於演示或測試）
            self.send_log(f"📝 [{account_match.get('roleName')}] (模擬): {content[:50]}...", "info")
        
        # 更新統計
        execution['message_count'] = execution.get('message_count', 0) + 1
        
        self.send_event("ai-team:message-sent", {
            "executionId": execution_id,
            "roleId": role_id,
            "content": content,
            "totalSent": execution['message_count'],
            "targetUser": target_user.get('firstName') if target_user else None,
            "success": send_success
        })
        
    except Exception as e:
        print(f"[AITeam] Send scriptless message error: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()


async def handle_ai_team_conversion_signal(self, payload: Dict[str, Any]):
    """處理轉化信號"""
    import sys
    
    try:
        execution_id = payload.get('executionId')
        signal = payload.get('signal', '')
        recommended_role = payload.get('recommendedRole', 'sales_expert')
        
        print(f"[AITeam] 檢測到轉化信號: {signal}", file=sys.stderr)
        
        execution = self._ai_team_executions.get(execution_id) if hasattr(self, '_ai_team_executions') else None
        if not execution:
            return
        
        # 記錄轉化信號
        if 'conversion_signals' not in execution:
            execution['conversion_signals'] = []
        
        execution['conversion_signals'].append({
            'signal': signal,
            'timestamp': datetime.now().isoformat(),
            'recommended_role': recommended_role
        })
        
        self.send_log(f"🎯 轉化信號: {signal[:50]}...", "success")
        
        # 通知前端切換角色
        self.send_event("ai-team:conversion-signal-detected", {
            "executionId": execution_id,
            "signal": signal,
            "recommendedRole": recommended_role,
            "action": "switch_to_closer"
        })
        
    except Exception as e:
        print(f"[AITeam] Conversion signal error: {e}", file=sys.stderr)


async def handle_ai_team_customer_reply(self, payload: Dict[str, Any]):
    """
    處理目標客戶的回覆（客戶回覆自動監聽）
    當收到私信時檢查是否為 AI 團隊執行任務的目標用戶
    """
    import sys
    
    try:
        user_id = str(payload.get('userId', ''))
        username = payload.get('username', '')
        first_name = payload.get('firstName', '')
        text = payload.get('text', '')
        phone = payload.get('phone', '')
        
        # 🔧 Phase 3 調試：記錄收到的私聊消息
        print(f"[AITeam] 📨 收到私聊消息: userId={user_id}, username={username}, text={text[:50] if text else 'empty'}...", file=sys.stderr)
        
        if not user_id:
            print(f"[AITeam] ⚠️ 跳過：userId 為空", file=sys.stderr)
            return
        
        if not hasattr(self, '_ai_team_executions'):
            print(f"[AITeam] ⚠️ 跳過：沒有執行中的任務 (_ai_team_executions 未初始化)", file=sys.stderr)
            return
        
        if len(self._ai_team_executions) == 0:
            print(f"[AITeam] ⚠️ 跳過：沒有執行中的任務 (列表為空)", file=sys.stderr)
            return
        
        print(f"[AITeam] 🔍 檢查 {len(self._ai_team_executions)} 個執行任務...", file=sys.stderr)
        
        # 遍歷所有執行中的任務，檢查是否為目標用戶
        found_match = False
        for execution_id, execution in self._ai_team_executions.items():
            exec_status = execution.get('status', 'unknown')
            if exec_status != 'running':
                print(f"[AITeam]   - 任務 {execution_id}: 狀態={exec_status} (跳過)", file=sys.stderr)
                continue
            
            target_users = execution.get('target_users', [])
            print(f"[AITeam]   - 任務 {execution_id}: running, 目標用戶={len(target_users)} 個", file=sys.stderr)
            
            # 🔧 調試：列出目標用戶的 ID
            for u in target_users:
                u_telegram_id = str(u.get('telegramId', ''))
                u_id = str(u.get('id', ''))
                u_name = u.get('firstName') or u.get('username') or 'unknown'
                print(f"[AITeam]     - 目標: {u_name}, telegramId={u_telegram_id}, id={u_id}", file=sys.stderr)
            
            # 檢查發送者是否為目標用戶
            is_target = any(
                str(u.get('telegramId')) == user_id or str(u.get('id')) == user_id
                for u in target_users
            )
            
            if not is_target:
                print(f"[AITeam]     ❌ userId {user_id} 不在目標用戶列表中", file=sys.stderr)
                continue
            
            found_match = True
            print(f"[AITeam] 🎯 目標用戶回覆！執行ID: {execution_id}, 用戶: {first_name or username}", file=sys.stderr)
            
            # 記錄客戶回覆到消息歷史
            if 'message_history' not in execution:
                execution['message_history'] = []
            
            execution['message_history'].append({
                'role': 'customer',
                'content': text,
                'userId': user_id,
                'username': username,
                'firstName': first_name,
                'timestamp': datetime.now().isoformat(),
                'isFromCustomer': True
            })
            
            # 更新統計
            execution['response_count'] = execution.get('response_count', 0) + 1
            
            # 發送事件通知前端
            self.send_event("ai-team:customer-reply", {
                "executionId": execution_id,
                "userId": user_id,
                "username": username,
                "firstName": first_name,
                "text": text,
                "totalResponses": execution['response_count'],
                "messageCount": len(execution.get('message_history', []))
            })
            
            self.send_log(f"💬 客戶回覆 [{first_name or username}]: {text[:50]}...", "success")
            
            # 🆕 檢查是否需要自動觸發下一輪 AI 對話
            mode = execution.get('mode', 'hybrid')
            if mode in ['scriptless', 'hybrid']:
                # 通知前端生成下一條消息
                self.send_event("ai-team:trigger-next-message", {
                    "executionId": execution_id,
                    "customerMessage": text,
                    "customerId": user_id,
                    "customerName": first_name or username
                })
            
            # 只處理第一個匹配的執行任務
            break
            
    except Exception as e:
        print(f"[AITeam] Customer reply handling error: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()


async def handle_ai_team_send_manual_message(self, payload: Dict[str, Any]):
    """
    處理手動介入發送的消息
    當用戶在手動模式下發送消息時調用
    """
    import sys
    
    try:
        execution_id = payload.get('executionId')
        role_id = payload.get('roleId')
        role_name = payload.get('roleName', 'Unknown')
        content = payload.get('content', '')
        target_user_id = payload.get('targetUserId')
        
        if not execution_id or not content:
            return
        
        execution = self._ai_team_executions.get(execution_id)
        if not execution:
            self.send_log(f"找不到執行任務: {execution_id}", "warning")
            return
        
        # 查找目標用戶和對應帳號
        target_users = execution.get('target_users', [])
        account_matches = execution.get('account_matches', [])
        
        # 🔧 修復: 查找角色對應的帳號（同時獲取 phone）
        account_id = None
        account_phone = None
        for match in account_matches:
            if match.get('roleId') == role_id:
                account_id = match.get('accountId')
                account_phone = match.get('accountPhone')
                break
        
        if not account_id:
            # 使用第一個可用帳號
            if account_matches:
                account_id = account_matches[0].get('accountId')
                account_phone = account_matches[0].get('accountPhone')
        
        # 查找目標用戶的 Telegram ID
        telegram_id = None
        target_name = "未知用戶"
        
        if target_user_id:
            for user in target_users:
                if str(user.get('id')) == str(target_user_id) or str(user.get('telegramId')) == str(target_user_id):
                    telegram_id = user.get('telegramId') or user.get('id')
                    target_name = user.get('firstName') or user.get('username') or str(telegram_id)
                    break
        
        if not telegram_id and target_users:
            current_idx = execution.get('current_target_index', 0)
            if current_idx < len(target_users):
                user = target_users[current_idx]
                telegram_id = user.get('telegramId') or user.get('id')
                target_name = user.get('firstName') or user.get('username') or str(telegram_id)
        
        send_success = False
        
        if telegram_id and account_phone:
            try:
                # 🔧 修復: 使用正確的客戶端獲取方式
                client = None
                if account_phone in self.telegram_manager.clients:
                    client = self.telegram_manager.clients[account_phone]
                
                if client and client.is_connected:
                    # 擬人化延遲
                    typing_delay = self._calculate_typing_delay(content)
                    
                    # 發送「正在輸入」狀態
                    try:
                        from pyrogram.raw.functions.messages import SetTyping
                        from pyrogram.raw.types import SendMessageTypingAction
                        await client.invoke(
                            SetTyping(
                                peer=await client.resolve_peer(int(telegram_id)),
                                action=SendMessageTypingAction()
                            )
                        )
                    except Exception:
                        pass
                    
                    import asyncio
                    await asyncio.sleep(typing_delay)
                    
                    # 發送消息
                    await client.send_message(int(telegram_id), content)
                    send_success = True
                    
                    self.send_log(f"🖐️ 手動消息 [{role_name}] → {target_name}: {content[:30]}...", "success")
                    
            except Exception as send_err:
                print(f"[AITeam] 手動消息發送失敗: {send_err}", file=sys.stderr)
                self.send_log(f"手動消息發送失敗: {send_err}", "error")
        
        # 記錄到消息歷史
        message_history = execution.get('message_history', [])
        message_history.append({
            'role': role_name,
            'content': content,
            'timestamp': datetime.now().isoformat(),
            'isFromCustomer': False,
            'isManual': True  # 標記為手動消息
        })
        execution['message_history'] = message_history
        
        # 更新統計
        execution['message_count'] = execution.get('message_count', 0) + 1
        
        # 發送事件
        self.send_event("ai-team:manual-message-sent", {
            "executionId": execution_id,
            "roleId": role_id,
            "roleName": role_name,
            "content": content,
            "targetUserId": telegram_id,
            "success": send_success
        })
        
    except Exception as e:
        print(f"[AITeam] Manual message error: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()


async def handle_ai_team_send_private_message(self, payload: Dict[str, Any]):
    """
    🆕 P0: 處理 AI 團隊自動私聊發送
    自動發送私聊消息給目標用戶
    """
    import sys
    
    try:
        execution_id = payload.get('executionId')
        account_id = payload.get('accountId')
        account_phone = payload.get('accountPhone')
        role_id = payload.get('roleId')
        role_name = payload.get('roleName', 'AI')
        target_user_id = payload.get('targetUserId')
        target_user_name = payload.get('targetUserName', 'User')
        content = payload.get('content', '')
        is_first_touch = payload.get('isFirstTouch', False)
        
        if not execution_id or not content or not target_user_id:
            self.send_log("私聊發送參數不完整", "warning")
            return
        
        print(f"[AITeam] 🚀 發送私聊: {role_name} → {target_user_name}", file=sys.stderr)
        self.send_log(f"🚀 開始私聊觸達: {role_name} → {target_user_name}", "info")
        
        send_success = False
        
        # 獲取客戶端並發送
        try:
            # 🔧 修復: 使用正確的客戶端獲取方式
            client = None
            if account_phone and account_phone in self.telegram_manager.clients:
                client = self.telegram_manager.clients[account_phone]
            
            if client and client.is_connected:
                # 擬人化延遲
                typing_delay = self._calculate_typing_delay(content)
                
                # 發送「正在輸入」狀態
                try:
                    from pyrogram.raw.functions.messages import SetTyping
                    from pyrogram.raw.types import SendMessageTypingAction
                    await client.invoke(
                        SetTyping(
                            peer=await client.resolve_peer(str(target_user_id)),
                            action=SendMessageTypingAction()
                        )
                    )
                except Exception as typing_err:
                    print(f"[AITeam] 輸入狀態發送失敗: {typing_err}", file=sys.stderr)
                
                # 等待打字延遲
                self.send_log(f"⌨️ 正在輸入... ({typing_delay:.1f}秒)", "info")
                await asyncio.sleep(typing_delay)
                
                # 發送消息
                # 嘗試多種方式解析用戶 ID
                try:
                    # 如果是純數字，直接使用
                    if str(target_user_id).isdigit():
                        await client.send_message(int(target_user_id), content)
                    else:
                        # 可能是 username
                        await client.send_message(str(target_user_id), content)
                    send_success = True
                except Exception as send_err:
                    print(f"[AITeam] 發送失敗，嘗試使用 username: {send_err}", file=sys.stderr)
                    # 嘗試作為 username
                    try:
                        await client.send_message(f"@{target_user_id}", content)
                        send_success = True
                    except Exception as retry_err:
                        print(f"[AITeam] 重試也失敗: {retry_err}", file=sys.stderr)
                
                if send_success:
                    log_prefix = "🎯 首次觸達" if is_first_touch else "💬 消息發送"
                    self.send_log(f"{log_prefix} [{role_name}] → {target_user_name}: {content[:30]}...", "success")
            else:
                self.send_log(f"帳號 {account_phone} 未連接，無法發送", "error")
                
        except Exception as client_err:
            print(f"[AITeam] 客戶端錯誤: {client_err}", file=sys.stderr)
            self.send_log(f"發送失敗: {client_err}", "error")
        
        # 記錄到執行狀態
        if hasattr(self, '_ai_team_executions') and execution_id in self._ai_team_executions:
            execution = self._ai_team_executions[execution_id]
            message_history = execution.get('message_history', [])
            message_history.append({
                'role': role_name,
                'content': content,
                'timestamp': datetime.now().isoformat(),
                'isFromCustomer': False,
                'isFirstTouch': is_first_touch,
                'targetUserId': target_user_id
            })
            execution['message_history'] = message_history
            execution['message_count'] = execution.get('message_count', 0) + 1
        
        # 發送事件
        self.send_event("ai-team:private-message-sent", {
            "executionId": execution_id,
            "roleId": role_id,
            "roleName": role_name,
            "targetUserId": target_user_id,
            "targetUserName": target_user_name,
            "content": content,
            "success": send_success,
            "isFirstTouch": is_first_touch
        })
        
    except Exception as e:
        print(f"[AITeam] Private message error: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()


async def handle_ai_team_request_suggestion(self, payload: Dict[str, Any]):
    """
    處理 AI 建議請求（手動模式下為用戶提供下一步建議）
    """
    import sys
    
    try:
        execution_id = payload.get('executionId')
        message_history = payload.get('messageHistory', [])
        current_stage = payload.get('currentStage', 'contact')
        
        if not execution_id:
            return
        
        execution = self._ai_team_executions.get(execution_id)
        if not execution:
            return
        
        # 構建 AI 請求
        goal = execution.get('goal', '')
        
        # 格式化消息歷史
        history_text = ""
        for msg in message_history[-10:]:
            sender = "客戶" if msg.get('isFromCustomer') else msg.get('role', 'AI')
            history_text += f"【{sender}】: {msg.get('content', '')}\n"
        
        # AI 提示詞
        prompt = f"""你是一個銷售專家，正在幫助用戶進行客戶轉化。

營銷目標：{goal}
當前階段：{current_stage}

最近對話：
{history_text}

請基於以上對話，給出下一條最佳回覆的建議。要求：
1. 自然、友好，不要太銷售化
2. 推進到下一個轉化階段
3. 簡短（1-2句話）
4. 如果客戶表現出興趣，可以適當推進
5. 如果客戶有疑慮，先解決疑慮

直接輸出建議的回覆內容，不要解釋："""

        # 調用 AI 生成建議
        suggestion = await self._generate_ai_suggestion(prompt)
        
        if suggestion:
            self.send_event("ai-team:suggestion-update", {
                "executionId": execution_id,
                "suggestion": suggestion
            })
        
    except Exception as e:
        print(f"[AITeam] Suggestion request error: {e}", file=sys.stderr)


# ==================== AI 團隊隊列管理 ====================

async def handle_ai_team_user_completed(self, payload: Dict[str, Any]):
    """標記當前用戶處理完成，準備處理下一個"""
    import sys
    try:
        execution_id = payload.get('executionId')
        user_id = payload.get('userId')
        result = payload.get('result', 'completed')  # completed, converted, skipped
        
        print(f"[AITeam] 用戶 {user_id} 處理完成: {result}", file=sys.stderr)
        
        # 更新數據庫記錄
        await db.execute("""
            UPDATE unified_contacts 
            SET last_contact_at = CURRENT_TIMESTAMP,
                funnel_stage = CASE WHEN ? = 'converted' THEN 'converted' ELSE funnel_stage END
            WHERE telegram_user_id = ?
        """, (result, user_id))
        
        # 發送完成事件
        self.send_event("ai-team:user-completed", {
            "executionId": execution_id,
            "userId": user_id,
            "result": result
        })
        
    except Exception as e:
        print(f"[AITeam] User completed error: {e}", file=sys.stderr)


async def handle_ai_team_queue_completed(self, payload: Dict[str, Any]):
    """整個隊列處理完成"""
    import sys
    try:
        execution_id = payload.get('executionId')
        stats = payload.get('stats', {})
        
        print(f"[AITeam] 隊列完成: {execution_id}", file=sys.stderr)
        print(f"[AITeam] 統計: 發送={stats.get('sent', 0)}, 回覆={stats.get('replied', 0)}, 轉化={stats.get('converted', 0)}", file=sys.stderr)
        
        self.send_log(f"✅ AI 團隊執行完成: 發送 {stats.get('sent', 0)} 條，回覆 {stats.get('replied', 0)} 條", "success")
        
        self.send_event("ai-team:execution-completed", {
            "executionId": execution_id,
            "stats": stats
        })
        
    except Exception as e:
        print(f"[AITeam] Queue completed error: {e}", file=sys.stderr)


async def handle_ai_team_next_user(self, payload: Dict[str, Any]):
    """開始處理下一個目標用戶"""
    import sys
    try:
        execution_id = payload.get('executionId')
        next_user = payload.get('nextUser')
        
        if not next_user:
            print(f"[AITeam] 隊列已空，沒有下一個用戶", file=sys.stderr)
            return
        
        user_id = next_user.get('id') or next_user.get('userId')
        username = next_user.get('username', 'Unknown')
        
        print(f"[AITeam] 開始處理下一用戶: {username} ({user_id})", file=sys.stderr)
        
        self.send_event("ai-team:next-user-started", {
            "executionId": execution_id,
            "userId": user_id,
            "username": username
        })
        
    except Exception as e:
        print(f"[AITeam] Next user error: {e}", file=sys.stderr)

