"""
Extracted handler implementations: accounts
Auto-generated by refactor_main.py
"""
import json
import sys
import time
import asyncio
import traceback
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

from service_context import get_service_context
from database import db
from config import config

import os
import gc
from error_handler import handle_error, AppError, ErrorType
from validators import validate_account, AccountValidator, ValidationError
from pathlib import Path
from service_locator import get_DeviceFingerprintGenerator, get_ProxyManager, get_WarmupManager
# All handlers receive (self, payload) where self is BackendService instance.
# They are called via: await handler_impl(self, payload)
# Inside, use self.db, self.send_event(), self.telegram_manager, etc.
# This is a transitional pattern - later, replace self.xxx with ctx.xxx


async def handle_add_account(self, payload: Dict[str, Any]):
    """Handle add-account command"""
    try:
        import sys
        import re as re_module
        import logging
        _logger = logging.getLogger('backend.add_account')
        
        owner_user_id = payload.get('ownerUserId')
        _logger.info(f"[add-account] START phone={payload.get('phone')}, proxy={payload.get('proxy')}, usePlatformApi={payload.get('usePlatformApi')}, ownerUserId={owner_user_id}")
        
        # 🔧 P4-3: 使用原子化的配額檢查 + 預留操作（防止並發超額）
        quota_reserved = False  # 追蹤預留狀態，用於後續 commit/rollback
        
        # Electron 模式跳過配額檢查
        is_electron = os.environ.get('ELECTRON_MODE', 'false').lower() == 'true'
        if not is_electron and owner_user_id:
            try:
                from core.quota_service import get_quota_service
                quota_service = get_quota_service()
                
                # 原子化：檢查 + 預留一步完成，持有鎖期間其他請求無法插入
                allowed, quota_result_obj = quota_service.atomic_check_and_reserve(
                    owner_user_id, 'tg_accounts', 1
                )
                quota_result = quota_result_obj.to_dict() if hasattr(quota_result_obj, 'to_dict') else {}
                
                print(f"[Backend] Atomic quota check for tg_accounts: allowed={allowed}, "
                      f"user_id={owner_user_id}, limit={quota_result.get('limit', '?')}, "
                      f"used={quota_result.get('used', '?')}, reserved={quota_result.get('reserved', '?')}", 
                      file=sys.stderr)
                
                if not allowed:
                    limit = quota_result.get('limit', 0)
                    used = quota_result.get('used', 0)
                    detail_msg = f"TG 帳號數量已達上限（已有 {used}/{limit} 個帳號）"
                    upgrade_msg = quota_result.get('upgrade_suggestion', '升級會員等級可添加更多帳號')
                    
                    self.send_event('account-added', {
                        'success': False,
                        'error': detail_msg,
                        'code': 'QUOTA_EXCEEDED',
                        'quota_type': 'tg_accounts',
                        'quota': quota_result,
                        'upgrade_suggestion': upgrade_msg,
                        'detail': {
                            'limit': limit,
                            'used': used,
                            'remaining': 0
                        }
                    })
                    return {"success": False, "error": detail_msg, "code": "QUOTA_EXCEEDED", 
                            "detail": {"limit": limit, "used": used}}
                
                quota_reserved = True  # 預留成功，後續需要 commit 或 rollback
                
            except Exception as e:
                print(f"[Backend] Atomic quota check error (allowing): {e}", file=sys.stderr)
        
        # Clean phone number - remove spaces, dashes, and parentheses
        if 'phone' in payload:
            payload['phone'] = re_module.sub(r'[\s\-\(\)]', '', payload['phone'].strip())
        
        print(f"[Backend] Handling add-account command for phone: {payload.get('phone', 'unknown')}", file=sys.stderr)
        
        # 當 usePlatformApi 為 true 時，先從 API 池或後備憑據填充 apiId/apiHash
        if payload.get('usePlatformApi'):
            try:
                from core.api_pool_integration import process_login_payload
                process_login_payload(payload)
                if payload.get('_api_error'):
                    err = payload['_api_error']
                    self.send_log(err, "error")
                    self.send_event("account-validation-error", {"errors": [err], "account_data": payload})
                    # 🔧 P4-3: 回滾配額預留
                    if quota_reserved and owner_user_id:
                        try:
                            quota_service.atomic_commit_or_rollback(owner_user_id, 'tg_accounts', 1, commit=False)
                        except: pass
                    return {"success": False, "error": err}
            except Exception as e:
                print(f"[Backend] process_login_payload error: {e}", file=sys.stderr)
        
        # Validate account data
        is_valid, errors = validate_account(payload)
        if not is_valid:
            error_message = "验证失败: " + "; ".join(errors)
            print(f"[Backend] Validation failed: {errors}", file=sys.stderr)
            self.send_log(error_message, "error")
            self.send_event("account-validation-error", {
                "errors": errors,
                "account_data": payload
            })
            handle_error(
                AppError(ErrorType.VALIDATION_ERROR, error_message, {"errors": errors}),
                {"command": "add-account", "payload": payload}
            )
            # 🔧 P4-3: 驗證失敗，回滾配額預留
            if quota_reserved and owner_user_id:
                try:
                    quota_service.atomic_commit_or_rollback(owner_user_id, 'tg_accounts', 1, commit=False)
                except: pass
            # 🆕 返回錯誤結果（HTTP API 模式需要）
            return {
                "success": False,
                "error": error_message,
                "errors": errors
            }
        
        print(f"[Backend] Validation passed, checking for existing account/session...", file=sys.stderr)
        
        phone = payload.get('phone', '')
        
        # Check if account already exists in database
        existing_account = await db.get_account_by_phone(phone)
        _logger.info(f"[add-account] phone={phone}, existing_account={'YES id=' + str(existing_account.get('id')) + ' status=' + existing_account.get('status', '?') if existing_account else 'NO'}")
        if existing_account:
            # 🔧 P4-3: 帳號已存在，不需要消耗新配額，回滾預留
            if quota_reserved and owner_user_id:
                try:
                    quota_service.atomic_commit_or_rollback(owner_user_id, 'tg_accounts', 1, commit=False)
                    quota_reserved = False
                    print(f"[Backend] Quota reservation rolled back (account already exists)", file=sys.stderr)
                except: pass
            
            # 🔧 多租戶：該手機號已被其他用戶添加時，不允許覆蓋或誤操作
            existing_owner = existing_account.get('owner_user_id') or existing_account.get('ownerUserId') or ''
            if not is_electron and owner_user_id and existing_owner and existing_owner not in ('', 'local_user'):
                if existing_owner != owner_user_id:
                    error_msg = "该手机号已被其他用户添加，无法重复添加。"
                    self.send_log(error_msg, "error")
                    self.send_event("account-validation-error", {
                        "errors": [error_msg],
                        "account_data": payload,
                        "error_type": "phone_taken_by_other_user"
                    })
                    return {
                        "success": False,
                        "error": error_msg,
                        "code": "PHONE_TAKEN_BY_OTHER_USER",
                        "phone": phone
                    }
            
            existing_status = existing_account.get('status', 'Offline')
            existing_id = existing_account.get('id')
            
            # CRITICAL: If account is already Online, just return success - don't trigger any login
            if existing_status == "Online":
                print(f"[Backend] Account {phone} already exists and is Online, skipping", file=sys.stderr)
                # Send duplicate error to inform user
                error_msg = f"账户已存在: 电话号码 {phone} 已经在系统中（状态: 在线）。无需重复添加。"
                self.send_log(error_msg, "info")
                self.send_event("account-validation-error", {
                    "errors": [error_msg],
                    "account_data": payload,
                    "error_type": "duplicate"
                })
                return {
                    "success": False,
                    "error": error_msg,
                    "code": "DUPLICATE_ACCOUNT",
                    "phone": phone
                }
            
            # OPTIMIZATION: If account exists with "error" or "Offline" status, 
            # automatically trigger login instead of showing "account already exists" error
            if existing_status in ["error", "Offline"]:
                print(f"[Backend] Account exists with status '{existing_status}', automatically triggering login...", file=sys.stderr)
                
                # Reset status to Offline and clear login state
                await db.update_account(existing_id, {"status": "Offline"})
                # Clear any login callbacks for this phone
                self.telegram_manager.login_callbacks.pop(phone, None)
                
                # Update account data if provided (API ID, API Hash, etc.)
                update_data = {}
                old_api_id = existing_account.get('apiId')
                new_api_id = payload.get('apiId')
                
                if new_api_id:
                    update_data['apiId'] = new_api_id
                if payload.get('apiHash'):
                    update_data['apiHash'] = payload['apiHash']
                if payload.get('proxy'):
                    update_data['proxy'] = payload['proxy']
                if payload.get('group'):
                    update_data['group'] = payload['group']
                if payload.get('twoFactorPassword'):
                    update_data['twoFactorPassword'] = payload['twoFactorPassword']
                if payload.get('role'):
                    update_data['role'] = payload['role']
                
                if update_data:
                    await db.update_account(existing_id, update_data)
                    print(f"[Backend] Updated account data for {phone}", file=sys.stderr)
                
                # 更新 API 憑據使用計數（當 API ID 改變時）
                if new_api_id and new_api_id != old_api_id:
                    try:
                        from api_credential_pool import get_api_credential_pool
                        data_dir = str(Path(config.DATA_PATH))
                        pool = get_api_credential_pool(data_dir)
                        
                        # 釋放舊的 API 憑據
                        if old_api_id:
                            pool.release_credential(old_api_id)
                            print(f"[Backend] Released old API credential {old_api_id}", file=sys.stderr)
                        
                        # 分配新的 API 憑據
                        pool.allocate_credential(new_api_id)
                        print(f"[Backend] Allocated new API credential {new_api_id}", file=sys.stderr)
                        
                        # 發送更新的憑據信息
                        credentials = pool.list_credentials()
                        self.send_event("api-credentials-updated", {"credentials": credentials})
                    except Exception as e:
                        print(f"[Backend] Error updating API credential usage: {e}", file=sys.stderr)
                
                # Send updated accounts list (🔧 多租戶安全)
                await self._send_accounts_updated(owner_user_id)
                
                # Automatically trigger login
                print(f"[Backend] Auto-triggering login for existing account {phone} (ID: {existing_id})", file=sys.stderr)
                self.send_log(f"账户 {phone} 已存在，自动触发登录...", "info")
                
                # Trigger login asynchronously (don't block the response)
                asyncio.create_task(self.handle_login_account({
                    "accountId": existing_id,
                    "phoneCode": None,
                    "phoneCodeHash": None
                }))
                
                # Return success with a message indicating auto-login was triggered
                return {
                    "success": True,
                    "account_id": existing_id,
                    "phone": phone,
                    "message": f"账户 {phone} 已存在，自动触发登录..."
                }
            
            # Check if account has stuck status (Logging in... or Waiting Code)
            if existing_status in ['Logging in...', 'Waiting Code', 'Waiting 2FA']:
                # CRITICAL: If account is in login process (especially Waiting Code), 
                # DO NOT update account data or send events that might trigger re-login
                # Just return success silently to prevent status loop
                print(f"[Backend] Account {phone} is in login process (status: {existing_status}), skipping update to prevent status loop", file=sys.stderr)
                
                # Only update account data if there are actual changes AND status is not Waiting Code
                # If status is Waiting Code, user is waiting for verification code - do NOT update
                if existing_status != 'Waiting Code':
                    # For Logging in... or Waiting 2FA, allow minimal updates
                    update_data = {}
                    if payload.get('apiId'):
                        update_data['apiId'] = payload.get('apiId')
                    if payload.get('apiHash'):
                        update_data['apiHash'] = payload.get('apiHash')
                    
                    if update_data and existing_id:
                        await db.update_account(existing_id, update_data)
                        print(f"[Backend] Updated account data for {phone}", file=sys.stderr)
                        # Only send accounts-updated if we actually updated something (🔧 多租戶安全)
                        await self._send_accounts_updated(owner_user_id)
                
                # Return success - account exists and is in login process
                # DO NOT send accounts-updated event if status is Waiting Code to prevent loop
                return {
                    "success": True,
                    "account_id": existing_id,
                    "phone": phone,
                    "message": f"账户 {phone} 正在登录中（状态: {existing_status}）"
                }
            
            # If account exists with other statuses (Online, Offline, error), show error
            error_msg = f"账户已存在: 电话号码 {phone} 已经在系统中（状态: {existing_status}）。如需更新账户信息，请使用更新功能。"
            print(f"[Backend] Account already exists in database: {phone}, status: {existing_status}", file=sys.stderr)
            self.send_log(error_msg, "error")
            self.send_event("account-validation-error", {
                "errors": [error_msg],
                "account_data": payload,
                "error_type": "duplicate"
            })
            return {
                "success": False,
                "error": error_msg,
                "code": "DUPLICATE_ACCOUNT",
                "phone": phone
            }
        
        # Check if session file exists (but account not in database)
        from config import SESSIONS_DIR
        safe_phone = phone.replace("+", "").replace("-", "").replace(" ", "")
        session_file = SESSIONS_DIR / f"{safe_phone}.session"
        session_journal = SESSIONS_DIR / f"{safe_phone}.session.journal"
        
        if session_file.exists() or session_journal.exists():
            # Session file exists but account not in database
            # This could be an orphaned session file
            print(f"[Backend] Warning: Session file exists for {phone} but account not in database", file=sys.stderr)
            
            # CRITICAL: Ensure any client using this session is disconnected first
            try:
                await self.telegram_manager.remove_client(phone, wait_for_disconnect=True)
                # Force garbage collection to release file handles
                gc.collect()
                await asyncio.sleep(0.3)  # Give OS time to release file handles
            except Exception as e:
                print(f"[Backend] Warning: Could not remove client for {phone} (may not exist): {e}", file=sys.stderr)
            
            # Now try to delete the orphaned session files
            print(f"[Backend] Deleting orphaned session file: {session_file}", file=sys.stderr)
            session_deleted = await self.safe_delete_session_file(session_file)
            
            if session_journal.exists():
                journal_deleted = await self.safe_delete_session_file(session_journal)
            else:
                journal_deleted = True
            
            if not session_deleted or not journal_deleted:
                # If we can't delete the session file, we should not add the account
                # This prevents database inconsistency
                error_msg = f"无法删除已存在的会话文件。请确保没有其他程序正在使用该文件，然后重试。"
                print(f"[Backend] Cannot delete orphaned session file, aborting account addition", file=sys.stderr)
                self.send_log(error_msg, "error")
                self.send_event("account-validation-error", {
                    "errors": [error_msg],
                    "account_data": payload,
                    "error_type": "file_locked"
                })
                # 🔧 P4-3: 回滾配額預留
                if quota_reserved and owner_user_id:
                    try:
                        quota_service.atomic_commit_or_rollback(owner_user_id, 'tg_accounts', 1, commit=False)
                    except: pass
                return
            
            print(f"[Backend] Orphaned session file deleted successfully", file=sys.stderr)
        
        print(f"[Backend] Adding account to database...", file=sys.stderr)
        
        # Generate device fingerprint for anti-ban (防封)
        DeviceFingerprintGenerator = get_DeviceFingerprintGenerator()
        device_config = DeviceFingerprintGenerator.generate_for_phone(phone)
        print(f"[Backend] Generated device fingerprint for {phone}: {device_config.get('device_model')} ({device_config.get('platform')})", file=sys.stderr)
        
        # Add device fingerprint to payload
        payload['deviceModel'] = device_config.get('device_model')
        payload['systemVersion'] = device_config.get('system_version')
        payload['appVersion'] = device_config.get('app_version')
        payload['langCode'] = device_config.get('lang_code')
        payload['platform'] = device_config.get('platform')
        payload['deviceId'] = device_config.get('device_id')
        
        # Get proxy country from phone number (if proxy is provided)
        if payload.get('proxy'):
            try:
                PM = get_ProxyManager()
                proxy_country = PM.get_country_from_phone(phone) if PM else None
            except Exception:
                proxy_country = None
            if proxy_country:
                payload['proxyCountry'] = proxy_country
                payload['proxyType'] = 'residential'  # Default to residential proxy
        
        # Ensure status is set to Offline when adding account
        payload['status'] = 'Offline'
        
        account_id = await db.add_account(payload)
        _logger.info(f"[add-account] SUCCESS account_id={account_id}, phone={phone}")
        print(f"[Backend] Account added successfully with ID: {account_id}", file=sys.stderr)
        
        # Double-check: ensure status is Offline (in case of any issues)
        await db.update_account(account_id, {"status": "Offline"})
        print(f"[Backend] Account status set to Offline for {phone}", file=sys.stderr)
        
        # 更新 API 憑據池使用計數
        api_id = payload.get('apiId')
        if api_id:
            try:
                from api_credential_pool import get_api_credential_pool
                data_dir = str(Path(config.DATA_PATH))
                pool = get_api_credential_pool(data_dir)
                if pool.allocate_credential(api_id):
                    print(f"[Backend] API credential {api_id} usage count incremented", file=sys.stderr)
                    # 發送更新的憑據信息
                    credentials = pool.list_credentials()
                    self.send_event("api-credentials-updated", {"credentials": credentials})
            except Exception as e:
                print(f"[Backend] Error updating API credential usage: {e}", file=sys.stderr)
        
        # 🔧 同步 API 池分配（平台 API）
        if payload.get('usePlatformApi') and api_id:
            try:
                from admin.api_pool import get_api_pool_manager
                api_pool = get_api_pool_manager()
                api_pool.link_allocation_to_account(phone, str(account_id), api_id=api_id)
            except Exception as e:
                print(f"[Backend] Error linking API allocation: {e}", file=sys.stderr)
        
        await db.add_log(f"Account added: {payload.get('phone')}", "success")
        self.send_log(f"账户添加成功: {payload.get('phone')}", "success")
        
        # Send updated accounts list (🔧 多租戶安全)
        await self._send_accounts_updated(owner_user_id)
        
        # 🔧 P4-3: 帳號新增成功 → 提交配額預留
        if quota_reserved and owner_user_id:
            try:
                from core.quota_service import get_quota_service
                qs = get_quota_service()
                qs.atomic_commit_or_rollback(owner_user_id, 'tg_accounts', 1, commit=True)
                print(f"[Backend] Quota reservation committed for user {owner_user_id}", file=sys.stderr)
            except Exception as e:
                print(f"[Backend] Quota commit error (non-fatal): {e}", file=sys.stderr)
        
        # 🔧 P3-3: 帳號新增後立即失效配額緩存
        try:
            from core.quota_service import get_quota_service
            qs = get_quota_service()
            owner_id = payload.get('owner_user_id') or payload.get('ownerUserId')
            if owner_id:
                qs.invalidate_cache(owner_id)
            else:
                qs.invalidate_cache()  # 無法確定用戶，全量失效
            print(f"[Backend] Quota cache invalidated after add-account for user {owner_id}", file=sys.stderr)
        except Exception as e:
            print(f"[Backend] Quota cache invalidation error: {e}", file=sys.stderr)
        
        # 🆕 返回成功結果（HTTP API 模式需要）
        return {
            "success": True,
            "account_id": account_id,
            "phone": phone,
            "message": f"账户 {phone} 添加成功"
        }
    
    except ValidationError as e:
        import sys
        # 🔧 P4-3: 帳號新增失敗 → 回滾配額預留
        if quota_reserved and owner_user_id:
            try:
                from core.quota_service import get_quota_service
                qs = get_quota_service()
                qs.atomic_commit_or_rollback(owner_user_id, 'tg_accounts', 1, commit=False)
                print(f"[Backend] Quota reservation rolled back for user {owner_user_id}", file=sys.stderr)
            except Exception as qe:
                print(f"[Backend] Quota rollback error: {qe}", file=sys.stderr)
        
        print(f"[Backend] ValidationError: {e.message}", file=sys.stderr)
        self.send_log(f"验证错误: {e.message}", "error")
        self.send_event("account-validation-error", {
            "errors": [e.message],
            "field": e.field
        })
    except ValueError as e:
        # Handle specific errors like duplicate phone number
        import sys
        import logging as _log2
        _log2.getLogger('backend.add_account').error(f"[add-account] ValueError: {e}")
        # 🔧 P4-3: 帳號新增失敗 → 回滾配額預留
        if quota_reserved and owner_user_id:
            try:
                from core.quota_service import get_quota_service
                qs = get_quota_service()
                qs.atomic_commit_or_rollback(owner_user_id, 'tg_accounts', 1, commit=False)
                print(f"[Backend] Quota reservation rolled back for user {owner_user_id}", file=sys.stderr)
            except Exception as qe:
                print(f"[Backend] Quota rollback error: {qe}", file=sys.stderr)
        
        error_msg = str(e)
        print(f"[Backend] ValueError adding account: {error_msg}", file=sys.stderr)
        self.send_log(error_msg, "error")
        self.send_event("account-validation-error", {
            "errors": [error_msg],
            "account_data": payload,
            "error_type": "duplicate" if "已存在" in error_msg else "validation"
        })
    except Exception as e:
        import sys
        # 🔧 P4-3: 帳號新增失敗 → 回滾配額預留
        if quota_reserved and owner_user_id:
            try:
                from core.quota_service import get_quota_service
                qs = get_quota_service()
                qs.atomic_commit_or_rollback(owner_user_id, 'tg_accounts', 1, commit=False)
                print(f"[Backend] Quota reservation rolled back for user {owner_user_id}", file=sys.stderr)
            except Exception as qe:
                print(f"[Backend] Quota rollback error: {qe}", file=sys.stderr)
        
        error_msg = str(e)
        import logging as _log3
        _log3.getLogger('backend.add_account').error(f"[add-account] Exception: {error_msg}")
        print(f"[Backend] Exception adding account: {error_msg}", file=sys.stderr)
        import traceback
        traceback.print_exc(file=sys.stderr)
        
        # Provide user-friendly error message
        if "UNIQUE constraint failed: accounts.phone" in error_msg or "phone" in error_msg.lower():
            friendly_msg = f"账户已存在: 电话号码 {payload.get('phone', '')} 已经在系统中。如需更新账户信息，请使用更新功能。"
        else:
            friendly_msg = f"添加账户失败: {error_msg}"
        
        self.send_log(friendly_msg, "error")
        self.send_event("account-validation-error", {
            "errors": [friendly_msg],
            "account_data": payload,
            "error_type": "duplicate" if "已存在" in friendly_msg else "error"
        })
        handle_error(e, {"command": "add-account", "payload": payload})


async def handle_send_code(self, payload: Dict[str, Any]):
    """
    Handle send-code command - 發送驗證碼
    
    這是獨立的驗證碼發送命令，用於 SaaS 版本
    """
    try:
        import sys
        print(f"[Backend] handle_send_code called with payload: {payload}", file=sys.stderr)
        
        phone = payload.get('phone', '').strip()
        api_id = payload.get('api_id') or payload.get('apiId')
        api_hash = payload.get('api_hash') or payload.get('apiHash')
        proxy = payload.get('proxy')
        two_factor_password = payload.get('twoFactorPassword') or payload.get('two_factor_password')
        
        if not phone:
            self.send_event("send-code-error", {
                "success": False,
                "error": "電話號碼不能為空"
            })
            return
        
        # 如果沒有提供 API ID/Hash，嘗試使用推薦的憑證
        if not api_id or not api_hash:
            try:
                from api_credential_pool import get_api_credential_pool
                data_dir = str(Path(config.DATA_PATH))
                pool = get_api_credential_pool(data_dir)
                recommended = pool.get_recommended_credential()
                if recommended:
                    api_id = api_id or recommended.get('api_id')
                    api_hash = api_hash or recommended.get('api_hash')
                    print(f"[Backend] Using recommended credential: {api_id}", file=sys.stderr)
            except Exception as e:
                print(f"[Backend] Could not get recommended credential: {e}", file=sys.stderr)
        
        if not api_id or not api_hash:
            self.send_event("send-code-error", {
                "success": False,
                "error": "請提供 API ID 和 API Hash，或在 API 憑證池中添加憑證"
            })
            return
        
        # 使用 TelegramManager 發送驗證碼
        print(f"[Backend] Sending verification code to {phone}...", file=sys.stderr)
        
        result = await self.telegram_manager.login_account(
            phone=phone,
            api_id=api_id,
            api_hash=api_hash,
            proxy=proxy,
            two_factor_password=two_factor_password
        )
        
        if result.get('success'):
            # 驗證碼已發送
            self.send_log(result.get('message', f"驗證碼已發送到 {phone}"), "success")
            response = {
                "success": True,
                "phone": phone,
                "status": result.get('status', 'waiting_code'),
                "message": result.get('message'),
                "send_type": result.get('send_type', 'unknown'),
                "requires_code": result.get('requires_code', True),
                "phone_code_hash": result.get('phone_code_hash')
            }
            self.send_event("send-code-result", response)
            return response
        else:
            # 發送失敗
            error_msg = result.get('message', '發送驗證碼失敗')
            self.send_log(error_msg, "error")
            response = {
                "success": False,
                "phone": phone,
                "error": error_msg,
                "status": result.get('status', 'error')
            }
            self.send_event("send-code-error", response)
            return response
            
    except Exception as e:
        import traceback
        print(f"[Backend] Error in handle_send_code: {e}", file=sys.stderr)
        traceback.print_exc(file=sys.stderr)
        self.send_log(f"發送驗證碼失敗: {str(e)}", "error")
        response = {
            "success": False,
            "error": str(e)
        }
        self.send_event("send-code-error", response)
        return response


async def handle_login_account(self, payload: Any):
    """Handle login-account command with Pyrogram"""
    try:
        import sys
        import logging
        _logger = logging.getLogger('backend.login_account')
        _logger.info(f"[login-account] START payload_keys={list(payload.keys()) if isinstance(payload, dict) else type(payload)}, phone={payload.get('phone') if isinstance(payload, dict) else 'N/A'}")
        print(f"[Backend] handle_login_account called with payload: {payload}", file=sys.stderr)
        
        # Payload can be account_id (int) or dict with account_id and login details
        if isinstance(payload, int):
            account_id = payload
            account = await db.get_account(account_id)
            phone_code = None
            phone_code_hash = None
            two_factor_password = None
        else:
            account_id = payload.get('accountId')
            phone_code = payload.get('phoneCode')
            phone_code_hash = payload.get('phoneCodeHash')
            two_factor_password = payload.get('twoFactorPassword')
            
            # Try to get account by ID first, then by phone number
            if account_id:
                account = await db.get_account(account_id)
            else:
                # If no accountId provided, try to find by phone number
                phone_from_payload = payload.get('phone')
                if phone_from_payload:
                    account = await db.get_account_by_phone(phone_from_payload)
                    if account:
                        account_id = account.get('id')
                        print(f"[Backend] Found account by phone {phone_from_payload}, ID: {account_id}", file=sys.stderr)
                else:
                    account = None
        
        if not account:
            error_msg = f"Account {account_id} not found"
            _logger.warning(f"[login-account] ACCOUNT NOT FOUND account_id={account_id}, phone={payload.get('phone') if isinstance(payload, dict) else 'N/A'}")
            print(f"[Backend] {error_msg}", file=sys.stderr)
            self.send_log(error_msg, "error")
            return {
                "success": False,
                "error": error_msg,
                "phone": payload.get('phone', '') if isinstance(payload, dict) else ''
            }
        
        phone = account.get('phone')
        current_status = account.get('status', 'Offline')
        _logger.info(f"[login-account] FOUND account_id={account_id}, phone={phone}, status={current_status}, apiId={account.get('apiId')}, hasApiHash={'yes' if account.get('apiHash') else 'no'}")
        print(f"[Backend] Found account: {phone}, API ID: {account.get('apiId')}, API Hash: {'***' if account.get('apiHash') else 'None'}", file=sys.stderr)
        
        # CRITICAL: If account is already Online and no verification code is being submitted,
        # skip login to prevent database lock and unnecessary operations
        if current_status == 'Online' and not phone_code:
            print(f"[Backend] Account {phone} is already Online, skipping login", file=sys.stderr)
            # Just verify the account is still valid
            try:
                status_result = await self.telegram_manager.check_account_status(phone)
                if status_result.get('online'):
                    print(f"[Backend] Account {phone} verified online", file=sys.stderr)
                    return {
                        "success": True,
                        "status": "Online",
                        "logged_in": True,
                        "phone": phone,
                        "account_id": account_id,
                        "message": f"帳號 {phone} 已在線"
                    }
            except Exception as e:
                print(f"[Backend] Error checking account status: {e}, will proceed with login", file=sys.stderr)
        
        # CRITICAL: If account is in 'Waiting Code' status and we're NOT submitting a code,
        # just return the existing hash (don't resend code)
        if current_status == 'Waiting Code' and not phone_code:
            if phone in self.telegram_manager.login_callbacks:
                existing_hash = self.telegram_manager.login_callbacks[phone].get("phone_code_hash")
                if existing_hash:
                    existing_send_type = self.telegram_manager.login_callbacks[phone].get("send_type", "app")
                    print(f"[Backend] Account {phone} already waiting for code, returning existing hash", file=sys.stderr)
                    self.send_event("login-requires-code", {
                        "accountId": account_id,
                        "phone": phone,
                        "phoneCodeHash": existing_hash,
                        "sendType": existing_send_type,
                        "message": "验证码已发送，请在 Telegram 应用中查看",
                        "canRetrySMS": False
                    })
                    return {
                        "success": True,
                        "requires_code": True,
                        "phone": phone,
                        "phone_code_hash": existing_hash,
                        "send_type": existing_send_type,
                        "message": "验证码已发送，请在 Telegram 应用中查看"
                    }
            print(f"[Backend] Account {phone} status is 'Waiting Code' but no callback found, will resend code", file=sys.stderr)
        
        # Update status to "Logging in..."
        await db.update_account(account_id, {"status": "Logging in..."})
        # 🔧 多租戶安全
        _login_owner = account.get('owner_user_id')
        await self._send_accounts_updated(_login_owner)
        
        self.send_log(f"Login initiated for account {phone}", "info")
        print(f"[Backend] Status updated to 'Logging in...', calling telegram_manager.login_account", file=sys.stderr)
        
        # Login with Pyrogram (使用设备指纹防封)
        print(f"[Backend] Calling telegram_manager.login_account for {phone}", file=sys.stderr)
        
        # Get device fingerprint from account (if exists) or generate new one
        device_model = account.get('deviceModel')
        system_version = account.get('systemVersion')
        app_version = account.get('appVersion')
        lang_code = account.get('langCode')
        platform = account.get('platform')
        
        # If device fingerprint not in account, generate it (for existing accounts)
        if not device_model or not system_version or not app_version:
            DeviceFingerprintGenerator = get_DeviceFingerprintGenerator()
            device_config = DeviceFingerprintGenerator.generate_for_phone(phone, prefer_platform=platform)
            device_model = device_model or device_config.get('device_model')
            system_version = system_version or device_config.get('system_version')
            app_version = app_version or device_config.get('app_version')
            lang_code = lang_code or device_config.get('lang_code')
            platform = platform or device_config.get('platform')
            
            # Update account with device fingerprint
            await db.update_account(account_id, {
                'deviceModel': device_model,
                'systemVersion': system_version,
                'appVersion': app_version,
                'langCode': lang_code,
                'platform': platform,
                'deviceId': device_config.get('device_id')
            })
            print(f"[Backend] Generated and saved device fingerprint for {phone}: {device_model} ({platform})", file=sys.stderr)
        
        _logger.info(f"[login-account] CALLING telegram_manager.login_account phone={phone}, proxy={account.get('proxy')}, apiId={account.get('apiId')}")
        result = await self.telegram_manager.login_account(
            phone=phone,
            api_id=account.get('apiId'),
            api_hash=account.get('apiHash'),
            proxy=account.get('proxy'),
            two_factor_password=two_factor_password or account.get('twoFactorPassword'),
            phone_code=phone_code,
            phone_code_hash=phone_code_hash,
            # Device fingerprint parameters (防封)
            device_model=device_model,
            system_version=system_version,
            app_version=app_version,
            lang_code=lang_code,
            platform=platform
        )
        
        _logger.info(f"[login-account] RESULT success={result.get('success')}, requires_code={result.get('requires_code')}, requires_2fa={result.get('requires_2fa')}, status={result.get('status')}, message={str(result.get('message', ''))[:100]}")
        print(f"[Backend] login_account result: success={result.get('success')}, requires_code={result.get('requires_code')}, requires_2fa={result.get('requires_2fa')}", file=sys.stderr)
        
        if result.get('success'):
            if result.get('requires_code'):
                # Need verification code
                phone_code_hash = result.get('phone_code_hash')
                send_type = result.get('send_type', 'unknown')
                next_type = result.get('next_type')
                message = result.get('message', f"验证码已发送到 {phone}")
                
                print(f"[Backend] Sending login-requires-code event for account {account_id} (phone: {phone}), phone_code_hash: {phone_code_hash[:8] if phone_code_hash else 'None'}...", file=sys.stderr)
                print(f"[Backend] Code send type: {send_type}, next_type: {next_type}, message: {message}", file=sys.stderr)
                
                # Check if we can retry for SMS (if previous was app and enough time has passed)
                can_retry_sms = result.get('canRetrySMS', False) or result.get('can_retry_sms', False)
                wait_seconds = result.get('waitSeconds', None)
                
                event_data = {
                    "accountId": account_id,
                    "phone": phone,
                    "phoneCodeHash": phone_code_hash,
                    "sendType": send_type,  # Include send type
                    "nextType": next_type,  # Include next type
                    "message": message,  # Include message
                    "canRetrySMS": can_retry_sms,  # Include canRetrySMS flag
                    "waitSeconds": wait_seconds  # Include wait seconds if available
                }
                self.send_event("login-requires-code", event_data)
                print(f"[Backend] login-requires-code event sent successfully", file=sys.stderr)
                # State: Requesting Code -> Waiting Code
                await db.update_account(account_id, {"status": "Waiting Code"})
                print(f"[Backend] Account status updated to 'Waiting Code'", file=sys.stderr)
                # 🆕 返回結果（HTTP API 模式需要）
                return {
                    "success": True,
                    "requires_code": True,
                    "phone": phone,
                    "phone_code_hash": phone_code_hash,
                    "send_type": send_type,
                    "message": message
                }
            elif result.get('requires_2fa'):
                # Need 2FA password
                self.send_event("login-requires-2fa", {
                    "accountId": account_id,
                    "phone": phone
                })
                await db.update_account(account_id, {"status": "Waiting 2FA"})
                # 🆕 返回結果（HTTP API 模式需要）
                return {
                    "success": True,
                    "requires_2fa": True,
                    "phone": phone,
                    "message": "需要二步驗證密碼"
                }
            else:
                # Successfully logged in
                await db.update_account(account_id, {"status": result.get('status', 'Online')})
                await db.add_account_event(account_id, "login", None)
                self.send_log(f"Account {phone} logged in successfully", "success")
                
                # 🔧 P1: 獲取用戶資料（跳過 bio 避免 FloodWait）
                try:
                    full_profile = await self.telegram_manager.get_full_user_profile(phone, download_avatar=True, skip_bio=True)
                    if full_profile.get('success'):
                        # 保存用戶信息到數據庫
                        await db.update_account(account_id, {
                            "firstName": full_profile.get('firstName', ''),
                            "lastName": full_profile.get('lastName', ''),
                            "username": full_profile.get('username', ''),
                            "bio": full_profile.get('bio', ''),
                            "avatarPath": full_profile.get('avatarPath', ''),
                            "telegramId": full_profile.get('id', '')
                        })
                        print(f"[Backend] Full profile saved for {phone}: {full_profile.get('firstName')} @{full_profile.get('username')}", file=sys.stderr)
                except Exception as profile_err:
                    print(f"[Backend] Could not get full profile for {phone}: {profile_err}", file=sys.stderr)
                
                # 獲取帳號信息
                account = await db.get_account(account_id)
                account_role = account.get('role', 'Unassigned')
                
                # ========== 智能角色分配 ==========
                # 如果帳號未分配角色，根據現有帳號情況自動分配
                if account_role == 'Unassigned':
                    all_accounts = await db.get_all_accounts()
                    has_listener = any(a.get('role') == 'Listener' for a in all_accounts)
                    has_sender = any(a.get('role') == 'Sender' for a in all_accounts)
                    
                    new_role = None
                    role_message = None
                    
                    if not has_listener:
                        # 優先分配為監控號
                        new_role = 'Listener'
                        role_message = f'已自動將 {phone} 設為「監控號」（用於監控群組消息）'
                    elif not has_sender:
                        # 其次分配為發送號
                        new_role = 'Sender'
                        role_message = f'已自動將 {phone} 設為「發送號」（用於發送消息給潛在客戶）'
                    
                    if new_role:
                        await db.update_account(account_id, {"role": new_role})
                        account_role = new_role
                        self.send_log(f"🎯 {role_message}", "success")
                        print(f"[Backend] Auto-assigned role {new_role} to account {phone}", file=sys.stderr)
                    else:
                        self.send_log(f"💡 帳號 {phone} 已登入，請在帳號管理中分配角色", "info")
                # ========== 智能角色分配結束 ==========

                # 發送登入成功事件給前端（包含完整信息）
                user_info = result.get('user_info', {})
                self.send_event("login-success", {
                    "accountId": account_id,
                    "phone": phone,
                    "status": "Online",
                    "role": account_role,  # 包含角色信息
                    "message": f"帳號 {phone} 登入成功",
                    "userInfo": {
                        "phone": phone,
                        "firstName": account.get('firstName') or user_info.get('first_name', ''),
                        "lastName": account.get('lastName') or user_info.get('last_name', ''),
                        "username": account.get('username') or user_info.get('username', ''),
                        "id": account.get('telegramId') or user_info.get('id', ''),
                        "bio": account.get('bio', ''),
                        "avatarPath": account.get('avatarPath', '')
                    }
                })
                print(f"[Backend] login-success event sent for account {account_id} ({phone}), role={account_role}", file=sys.stderr)
                
                # === P0: 保存 Session Metadata ===
                try:
                    await self._save_session_metadata(phone, {
                        'phone': phone,
                        'apiId': account.get('apiId'),
                        'apiHash': account.get('apiHash'),
                        'firstName': account.get('firstName') or user_info.get('first_name', ''),
                        'lastName': account.get('lastName') or user_info.get('last_name', ''),
                        'username': account.get('username') or user_info.get('username', ''),
                        'telegramId': str(account.get('telegramId') or user_info.get('id', '')),
                        'role': account_role,
                        'created_at': datetime.now().isoformat()
                    })
                    print(f"[Backend] Session metadata saved for {phone}", file=sys.stderr)
                except Exception as e:
                    print(f"[Backend] Error saving session metadata: {e}", file=sys.stderr)
                
                # 刷新 API 憑據列表（確保綁定帳號數據正確）
                try:
                    await self.handle_get_api_credentials({})
                except Exception as e:
                    print(f"[Backend] Error refreshing API credentials after login: {e}", file=sys.stderr)
                
                # 為所有帳號註冊私信處理器（處理用戶回復）
                try:
                    await self.telegram_manager.register_private_message_handler(
                        phone=phone,
                        account_role=account_role
                    )
                    self.send_log(f"已為帳號 {phone} ({account_role}) 註冊私信處理器", "success")
                except Exception as e:
                        self.send_log(f"註冊私信處理器失敗: {e}", "warning")
                
                # Start Warmup if enabled and not already started (防封)
                warmup_enabled = account.get('warmupEnabled', False)
                warmup_start_date = account.get('warmupStartDate')
                
                if warmup_enabled and not warmup_start_date:
                    # Start Warmup (datetime 已在文件頂部全局導入)
                    _WarmupManager = get_WarmupManager()
                    warmup_info = _WarmupManager.start_warmup(account_id, datetime.now())
                    
                    await db.update_account(account_id, {
                        'warmupStartDate': warmup_info['warmup_start_date'],
                        'warmupStage': warmup_info['warmup_stage'],
                        'warmupDaysCompleted': 0
                    })
                    
                    stage_info = warmup_info['current_stage_info']
                    self.send_log(
                        f"账户 {phone} Warmup 已启动: {stage_info.get('stage_name')} "
                        f"(每日限制: {stage_info.get('daily_limit')} 条)",
                        "info"
                    )
                    print(f"[Backend] Warmup started for {phone}: Stage {stage_info.get('stage')} - {stage_info.get('stage_name')}", file=sys.stderr)
                elif warmup_enabled and warmup_start_date:
                    # Update Warmup progress
                    _WarmupManager = get_WarmupManager()
                    warmup_progress = _WarmupManager.get_warmup_progress(account)
                    if warmup_progress.get('enabled') and warmup_progress.get('stage'):
                        stage_info = warmup_progress['stage']
                        await db.update_account(account_id, {
                            'warmupStage': stage_info.get('stage'),
                            'warmupDaysCompleted': stage_info.get('days_completed', 0)
                        })
                        print(f"[Backend] Warmup progress updated for {phone}: Stage {stage_info.get('stage')} - {stage_info.get('stage_name')}, Days: {stage_info.get('days_completed')}", file=sys.stderr)
                
                # 🔧 關鍵修復：登入成功後發送 accounts-updated 事件更新前端狀態（多租戶安全）
                await self._send_accounts_updated(account.get('owner_user_id'))
                
                # 🆕 返回結果（HTTP API 模式需要）
                return {
                    "success": True,
                    "status": "Online",
                    "phone": phone,
                    "account_id": account_id,
                    "user_info": {
                        "phone": phone,
                        "firstName": account.get('firstName') or user_info.get('first_name', ''),
                        "lastName": account.get('lastName') or user_info.get('last_name', ''),
                        "username": account.get('username') or user_info.get('username', '')
                    }
                }
        else:
            # Login failed
            import sys
            error_status = result.get('status', 'Error')
            error_message = result.get('message', '未知错误')
            flood_wait = result.get('flood_wait')
            
            print(f"[Backend] Login failed for {phone}: status={error_status}, message={error_message}", file=sys.stderr)
            
            # Handle FloodWait
            if flood_wait:
                friendly_msg = f'账户 {phone} 登录失败：请求过于频繁，请等待 {flood_wait} 秒后重试。'
                self.send_event("account-login-error", {
                    "accountId": account_id,
                    "phone": phone,
                    "status": error_status,
                    "message": error_message,
                    "friendlyMessage": friendly_msg,
                    "floodWait": flood_wait
                })
                await db.update_account(account_id, {"status": "Offline"})
                # 🆕 返回結果（HTTP API 模式需要）
                return {
                    "success": False,
                    "error": friendly_msg,
                    "flood_wait": flood_wait,
                    "phone": phone
                }
            
            await db.update_account(account_id, {"status": error_status})
            
            # Provide user-friendly error message
            if "API ID and API Hash are required" in error_message:
                friendly_msg = f"账户 {phone} 登录失败：API ID 或 API Hash 未填写。请在账户管理中填写正确的 API 凭证。"
            elif "Invalid verification code" in error_message or "PhoneCodeInvalid" in error_message or "PHONE_CODE_INVALID" in error_message.upper():
                friendly_msg = f"账户 {phone} 登录失败：验证码错误。请检查验证码是否正确，然后重新输入。"
                # Keep the login state so user can retry
                # Don't close the dialog, let user try again
            elif "code expired" in error_message.lower() or "PHONE_CODE_EXPIRED" in error_message.upper() or result.get('code_expired'):
                friendly_msg = f'账户 {phone} 登录失败：验证码已过期。请点击"重新发送"获取新的验证码。'
                # Non-recoverable error: State: Logging in... -> Offline (need to restart)
                await db.update_account(account_id, {"status": "Offline"})
                # Clear login callbacks
                self.telegram_manager.login_callbacks.pop(phone, None)
                # Mark as code expired so frontend can handle it
                self.send_event("account-login-error", {
                    "accountId": account_id,
                    "phone": phone,
                    "status": "Offline",
                    "message": error_message,
                    "friendlyMessage": friendly_msg,
                    "codeExpired": True
                })
                # Don't send duplicate error event below
                await self._send_accounts_updated(account.get('owner_user_id'))
                return {
                    "success": False,
                    "error": friendly_msg,
                    "phone": phone,
                    "code_expired": True,
                    "codeExpired": True
                }
            elif "hash mismatch" in error_message.lower() or "hash" in error_message.lower() and "mismatch" in error_message.lower():
                friendly_msg = f'账户 {phone} 登录失败：验证码哈希不匹配。这通常是因为客户端被重新创建。请点击"重新发送"获取新的验证码。'
                # Non-recoverable error: State: Logging in... -> Offline (need to restart)
                await db.update_account(account_id, {"status": "Offline"})
                # Clear login callbacks
                self.telegram_manager.login_callbacks.pop(phone, None)
                # Mark as code expired so frontend can handle it
                self.send_event("account-login-error", {
                    "accountId": account_id,
                    "phone": phone,
                    "status": "Offline",
                    "message": error_message,
                    "friendlyMessage": friendly_msg,
                    "codeExpired": True
                })
                await self._send_accounts_updated(account.get('owner_user_id'))
                return {
                    "success": False,
                    "error": friendly_msg,
                    "phone": phone,
                    "code_expired": True,
                    "codeExpired": True
                }
            elif "Invalid 2FA password" in error_message or "2FA" in error_message and "password" in error_message.lower():
                friendly_msg = f"帳號 {phone} 登入失敗：二步驗證密碼錯誤。請檢查密碼後重試。"
            elif "2FA verification timeout" in error_message or ("2FA" in error_message and "timeout" in error_message.lower()):
                friendly_msg = f"帳號 {phone} 登入失敗：二步驗證超時。請檢查網絡連接後重試。"
            elif "Flood wait" in error_message or "FLOOD_WAIT" in error_message.upper() or result.get('flood_wait'):
                wait_time = result.get('flood_wait', 0)
                friendly_msg = f"账户 {phone} 登录失败：请求过于频繁，请等待 {wait_time} 秒后重试。"
            elif "Invalid phone number" in error_message or "PHONE_NUMBER_INVALID" in error_message.upper():
                friendly_msg = f"账户 {phone} 登录失败：电话号码格式不正确。请确保格式为 +国家代码+号码。"
            elif "超時" in error_message or "timeout" in error_message.lower():
                friendly_msg = f"账户 {phone} 登录失败：连接超时。请检查网络连接或代理设置后重试。"
                # Non-recoverable error: State: Logging in... -> Offline (need to restart)
                await db.update_account(account_id, {"status": "Offline"})
                # Clear login callbacks
                self.telegram_manager.login_callbacks.pop(phone, None)
            elif "Proxy" in error_message or "proxy" in error_message.lower():
                friendly_msg = f"账户 {phone} 登录失败：代理连接错误。请检查代理配置或暂时移除代理。"
            elif "Connection" in error_message or "connection" in error_message.lower():
                friendly_msg = f"账户 {phone} 登录失败：网络连接错误。请检查网络连接或代理设置。"
            elif "Client connection lost" in error_message or "No valid client" in error_message:
                friendly_msg = f'账户 {phone} 登录失败：客户端连接丢失。请点击"重新发送"获取新的验证码。'
                # Non-recoverable error: State: Logging in... -> Offline (need to restart)
                await db.update_account(account_id, {"status": "Offline"})
                # Clear login callbacks
                self.telegram_manager.login_callbacks.pop(phone, None)
                # Mark as code expired so frontend can handle it
                self.send_event("account-login-error", {
                    "accountId": account_id,
                    "phone": phone,
                    "status": "Offline",
                    "message": error_message,
                    "friendlyMessage": friendly_msg,
                    "codeExpired": True
                })
                await self._send_accounts_updated(account.get('owner_user_id'))
                return {
                    "success": False,
                    "error": friendly_msg,
                    "phone": phone,
                    "code_expired": True,
                    "codeExpired": True
                }
            else:
                friendly_msg = f"账户 {phone} 登录失败：{error_message}"
            
            self.send_log(friendly_msg, "error")
            
            # Also send a specific error event for frontend
            self.send_event("account-login-error", {
                "accountId": account_id,
                "phone": phone,
                "status": error_status,
                "message": error_message,
                "friendlyMessage": friendly_msg
            })
            
            # 🆕 返回錯誤結果（HTTP API 模式需要）
            return {
                "success": False,
                "error": friendly_msg,
                "phone": phone,
                "status": error_status
            }
        
        # Update accounts list
        await self._send_accounts_updated()
    
    except Exception as e:
        import sys
        import traceback
        error_msg = f"Error logging in account: {str(e)}"
        print(f"[Backend] {error_msg}", file=sys.stderr)
        traceback.print_exc(file=sys.stderr)
        self.send_log(error_msg, "error")
        return {
            "success": False,
            "error": f"登录失败：{str(e)}",
            "phone": payload.get('phone', '') if isinstance(payload, dict) else ''
        }


# ===================== End Credential Scraper Handlers =====================

async def handle_check_account_status(self, payload: int):
    """Handle check-account-status command with Pyrogram"""
    try:
        account_id = payload
        account = await db.get_account(account_id)
        
        if not account:
            self.send_log(f"账户 ID {account_id} 不存在。无法检查状态。", "error")
            return
        
        phone = account.get('phone')
        
        # Check status with Pyrogram
        status_result = await self.telegram_manager.check_account_status(phone)
        
        # Update database
        await db.update_account(account_id, {"status": status_result.get('status', 'Offline')})
        
        # Send status update event
        status_info = {
            "accountId": account_id,
            "status": status_result.get('status', 'Offline'),
            "online": status_result.get('online', False),
            "message": status_result.get('message', ''),
            "user": status_result.get('user')
        }
        
        self.send_event("account-status-updated", status_info)
        
        # Update accounts list
        await self._send_accounts_updated()
    
    except Exception as e:
        self.send_log(f"Error checking account status: {str(e)}", "error")


async def handle_update_account_data(self, payload: Dict[str, Any]):
    """Handle update-account-data command"""
    try:
        account_id = payload.get('id')
        updates = payload.get('updates', {})
        await db.update_account(account_id, updates)
        
        await self._send_accounts_updated()
        await db.add_log(f"Account {account_id} updated", "success")
    
    except Exception as e:
        self.send_log(f"Error updating account: {str(e)}", "error")


async def handle_update_account(self, payload: Dict[str, Any]):
    """Handle update-account command - 完整帳號編輯"""
    try:
        import sys
        account_id = payload.get('id')
        phone = payload.get('phone')
        
        if not account_id:
            self.send_event("update-account-result", {"success": False, "error": "缺少帳號 ID"})
            return

        # 構建更新數據
        update_data = {}
        
        # 基本設置
        if 'nickname' in payload:
            update_data['nickname'] = payload['nickname']
        if 'notes' in payload:
            update_data['notes'] = payload['notes']
        if 'dailySendLimit' in payload:
            update_data['dailySendLimit'] = payload['dailySendLimit']
        if 'group' in payload:
            update_data['group'] = payload['group']
        if 'enableWarmup' in payload:
            update_data['enableWarmup'] = 1 if payload['enableWarmup'] else 0

        # API 凭证（数据库字段名是 apiId 和 apiHash）
        if 'apiId' in payload and payload['apiId']:
            update_data['apiId'] = payload['apiId']
        if 'apiHash' in payload and payload['apiHash']:
            update_data['apiHash'] = payload['apiHash']

        # 代理設置
        if 'proxy' in payload:
            update_data['proxy'] = payload['proxy']
        if 'proxyType' in payload:
            update_data['proxyType'] = payload['proxyType']
        if 'proxyHost' in payload:
            update_data['proxyHost'] = payload['proxyHost']
        if 'proxyPort' in payload:
            update_data['proxyPort'] = payload['proxyPort']
        if 'proxyUsername' in payload:
            update_data['proxyUsername'] = payload['proxyUsername']
        if 'proxyPassword' in payload:
            update_data['proxyPassword'] = payload['proxyPassword']
        if 'proxyCountry' in payload:
            update_data['proxyCountry'] = payload['proxyCountry']
        if 'proxyRotationEnabled' in payload:
            update_data['proxyRotationEnabled'] = 1 if payload['proxyRotationEnabled'] else 0

        # 角色設置
        if 'role' in payload:
            update_data['role'] = payload['role']
        if 'aiPersonality' in payload:
            update_data['aiPersonality'] = payload['aiPersonality']

        # AI 設置
        if 'aiEnabled' in payload:
            update_data['aiEnabled'] = 1 if payload['aiEnabled'] else 0
        if 'aiModel' in payload:
            update_data['aiModel'] = payload['aiModel']

        # 執行更新
        await db.update_account(account_id, update_data)
        print(f"[Backend] Account {phone or account_id} updated: {list(update_data.keys())}", file=sys.stderr)

        # 刷新帳號列表
        await self._send_accounts_updated()
        
        # 發送成功響應
        self.send_event("update-account-result", {"success": True})
        await db.add_log(f"帳號 {phone or account_id} 設置已更新", "success")

    except Exception as e:
        import sys
        print(f"[Backend] Error updating account: {e}", file=sys.stderr)
        self.send_event("update-account-result", {"success": False, "error": str(e)})
        self.send_log(f"Error updating account: {str(e)}", "error")


async def handle_test_proxy(self, payload: Dict[str, Any]):
    """Handle test-proxy command - 測試代理連接"""
    import sys
    import asyncio
    import aiohttp
    
    try:
        proxy_type = payload.get('type', 'socks5')
        host = payload.get('host', '')
        port = payload.get('port', 0)
        username = payload.get('username', '')
        password = payload.get('password', '')

        if not host or not port:
            self.send_event("test-proxy-result", {
                "success": False, 
                "error": "請填寫代理地址和端口"
            })
            return

        print(f"[Backend] Testing proxy: {proxy_type}://{host}:{port}", file=sys.stderr)

        # 構建代理 URL
        if username and password:
            proxy_url = f"{proxy_type}://{username}:{password}@{host}:{port}"
        else:
            proxy_url = f"{proxy_type}://{host}:{port}"

        # 測試連接
        start_time = asyncio.get_event_loop().time()
        
        try:
            connector = None
            if proxy_type in ['socks5', 'socks4']:
                # 使用 aiohttp-socks 支持 SOCKS 代理
                try:
                    from aiohttp_socks import ProxyConnector
                    connector = ProxyConnector.from_url(proxy_url)
                except ImportError:
                    # 如果沒有 aiohttp-socks，嘗試基本測試
                    pass
            
            timeout = aiohttp.ClientTimeout(total=10)
            
            if connector:
                async with aiohttp.ClientSession(connector=connector, timeout=timeout) as session:
                    async with session.get('https://api.telegram.org') as response:
                        end_time = asyncio.get_event_loop().time()
                        latency = int((end_time - start_time) * 1000)
                        
                        if response.status == 200:
                            self.send_event("test-proxy-result", {
                                "success": True,
                                "latency": latency,
                                "message": f"連接成功，延遲 {latency}ms"
                            })
                        else:
                            self.send_event("test-proxy-result", {
                                "success": False,
                                "error": f"HTTP 狀態碼: {response.status}"
                            })
            else:
                # HTTP 代理測試
                async with aiohttp.ClientSession(timeout=timeout) as session:
                    async with session.get('https://api.telegram.org', proxy=proxy_url) as response:
                        end_time = asyncio.get_event_loop().time()
                        latency = int((end_time - start_time) * 1000)
                        
                        if response.status == 200:
                            self.send_event("test-proxy-result", {
                                "success": True,
                                "latency": latency,
                                "message": f"連接成功，延遲 {latency}ms"
                            })
                        else:
                            self.send_event("test-proxy-result", {
                                "success": False,
                                "error": f"HTTP 狀態碼: {response.status}"
                            })
                            
        except asyncio.TimeoutError:
            self.send_event("test-proxy-result", {
                "success": False,
                "error": "連接超時（10秒）"
            })
        except Exception as conn_err:
            self.send_event("test-proxy-result", {
                "success": False,
                "error": f"連接失敗: {str(conn_err)}"
            })

    except Exception as e:
        print(f"[Backend] Error testing proxy: {e}", file=sys.stderr)
        self.send_event("test-proxy-result", {
            "success": False,
            "error": str(e)
        })


async def handle_sync_account_info(self, payload: Dict[str, Any]):
    """Handle sync-account-info command - 同步帳號信息（包括頭像）"""
    import sys
    
    try:
        account_id = payload.get('id') or payload.get('accountId')
        phone = payload.get('phone')
        
        if not account_id and not phone:
            self.send_event("sync-account-info-result", {
                "success": False, 
                "error": "缺少账户 ID 或电话号码"
            })
            return

        # 獲取帳號信息
        if account_id:
            account = await db.get_account(account_id)
        else:
            account = await db.get_account_by_phone(phone)
        
        if not account:
            self.send_event("sync-account-info-result", {
                "success": False, 
                "error": "账户不存在"
            })
            return
        
        phone = account.get('phone')
        account_id = account.get('id')
        
        print(f"[Backend] Syncing account info for {phone}...", file=sys.stderr)
        
        # 检查客户端是否已连接，如果未连接则尝试连接
        client = self.telegram_manager.get_client(phone)
        if not client or not client.is_connected:
            print(f"[Backend] Client not connected, attempting to connect for {phone}...", file=sys.stderr)
            
            # 获取 API 凭证（数据库字段名是 apiId 和 apiHash）
            api_id = account.get('apiId') or account.get('api_id')
            api_hash = account.get('apiHash') or account.get('api_hash')
            
            if not api_id or not api_hash:
                self.send_event("sync-account-info-result", {
                    "success": False, 
                    "error": "账户缺少 API 凭证，请在账户设置中填写 API ID 和 API Hash"
                })
                return
            
            # 尝试登录/连接
            try:
                login_result = await self.telegram_manager.login_account(
                    phone=phone,
                    api_id=api_id,
                    api_hash=api_hash,
                    proxy=account.get('proxy')
                )
                
                if not login_result.get('success') and login_result.get('status') != 'Online':
                    self.send_event("sync-account-info-result", {
                        "success": False, 
                        "error": f"无法连接账户: {login_result.get('error', '连接失败')}"
                    })
                    return
                    
                print(f"[Backend] Client connected for {phone}", file=sys.stderr)
            except Exception as conn_error:
                self.send_event("sync-account-info-result", {
                    "success": False, 
                    "error": f"连接账户失败: {str(conn_error)}"
                })
                return
        
        # 獲取完整用戶資料
        full_profile = await self.telegram_manager.get_full_user_profile(phone, download_avatar=True)
        
        if not full_profile.get('success'):
            self.send_event("sync-account-info-result", {
                "success": False,
                "error": full_profile.get('error', '无法获取用户信息')
            })
            return
        
        # 更新數據庫
        await db.update_account(account_id, {
            "firstName": full_profile.get('firstName', ''),
            "lastName": full_profile.get('lastName', ''),
            "username": full_profile.get('username', ''),
            "bio": full_profile.get('bio', ''),
            "avatarPath": full_profile.get('avatarPath', ''),
            "telegramId": str(full_profile.get('id', ''))
        })
        
        print(f"[Backend] Account info synced for {phone}", file=sys.stderr)
        
        # 刷新帳號列表
        await self._send_accounts_updated()
        
        # 發送成功結果
        self.send_event("sync-account-info-result", {
            "success": True,
            "accountId": account_id,
            "phone": phone,
            "profile": full_profile
        })
        
        self.send_log(f"帳號 {phone} 信息已同步", "success")

    except Exception as e:
        print(f"[Backend] Error syncing account info: {e}", file=sys.stderr)
        self.send_event("sync-account-info-result", {
            "success": False,
            "error": str(e)
        })


async def handle_logout_account(self, payload: Dict[str, Any]):
    """Handle logout-account command - 退出账户（断开连接但保留账户）"""
    import sys

    try:
        account_id = payload if isinstance(payload, int) else payload.get('id') or payload.get('accountId')

        if not account_id:
            self.send_event("logout-account-result", {
                "success": False,
                "error": "缺少账户 ID"
            })
            return

        # 获取账户信息
        account = await db.get_account(account_id)
        if not account:
            self.send_event("logout-account-result", {
                "success": False,
                "error": "账户不存在"
            })
            return

        phone = account.get('phone')
        print(f"[Backend] Logging out account {phone}...", file=sys.stderr)

        # 断开客户端连接
        try:
            await self.telegram_manager.disconnect_account(phone, graceful=True)
            print(f"[Backend] Account {phone} disconnected successfully", file=sys.stderr)
        except Exception as e:
            print(f"[Backend] Warning: Error disconnecting account {phone}: {e}", file=sys.stderr)

        # 更新数据库状态为离线
        await db.update_account(account_id, {"status": "Offline"})
        await db.add_account_event(account_id, "logout", None)

        # 刷新账户列表
        await self._send_accounts_updated()

        # 发送成功结果
        self.send_event("logout-account-result", {
            "success": True,
            "accountId": account_id,
            "phone": phone
        })

        self.send_log(f"账户 {phone} 已退出", "success")

    except Exception as e:
        print(f"[Backend] Error logging out account: {e}", file=sys.stderr)
        self.send_event("logout-account-result", {
            "success": False,
            "error": str(e)
        })


async def handle_save_tags(self, payload: Dict[str, Any]):
    """Save tags to settings"""
    try:
        tags = payload.get('tags', [])
        await db.save_setting('account_tags', json.dumps(tags))
        self.send_event("save-tags-result", {"success": True})
    except Exception as e:
        self.send_event("save-tags-result", {"success": False, "error": str(e)})


async def handle_save_groups(self, payload: Dict[str, Any]):
    """Save groups to settings"""
    try:
        groups = payload.get('groups', [])
        await db.save_setting('account_groups', json.dumps(groups))
        self.send_event("save-groups-result", {"success": True})
    except Exception as e:
        self.send_event("save-groups-result", {"success": False, "error": str(e)})


async def handle_get_tags(self, payload: Dict[str, Any]):
    """Get saved tags"""
    try:
        tags_json = await db.get_setting('account_tags')
        tags = json.loads(tags_json) if tags_json else []
        self.send_event("get-tags-result", {"success": True, "tags": tags})
    except Exception as e:
        self.send_event("get-tags-result", {"success": False, "error": str(e), "tags": []})


async def handle_get_groups(self, payload: Dict[str, Any]):
    """Get saved groups"""
    try:
        groups_json = await db.get_setting('account_groups')
        groups = json.loads(groups_json) if groups_json else []
        self.send_event("get-groups-result", {"success": True, "groups": groups})
    except Exception as e:
        self.send_event("get-groups-result", {"success": False, "error": str(e), "groups": []})


async def handle_save_personas(self, payload: Dict[str, Any]):
    """Save custom AI personas to settings"""
    try:
        personas = payload.get('personas', [])
        await db.save_setting('ai_personas', json.dumps(personas))
        self.send_event("save-personas-result", {"success": True})
    except Exception as e:
        self.send_event("save-personas-result", {"success": False, "error": str(e)})


async def handle_get_personas(self, payload: Dict[str, Any]):
    """Get saved custom AI personas"""
    try:
        personas_json = await db.get_setting('ai_personas')
        personas = json.loads(personas_json) if personas_json else []
        self.send_event("get-personas-result", {"success": True, "personas": personas})
    except Exception as e:
        self.send_event("get-personas-result", {"success": False, "error": str(e), "personas": []})


async def handle_get_account_events(self, payload: Dict[str, Any]):
    """P1-5: 獲取帳號登入/斷開事件列表（用於診斷）"""
    try:
        account_id = payload.get('accountId') or payload.get('account_id')
        if not account_id:
            self.send_event("get-account-events-result", {"success": False, "error": "缺少 accountId", "events": []})
            return
        limit = int(payload.get('limit', 30))
        events = await db.get_account_events(account_id, limit=limit)
        self.send_event("get-account-events-result", {"success": True, "accountId": account_id, "events": events})
    except Exception as e:
        self.send_event("get-account-events-result", {"success": False, "error": str(e), "events": []})


async def handle_batch_update_accounts(self, payload: Dict[str, Any]):
    """Handle batch-update-accounts command - 批量更新帳號設置"""
    import sys
    
    try:
        account_ids = payload.get('accountIds', [])
        updates = payload.get('updates', {})
        
        if not account_ids:
            self.send_event("batch-update-accounts-result", {
                "success": False,
                "error": "未選擇帳號"
            })
            return
        
        if not updates:
            self.send_event("batch-update-accounts-result", {
                "success": False,
                "error": "未提供更新數據"
            })
            return
        
        print(f"[Backend] Batch updating {len(account_ids)} accounts with: {list(updates.keys())}", file=sys.stderr)
        
        # 批量更新每個帳號
        success_count = 0
        for account_id in account_ids:
            try:
                await db.update_account(account_id, updates)
                success_count += 1
            except Exception as e:
                print(f"[Backend] Error updating account {account_id}: {e}", file=sys.stderr)
        
        # 刷新帳號列表
        await self._send_accounts_updated()
        
        # 發送成功結果
        self.send_event("batch-update-accounts-result", {
            "success": True,
            "count": success_count,
            "total": len(account_ids)
        })
        
        self.send_log(f"批量更新完成: {success_count}/{len(account_ids)} 個帳號", "success")

    except Exception as e:
        print(f"[Backend] Error in batch update: {e}", file=sys.stderr)
        self.send_event("batch-update-accounts-result", {
            "success": False,
            "error": str(e)
        })


async def handle_bulk_assign_role(self, payload: Dict[str, Any]):
    """Handle bulk-assign-role command"""
    try:
        account_ids = payload.get('accountIds', [])
        role = payload.get('role')
        await db.bulk_update_accounts_role(account_ids, role)
        
        await self._send_accounts_updated()
        await db.add_log(f"Bulk assigned role '{role}' to {len(account_ids)} accounts", "success")
    
    except Exception as e:
        self.send_log(f"Error bulk assigning role: {str(e)}", "error")


async def handle_bulk_assign_group(self, payload: Dict[str, Any]):
    """Handle bulk-assign-group command"""
    try:
        account_ids = payload.get('accountIds', [])
        group = payload.get('group')
        await db.bulk_update_accounts_group(account_ids, group)
        
        await self._send_accounts_updated()
        await db.add_log(f"Bulk assigned group '{group}' to {len(account_ids)} accounts", "success")
    
    except Exception as e:
        self.send_log(f"Error bulk assigning group: {str(e)}", "error")


async def handle_bulk_delete_accounts(self, payload: Dict[str, Any]):
    """Handle bulk-delete-accounts command - completely remove accounts and all related resources"""
    try:
        import sys
        from pathlib import Path
        from config import SESSIONS_DIR
        
        account_ids = payload.get('accountIds', [])
        if not account_ids:
            self.send_log("未选择要删除的账户", "error")
            return
        
        print(f"[Backend] Bulk deleting {len(account_ids)} accounts", file=sys.stderr)
        
        # 🆕 先釋放雙池分配（在刪除數據庫記錄之前）
        for account_id in account_ids:
            try:
                account = await db.get_account(account_id)
                if account:
                    phone = account.get('phone')
                    if phone:
                        # 釋放 SQLite API 對接池
                        try:
                            from admin.api_pool import get_api_pool_manager
                            api_pool = get_api_pool_manager()
                            api_pool.release_api(phone)
                        except Exception as e:
                            print(f"[Backend] Error releasing API pool for {phone}: {e}", file=sys.stderr)
                        
                        # 釋放代理池
                        try:
                            from admin.proxy_pool import get_proxy_pool
                            proxy_pool = get_proxy_pool()
                            proxy_pool.release_proxy(phone=phone)
                        except Exception as e:
                            print(f"[Backend] Error releasing proxy pool for {phone}: {e}", file=sys.stderr)
            except Exception as e:
                print(f"[Backend] Error releasing pools for account {account_id}: {e}", file=sys.stderr)
        
        # Delete from database (this also cleans up related data)
        deleted_phones = await db.bulk_delete_accounts(account_ids)
        print(f"[Backend] {len(deleted_phones)} accounts deleted from database", file=sys.stderr)
        
        # Remove clients from TelegramClientManager and delete session files
        for phone in deleted_phones:
            if phone:
                # Ensure client is fully disconnected
                try:
                    await self.ensure_client_disconnected(phone)
                    print(f"[Backend] Client disconnected and removed for {phone}", file=sys.stderr)
                except Exception as e:
                    print(f"[Backend] Error removing client for {phone}: {e}", file=sys.stderr)
                
                # Delete session files with retry mechanism
                try:
                    safe_phone = phone.replace("+", "").replace("-", "").replace(" ", "")
                    session_file = SESSIONS_DIR / f"{safe_phone}.session"
                    session_journal = SESSIONS_DIR / f"{safe_phone}.session.journal"
                    
                    if session_file.exists():
                        deleted = await self.safe_delete_session_file(session_file)
                        if deleted:
                            print(f"[Backend] Deleted session file: {session_file}", file=sys.stderr)
                        else:
                            print(f"[Backend] WARNING: Failed to delete session file after retries: {session_file}", file=sys.stderr)
                    
                    if session_journal.exists():
                        deleted = await self.safe_delete_session_file(session_journal)
                        if deleted:
                            print(f"[Backend] Deleted session journal: {session_journal}", file=sys.stderr)
                        else:
                            print(f"[Backend] WARNING: Failed to delete session journal after retries: {session_journal}", file=sys.stderr)
                except Exception as e:
                    print(f"[Backend] Error deleting session files for {phone}: {e}", file=sys.stderr)
        
        # Update accounts list and send event
        await self._send_accounts_updated()
        
        await db.add_log(f"批量删除了 {len(deleted_phones)} 个账户", "success")
        self.send_log(f"已删除 {len(deleted_phones)} 个账户", "success")
        print(f"[Backend] Bulk delete completed: {len(deleted_phones)} accounts removed", file=sys.stderr)
        
        # 🔧 P3-3: 批量刪除後失效配額緩存（全量失效，因涉及多帳號）
        try:
            from core.quota_service import get_quota_service
            get_quota_service().invalidate_cache()
            print(f"[Backend] Quota cache invalidated after bulk-delete", file=sys.stderr)
        except Exception as qe:
            print(f"[Backend] Quota cache invalidation error: {qe}", file=sys.stderr)
        
        await self._send_accounts_updated()
        await db.add_log(f"Deleted {len(account_ids)} accounts", "success")
    
    except Exception as e:
        self.send_log(f"Error deleting accounts: {str(e)}", "error")


async def handle_remove_account(self, payload: Dict[str, Any]):
    """Handle remove-account command - completely remove account and all related resources"""
    try:
        import sys
        from pathlib import Path
        from config import SESSIONS_DIR
        
        account_id = payload.get('id')
        if not account_id:
            self.send_log("账户ID不能为空", "error")
            return
        
        # Get account info before deleting (for cleanup)
        account = await db.get_account(account_id)
        if not account:
            self.send_log(f"账户 {account_id} 不存在", "error")
            return
        
        phone = account.get('phone')
        api_id = account.get('apiId')
        print(f"[Backend] Removing account {account_id} (phone: {phone})", file=sys.stderr)
        
        # 0. 釋放 API 憑據使用計數（舊池）
        if api_id:
            try:
                from api_credential_pool import get_api_credential_pool
                data_dir = str(Path(config.DATA_PATH))
                pool = get_api_credential_pool(data_dir)
                if pool.release_credential(api_id):
                    print(f"[Backend] API credential {api_id} usage count decremented", file=sys.stderr)
                    # 發送更新的憑據信息
                    credentials = pool.list_credentials()
                    self.send_event("api-credentials-updated", {"credentials": credentials})
            except Exception as e:
                print(f"[Backend] Error releasing API credential: {e}", file=sys.stderr)
        
        # 0.1 🆕 釋放 SQLite API 對接池分配
        if phone:
            try:
                from admin.api_pool import get_api_pool_manager
                api_pool = get_api_pool_manager()
                success, msg = api_pool.release_api(phone)
                if success:
                    print(f"[Backend] SQLite API pool released for {phone}", file=sys.stderr)
            except Exception as e:
                print(f"[Backend] Error releasing SQLite API pool: {e}", file=sys.stderr)
        
        # 0.2 🆕 釋放代理池分配
        if phone:
            try:
                from admin.proxy_pool import get_proxy_pool
                proxy_pool = get_proxy_pool()
                success = proxy_pool.release_proxy(phone=phone)
                if success:
                    print(f"[Backend] Proxy pool released for {phone}", file=sys.stderr)
            except Exception as e:
                print(f"[Backend] Error releasing proxy pool: {e}", file=sys.stderr)
        
        # 1. Delete from database (this also cleans up related data)
        deleted_phone = await db.remove_account(account_id)
        if not deleted_phone:
            self.send_log(f"删除账户 {account_id} 失败", "error")
            return
        
        print(f"[Backend] Account {account_id} deleted from database", file=sys.stderr)
        
        # 2. Remove client from TelegramClientManager (this will disconnect it)
        if phone:
            try:
                await self.telegram_manager.remove_client(phone, wait_for_disconnect=True)
                # Force garbage collection to release file handles
                gc.collect()
                await asyncio.sleep(0.3)  # Give OS time to release file handles
                print(f"[Backend] Client disconnected and removed for {phone}", file=sys.stderr)
            except Exception as e:
                print(f"[Backend] Error removing client from TelegramClientManager: {e}", file=sys.stderr)
                # Continue with file deletion attempt anyway
        
        # 3. Delete session files (with retry mechanism)
        if phone:
            try:
                # Sanitize phone number for filename
                safe_phone = phone.replace("+", "").replace("-", "").replace(" ", "")
                session_file = SESSIONS_DIR / f"{safe_phone}.session"
                session_journal = SESSIONS_DIR / f"{safe_phone}.session.journal"
                
                # Delete session file with retry
                if session_file.exists():
                    deleted = await self.safe_delete_session_file(session_file)
                    if deleted:
                        print(f"[Backend] Deleted session file: {session_file}", file=sys.stderr)
                    else:
                        print(f"[Backend] WARNING: Failed to delete session file after retries: {session_file}", file=sys.stderr)
                
                # Delete session journal file if exists
                if session_journal.exists():
                    deleted = await self.safe_delete_session_file(session_journal)
                    if deleted:
                        print(f"[Backend] Deleted session journal file: {session_journal}", file=sys.stderr)
                    else:
                        print(f"[Backend] WARNING: Failed to delete session journal file after retries: {session_journal}", file=sys.stderr)
                
            except Exception as e:
                print(f"[Backend] Error deleting session files for {phone}: {e}", file=sys.stderr)
                # Don't fail the whole operation if session file deletion fails
                # The account is already deleted from database
        
        # 4. Update accounts list and send event
        await self._send_accounts_updated()
        
        await db.add_log(f"账户 {phone} (ID: {account_id}) 已完全删除", "success")
        self.send_log(f"账户 {phone} 已完全删除", "success")
        print(f"[Backend] Account {account_id} ({phone}) completely removed", file=sys.stderr)
        
        # 🔧 P3-3: 帳號刪除後立即失效配額緩存
        try:
            from core.quota_service import get_quota_service
            qs = get_quota_service()
            # 嘗試從帳號信息獲取 owner_user_id（account 在刪除前已獲取）
            owner_id = account.get('owner_user_id') if account else None
            if owner_id:
                qs.invalidate_cache(owner_id)
            else:
                qs.invalidate_cache()
            print(f"[Backend] Quota cache invalidated after remove-account", file=sys.stderr)
        except Exception as qe:
            print(f"[Backend] Quota cache invalidation error: {qe}", file=sys.stderr)
    
    except Exception as e:
        import sys
        import traceback
        error_msg = str(e)
        print(f"[Backend] Error removing account: {error_msg}", file=sys.stderr)
        traceback.print_exc(file=sys.stderr)
        self.send_log(f"删除账户失败: {error_msg}", "error")


# ==================== Monitoring Management Handlers ====================

async def handle_get_accounts(self, payload: Dict[str, Any] = None):
    """獲取所有帳號列表（含每個帳號綁定的代理/IP 顯示用）。支持 payload.owner_user_id 多租戶過濾。"""
    try:
        owner_user_id = None
        if payload:
            owner_user_id = payload.get('owner_user_id') or payload.get('ownerUserId')
        accounts = await db.get_all_accounts(owner_user_id=owner_user_id)
        # 為每個帳號附加當前綁定的代理顯示（host:port），便於在 UI 查看 IP
        try:
            from admin.proxy_pool import get_proxy_pool
            pool = get_proxy_pool()
            for a in accounts:
                phone = a.get('phone')
                if not phone:
                    a['proxyDisplay'] = None
                    continue
                px = pool.get_proxy_for_account(phone=phone)
                a['proxyDisplay'] = f"{px.host}:{px.port}" if px else None
        except Exception as _e:
            for a in accounts:
                a['proxyDisplay'] = a.get('proxyDisplay', None)
        # 🔧 多租戶安全：通過 _send_accounts_updated 發送，帶租戶過濾
        await self._send_accounts_updated()
        # 同時返回數據給 HTTP 響應
        return {'success': True, 'accounts': accounts}
    except Exception as e:
        self.send_log(f"❌ 獲取帳號列表失敗: {e}", "error")
        self.send_event("accounts-updated", [])
        return {'success': False, 'error': str(e), 'accounts': []}

