"""
Extracted handler implementations: qr_login
Auto-generated by refactor_main.py
"""
import json
import sys
import time
import asyncio
import traceback
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

from service_context import get_service_context

# All handlers receive (self, payload) where self is BackendService instance.
# They are called via: await handler_impl(self, payload)
# Inside, use self.db, self.send_event(), self.telegram_manager, etc.
# This is a transitional pattern - later, replace self.xxx with ctx.xxx


def _release_qr_pool_allocation(temp_key: Optional[str]) -> None:
    """
    🛡️ Stage 3：釋放 QR 登入時從平台 API 池臨時佔用的憑據。

    對「未使用池分配」的情況（temp_key 為 None）是安全的 no-op；
    對「已重新綁定到 sessionId」的情況，傳入 sessionId 一樣可以正確釋放
    （release_api_for_phone 內部按 key 查表，查不到就什麼都不做）。
    """
    if not temp_key:
        return
    try:
        from core.api_pool_integration import release_api_for_phone
        release_api_for_phone(temp_key)
    except Exception as e:
        print(f"[Backend] QR 登入 API 池釋放失敗（不影響流程）: {e}", file=sys.stderr)


# ===================== QR Code Login Handlers =====================

async def handle_qr_login_create(self, payload: Dict[str, Any]):
    """Handle qr-login-create command - Create a new QR login session"""
    try:
        import sys
        print(f"[Backend] handle_qr_login_create called with payload: {payload}", file=sys.stderr)
        
        if not self.qr_auth_manager:
            # 提供更詳細的錯誤信息
            from qr_auth_manager import HAS_TELETHON, HAS_QRCODE
            missing_libs = []
            if not HAS_TELETHON:
                missing_libs.append("telethon")
            if not HAS_QRCODE:
                missing_libs.append("qrcode")
            
            if missing_libs:
                error_msg = f"QR 登入功能未啟用，缺少依賴庫: {', '.join(missing_libs)}。請運行: pip install telethon qrcode[pil]"
            else:
                error_msg = "QR 登入功能初始化失敗，請查看後端日誌了解詳情"
            
            print(f"[Backend] {error_msg} (HAS_TELETHON={HAS_TELETHON}, HAS_QRCODE={HAS_QRCODE})", file=sys.stderr)
            self.send_event("qr-login-error", {"error": error_msg})
            self.send_log(error_msg, "error")
            return
        
        proxy = payload.get("proxy") if isinstance(payload, dict) else None
        device_type = payload.get("deviceType") if isinstance(payload, dict) else None
        two_factor_password = payload.get("twoFactorPassword") if isinstance(payload, dict) else None
        
        # 獲取自定義 API 憑據（防封推薦）
        custom_api_id = payload.get("customApiId") if isinstance(payload, dict) else None
        custom_api_hash = payload.get("customApiHash") if isinstance(payload, dict) else None

        # 🛡️ Stage 3：用戶未提供專屬 API 時，先嘗試向平台 API 池申請
        # （與手機驗證碼登入的 process_login_payload 同源機制）；申請成功則
        # 視同「用戶專屬 API」使用，避免落到公共 Desktop/iOS/Android API。
        # 池為空、分配失敗或開關關閉時，行為與之前完全一致（回退公共 API）。
        _qr_pool_temp_key: Optional[str] = None
        if not (custom_api_id and custom_api_hash):
            try:
                from config import QR_USE_API_POOL
            except Exception:
                QR_USE_API_POOL = False
            if QR_USE_API_POOL:
                try:
                    import uuid
                    from core.api_pool_integration import get_api_for_login
                    _qr_pool_temp_key = f"qr-pending:{uuid.uuid4().hex}"
                    pool_api_id, pool_api_hash, pool_source = get_api_for_login(
                        phone=_qr_pool_temp_key,
                        use_platform_api=True
                    )
                    if pool_source in ("platform", "platform_sqlite") and pool_api_id and pool_api_hash:
                        custom_api_id = pool_api_id
                        custom_api_hash = pool_api_hash
                        print(f"[Backend] QR 登入從平台 API 池分配到專屬憑據 (api_id={pool_api_id}, source={pool_source})", file=sys.stderr)
                        try:
                            from core.api_pool_integration import record_qr_pool_allocation
                            record_qr_pool_allocation()
                        except Exception:
                            pass
                    else:
                        # 池為空/回退：不佔用任何資源，temp_key 置空，走原有公共 API 邏輯
                        _qr_pool_temp_key = None
                except Exception as pool_err:
                    print(f"[Backend] QR 登入 API 池分配失敗（不影響登入，回退公共 API）: {pool_err}", file=sys.stderr)
                    _qr_pool_temp_key = None

        if custom_api_id and custom_api_hash:
            print(f"[Backend] Using CUSTOM API credentials (api_id={custom_api_id}) - Recommended for anti-ban", file=sys.stderr)
        else:
            print(f"[Backend] ⚠️ WARNING: No custom API credentials provided - Using PUBLIC API (HIGH BAN RISK!)", file=sys.stderr)
        
        print(f"[Backend] Calling qr_auth_manager.create_qr_login with proxy={proxy}, device_type={device_type}", file=sys.stderr)
        
        # 添加超時保護（60秒）
        try:
            result = await asyncio.wait_for(
                self.qr_auth_manager.create_qr_login(
                    proxy=proxy,
                    device_type=device_type,
                    two_factor_password=two_factor_password,
                    custom_api_id=custom_api_id,
                    custom_api_hash=custom_api_hash
                ),
                timeout=60.0
            )
        except asyncio.TimeoutError:
            error_msg = "創建 QR 登入超時（60秒），請檢查網絡連接或代理設置"
            print(f"[Backend] {error_msg}", file=sys.stderr)
            _release_qr_pool_allocation(_qr_pool_temp_key)
            self.send_event("qr-login-error", {"error": error_msg})
            self.send_log(error_msg, "error")
            return
        
        print(f"[Backend] create_qr_login result: success={result.get('success')}, error={result.get('error', 'None')}", file=sys.stderr)
        
        if result.get("success"):
            # 🛡️ 將池分配的臨時 key 重新綁定到真正的 sessionId，方便取消/失敗時按 sessionId 釋放
            if _qr_pool_temp_key:
                try:
                    from core.api_pool_integration import bind_phone_to_api, get_api_for_phone
                    real_api_id = get_api_for_phone(_qr_pool_temp_key)
                    session_id = result.get('sessionId')
                    if real_api_id and session_id:
                        bind_phone_to_api(session_id, real_api_id)
                except Exception as bind_err:
                    print(f"[Backend] QR 登入 API 池 key 重綁定失敗（不影響登入）: {bind_err}", file=sys.stderr)
            print(f"[Backend] Sending qr-login-created event with sessionId={result.get('sessionId')}", file=sys.stderr)
            self.send_event("qr-login-created", result)
            self.send_log(f"QR 登入會話已創建，請掃描二維碼", "info")
        else:
            _release_qr_pool_allocation(_qr_pool_temp_key)
            error_msg = result.get("error", "創建 QR 登入失敗")
            print(f"[Backend] QR login failed: {error_msg}", file=sys.stderr)
            self.send_event("qr-login-error", {"error": error_msg})
            self.send_log(f"創建 QR 登入失敗: {error_msg}", "error")
            
    except Exception as e:
        # 🛡️ 任何未預期異常也要釋放已佔用的池資源，避免洩漏
        try:
            _release_qr_pool_allocation(locals().get('_qr_pool_temp_key'))
        except Exception:
            pass
        import sys
        import traceback
        error_msg = f"創建 QR 登入時發生錯誤: {str(e)}"
        print(f"[Backend] Error in handle_qr_login_create: {e}", file=sys.stderr)
        traceback.print_exc(file=sys.stderr)
        self.send_event("qr-login-error", {"error": error_msg})
        self.send_log(error_msg, "error")


async def handle_qr_login_status(self, payload: Dict[str, Any]):
    """Handle qr-login-status command - Get QR login session status"""
    try:
        if not self.qr_auth_manager:
            self.send_event("qr-login-status-result", {
                "success": False,
                "error": "QR 登入功能未啟用"
            })
            return
        
        session_id = payload.get("sessionId") if isinstance(payload, dict) else payload
        result = self.qr_auth_manager.get_session_status(session_id)
        self.send_event("qr-login-status-result", result)
        
    except Exception as e:
        import sys
        print(f"[Backend] Error in handle_qr_login_status: {e}", file=sys.stderr)
        self.send_event("qr-login-status-result", {"success": False, "error": str(e)})


async def handle_qr_login_refresh(self, payload: Dict[str, Any]):
    """Handle qr-login-refresh command - Refresh QR code"""
    try:
        if not self.qr_auth_manager:
            self.send_event("qr-login-error", {"error": "QR 登入功能未啟用"})
            return
        
        session_id = payload.get("sessionId") if isinstance(payload, dict) else payload
        result = await self.qr_auth_manager.refresh_qr_code(session_id)
        
        if result.get("success"):
            self.send_event("qr-login-refreshed", result)
        else:
            self.send_event("qr-login-error", {
                "sessionId": session_id,
                "error": result.get("error", "刷新 QR 碼失敗")
            })
            
    except Exception as e:
        import sys
        print(f"[Backend] Error in handle_qr_login_refresh: {e}", file=sys.stderr)
        self.send_event("qr-login-error", {"error": str(e)})


async def handle_qr_login_submit_2fa(self, payload: Dict[str, Any]):
    """Handle qr-login-submit-2fa command - Submit 2FA password"""
    try:
        if not self.qr_auth_manager:
            self.send_event("qr-login-error", {"error": "QR 登入功能未啟用"})
            return
        
        session_id = payload.get("sessionId")
        password = payload.get("password")
        
        if not session_id or not password:
            self.send_event("qr-login-error", {
                "sessionId": session_id,
                "error": "缺少會話 ID 或密碼"
            })
            return
        
        result = await self.qr_auth_manager.submit_2fa_password(session_id, password)
        
        if result.get("success"):
            self.send_event("qr-login-2fa-success", {
                "sessionId": session_id,
                "message": "二步驗證成功"
            })
        else:
            self.send_event("qr-login-error", {
                "sessionId": session_id,
                "error": result.get("error", "二步驗證失敗")
            })
            
    except Exception as e:
        import sys
        print(f"[Backend] Error in handle_qr_login_submit_2fa: {e}", file=sys.stderr)
        self.send_event("qr-login-error", {"error": str(e)})


async def handle_qr_login_cancel(self, payload: Dict[str, Any]):
    """Handle qr-login-cancel command - Cancel QR login session"""
    try:
        if not self.qr_auth_manager:
            return
        
        session_id = payload.get("sessionId") if isinstance(payload, dict) else payload
        result = await self.qr_auth_manager.cancel_session(session_id)

        # 🛡️ 若此 session 曾從 API 池分配專屬憑據，取消時一併釋放回池
        # （若未使用池分配，release_api_for_phone 查不到 key，是安全的 no-op）
        _release_qr_pool_allocation(session_id)
        
        self.send_event("qr-login-cancelled", {
            "sessionId": session_id,
            "message": "QR 登入已取消"
        })
        
    except Exception as e:
        import sys
        print(f"[Backend] Error in handle_qr_login_cancel: {e}", file=sys.stderr)

