"""
Extracted handler implementations: roles
Auto-generated by refactor_main.py
"""
import json
import sys
import time
import asyncio
import traceback
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

from service_context import get_service_context

from service_locator import get_multi_role_manager
# All handlers receive (self, payload) where self is BackendService instance.
# They are called via: await handler_impl(self, payload)
# Inside, use self.db, self.send_event(), self.telegram_manager, etc.
# This is a transitional pattern - later, replace self.xxx with ctx.xxx


# ==================== Multi-Role Handlers (多角色協作) ====================

async def handle_get_role_templates(self, payload: Dict[str, Any]):
    """獲取角色模板"""
    try:
        role_manager = get_multi_role_manager()
        if not role_manager:
            self.send_event("role-templates", {"success": False, "error": "角色管理器未初始化"})
            return
        
        templates = role_manager.get_role_templates()
        self.send_event("role-templates", {"success": True, "templates": templates})
        
    except Exception as e:
        self.send_event("role-templates", {"success": False, "error": str(e)})


async def handle_assign_role(self, payload: Dict[str, Any]):
    """分配角色"""
    try:
        role_manager = get_multi_role_manager()
        if not role_manager:
            self.send_event("role-assigned", {"success": False, "error": "角色管理器未初始化"})
            return
        
        result = await role_manager.assign_role(
            account_phone=payload.get('accountPhone'),
            role_type=payload.get('roleType'),
            role_name=payload.get('roleName', ''),
            personality=payload.get('personality'),
            speaking_style=payload.get('speakingStyle'),
            emoji_frequency=payload.get('emojiFrequency'),
            response_speed=payload.get('responseSpeed'),
            custom_prompt=payload.get('customPrompt'),
            bio=payload.get('bio')
        )
        
        if result.get('success'):
            self.send_log(f"已分配角色: {payload.get('roleType')}", "success")
        
        self.send_event("role-assigned", result)
        
    except Exception as e:
        self.send_event("role-assigned", {"success": False, "error": str(e)})


async def handle_update_role(self, payload: Dict[str, Any]):
    """更新角色"""
    try:
        role_manager = get_multi_role_manager()
        if not role_manager:
            self.send_event("role-updated", {"success": False, "error": "角色管理器未初始化"})
            return
        
        result = await role_manager.update_role(
            role_id=payload.get('roleId'),
            updates=payload.get('updates', {})
        )
        
        self.send_event("role-updated", result)
        
    except Exception as e:
        self.send_event("role-updated", {"success": False, "error": str(e)})


async def handle_remove_role(self, payload: Dict[str, Any]):
    """移除角色"""
    try:
        role_manager = get_multi_role_manager()
        if not role_manager:
            self.send_event("role-removed", {"success": False, "error": "角色管理器未初始化"})
            return
        
        result = await role_manager.remove_role(payload.get('roleId'))
        
        self.send_event("role-removed", result)
        
    except Exception as e:
        self.send_event("role-removed", {"success": False, "error": str(e)})


async def handle_get_account_roles(self, payload: Dict[str, Any]):
    """獲取帳號角色"""
    try:
        role_manager = get_multi_role_manager()
        if not role_manager:
            self.send_event("account-roles", {"success": False, "error": "角色管理器未初始化"})
            return
        
        roles = await role_manager.get_account_roles(payload.get('accountPhone'))
        self.send_event("account-roles", {
            "success": True,
            "roles": [r.to_dict() for r in roles]
        })
        
    except Exception as e:
        self.send_event("account-roles", {"success": False, "error": str(e)})


async def handle_get_all_roles(self, payload: Dict[str, Any]):
    """獲取所有角色"""
    try:
        role_manager = get_multi_role_manager()
        if not role_manager:
            self.send_event("all-roles", {"success": False, "error": "角色管理器未初始化"})
            return
        
        result = await role_manager.get_all_roles(
            role_type=payload.get('roleType'),
            active_only=payload.get('activeOnly', True)
        )
        
        self.send_event("all-roles", result)
        
    except Exception as e:
        self.send_event("all-roles", {"success": False, "error": str(e)})


async def handle_get_role_stats(self, payload: Dict[str, Any]):
    """獲取角色統計"""
    try:
        role_manager = get_multi_role_manager()
        if not role_manager:
            self.send_event("role-stats", {"success": False, "error": "角色管理器未初始化"})
            return
        
        result = await role_manager.get_role_stats()
        self.send_event("role-stats", result)
        
    except Exception as e:
        self.send_event("role-stats", {"success": False, "error": str(e)})

