"""
Extracted handler implementations: messaging
Auto-generated by refactor_main.py
"""
import json
import sys
import time
import asyncio
import traceback
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

from service_context import get_service_context
from database import db
from config import config

from error_handler import handle_error, AppError, ErrorType
from message_queue import MessagePriority
from service_locator import get_SpintaxGenerator

# All handlers receive (self, payload) where self is BackendService instance.
# They are called via: await handler_impl(self, payload)
# Inside, use self.db, self.send_event(), self.telegram_manager, etc.
# This is a transitional pattern - later, replace self.xxx with ctx.xxx


async def handle_get_queue_status(self, payload: Dict[str, Any]):
    """Handle get-queue-status command"""
    try:
        phone = payload.get('phone')  # Optional, if None returns all
        status = await self.message_queue.get_queue_status(phone)
        self.send_event("queue-status", status)
    
    except Exception as e:
        self.send_log(f"Error getting queue status: {str(e)}", "error")


async def handle_clear_queue(self, payload: Dict[str, Any]):
    """Handle clear-queue command"""
    try:
        phone = payload.get('phone')
        status_str = payload.get('status')  # Optional: 'pending', 'failed', etc.
        
        if not phone:
            self.send_log("Phone number required to clear queue", "error")
            return
        
        # Convert status string to enum if provided
        status = None
        if status_str:
            from message_queue import MessageStatus
            status_map = {
                'pending': MessageStatus.PENDING,
                'processing': MessageStatus.PROCESSING,
                'failed': MessageStatus.FAILED,
                'retrying': MessageStatus.RETRYING
            }
            status = status_map.get(status_str.lower())
        
        await self.message_queue.clear_queue(phone, status)
        await db.add_log(f"Queue cleared for {phone}", "info")
        self.send_log(f"Queue cleared for {phone}", "success")
        
        # Send updated status
        status = await self.message_queue.get_queue_status(phone)
        self.send_event("queue-status", status)
    
    except Exception as e:
        self.send_log(f"Error clearing queue: {str(e)}", "error")


async def handle_pause_queue(self, payload: Dict[str, Any]):
    """Handle pause-queue command"""
    try:
        phone = payload.get('phone')
        if not phone:
            self.send_log("Phone number required to pause queue", "error")
            return
        
        await self.message_queue.pause_queue(phone)
        self.send_log(f"Queue paused for {phone}", "info")
        
        # Send updated queue status
        queue_status = await self.message_queue.get_queue_status(phone)
        queue_status['paused'] = True
        self.send_event("queue-status", queue_status)
    
    except Exception as e:
        self.send_log(f"Error pausing queue: {str(e)}", "error")


async def handle_resume_queue(self, payload: Dict[str, Any]):
    """Handle resume-queue command"""
    try:
        phone = payload.get('phone')
        if not phone:
            self.send_log("Phone number required to resume queue", "error")
            return
        
        await self.message_queue.resume_queue(phone)
        self.send_log(f"Queue resumed for {phone}", "success")
        
        # Send updated queue status
        queue_status = await self.message_queue.get_queue_status(phone)
        queue_status['paused'] = False
        self.send_event("queue-status", queue_status)
    
    except Exception as e:
        self.send_log(f"Error resuming queue: {str(e)}", "error")


async def handle_delete_queue_message(self, payload: Dict[str, Any]):
    """Handle delete-queue-message command"""
    try:
        phone = payload.get('phone')
        message_id = payload.get('messageId')
        
        if not phone or not message_id:
            self.send_log("Phone number and message ID required", "error")
            return
        
        success = await self.message_queue.delete_message(phone, message_id)
        if success:
            self.send_log(f"Message {message_id} deleted from queue", "success")
            # Send updated queue status
            queue_status = await self.message_queue.get_queue_status(phone)
            self.send_event("queue-status", queue_status)
        else:
            self.send_log(f"Message {message_id} not found in queue", "warning")
    
    except Exception as e:
        self.send_log(f"Error deleting queue message: {str(e)}", "error")


async def handle_update_queue_message_priority(self, payload: Dict[str, Any]):
    """Handle update-queue-message-priority command"""
    try:
        phone = payload.get('phone')
        message_id = payload.get('messageId')
        priority_str = payload.get('priority')  # 'HIGH', 'NORMAL', 'LOW'
        
        if not phone or not message_id or not priority_str:
            self.send_log("Phone number, message ID, and priority required", "error")
            return
        
        from message_queue import MessagePriority
        priority_map = {
            'HIGH': MessagePriority.HIGH,
            'NORMAL': MessagePriority.NORMAL,
            'LOW': MessagePriority.LOW
        }
        priority = priority_map.get(priority_str.upper())
        
        if not priority:
            self.send_log(f"Invalid priority: {priority_str}", "error")
            return
        
        success = await self.message_queue.update_message_priority(phone, message_id, priority)
        if success:
            self.send_log(f"Message {message_id} priority updated to {priority_str}", "success")
            # Send updated queue status
            queue_status = await self.message_queue.get_queue_status(phone)
            self.send_event("queue-status", queue_status)
        else:
            self.send_log(f"Message {message_id} not found in queue", "warning")
    
    except Exception as e:
        self.send_log(f"Error updating message priority: {str(e)}", "error")


async def handle_get_queue_messages(self, payload: Dict[str, Any]):
    """Handle get-queue-messages command"""
    try:
        phone = payload.get('phone')  # Optional
        status_str = payload.get('status')  # Optional
        limit = payload.get('limit', 100)
        
        status = None
        if status_str:
            from message_queue import MessageStatus
            status_map = {
                'pending': MessageStatus.PENDING,
                'processing': MessageStatus.PROCESSING,
                'failed': MessageStatus.FAILED,
                'retrying': MessageStatus.RETRYING,
                'completed': MessageStatus.COMPLETED
            }
            status = status_map.get(status_str.lower())
        
        messages = await self.message_queue.get_queue_messages(phone, status, limit)
        self.send_event("queue-messages", {
            "phone": phone,
            "messages": messages,
            "count": len(messages)
        })
    
    except Exception as e:
        self.send_log(f"Error getting queue messages: {str(e)}", "error")


async def handle_send_message(self, payload: Dict[str, Any]):
    """Handle send-message command with message queue"""
    try:
        lead_id = payload.get('leadId')
        account_phone = payload.get('accountPhone')
        user_id = payload.get('userId')
        source_group = payload.get('sourceGroup')  # 源群組（用於獲取用戶信息）
        message_text = payload.get('message')
        attachment = payload.get('attachment')
        priority = payload.get('priority', 'normal')  # high, normal, low
        scheduled_at = payload.get('scheduledAt')  # Optional ISO datetime string
        owner_user_id = payload.get('ownerUserId')  # 用於配額檢查
        
        # 配額檢查
        quota_check = await self.check_quota('daily_messages', 1, owner_user_id)
        if not quota_check.get('allowed', True):
            self.send_quota_exceeded_error('message-sent', 'daily_messages', quota_check.get('result', {}))
            return
        
        # 必須有帳號和用戶ID，消息內容或附件至少一個
        if not account_phone or not user_id:
            self.send_log("Missing required parameters for sending message (accountPhone or userId)", "error")
            return
        
        if not message_text and not attachment:
            self.send_log("Missing message text or attachment", "error")
            return
        
        # 如果沒有文字消息，設置為空字符串
        if not message_text:
            message_text = ""
        
        # 嘗試獲取群組 URL（用於加入群組）
        source_group_url = source_group
        if source_group:
            try:
                source_group_str = str(source_group)
                
                # 如果已經是 URL，直接使用
                if 't.me/' in source_group_str or source_group_str.startswith('@'):
                    source_group_url = source_group_str
                    print(f"[Backend] source_group is already a URL: {source_group_url}", file=sys.stderr)
                else:
                    # source_group 是 Telegram chat_id，需要從 monitoredGroups 查找對應的 URL
                    # monitoredGroups 存儲的是 URL，而不是 chat_id
                    # 我們需要從 lead 數據中獲取 source_group_url
                    if lead_id:
                        lead = await db.get_lead(lead_id)
                        if lead:
                            # 檢查 lead 中是否有存儲群組 URL
                            lead_source = lead.get('source_group') or lead.get('sourceGroup')
                            if lead_source and ('t.me/' in str(lead_source) or str(lead_source).startswith('@')):
                                source_group_url = str(lead_source)
                                print(f"[Backend] Found group URL from lead: {source_group_url}", file=sys.stderr)
                            else:
                                # 如果 lead 中沒有 URL，嘗試從 monitoredGroups 查找
                                # 由於 monitoredGroups 存儲的是 URL，而 source_group 是 chat_id
                                # 我們無法直接匹配，只能使用第一個匹配的 URL
                                monitored_groups = await db.get_all_monitored_groups()
                                if monitored_groups:
                                    # 使用第一個可用的群組 URL 作為備選
                                    source_group_url = monitored_groups[0].get('url')
                                    print(f"[Backend] Using first monitored group URL as fallback: {source_group_url}", file=sys.stderr)
                    
                    if source_group_url == source_group:
                        print(f"[Backend] Could not find URL for chat_id {source_group}, using as-is", file=sys.stderr)
            except Exception as e:
                print(f"[Backend] Error looking up group URL: {e}", file=sys.stderr)
        
        # 獲取用戶名作為備選（如果通過 userId 無法發送）
        # 優先使用 payload 中直接傳遞的 username
        target_username = payload.get('username')
        if target_username:
            print(f"[Backend] Got target username from payload: @{target_username}", file=sys.stderr)
        elif lead_id:
            # 嘗試從數據庫中查詢（使用 user_id 而非 lead_id）
            try:
                lead = await db.get_lead_by_user_id(str(user_id))
                if lead:
                    target_username = lead.get('username')
                    if target_username:
                        print(f"[Backend] Got target username from database: @{target_username}", file=sys.stderr)
            except Exception as e:
                print(f"[Backend] Error getting username from database: {e}", file=sys.stderr)
        
        # Convert priority
        if priority == 'high':
            msg_priority = MessagePriority.HIGH
        elif priority == 'low':
            msg_priority = MessagePriority.LOW
        else:
            msg_priority = MessagePriority.NORMAL
        
        # Parse scheduled time if provided
        scheduled_datetime = None
        if scheduled_at:
            try:
                scheduled_datetime = datetime.fromisoformat(scheduled_at.replace('Z', '+00:00'))
            except:
                pass
        
        # Add message to queue
        message_id = await self.message_queue.add_message(
            phone=account_phone,
            user_id=user_id,
            text=message_text,
            attachment=attachment,
            source_group=source_group_url,  # 使用 URL 而非 ID
            target_username=target_username,  # 用戶名作為備選
            priority=msg_priority,
            scheduled_at=scheduled_datetime,
            callback=self._on_message_sent_callback(lead_id)
        )
        
        await db.add_log(f"Message queued for lead {lead_id} (queue ID: {message_id})", "info")
        self.send_log(f"Message queued for lead {lead_id}", "success")
        
        # Send queued event
        self.send_event("message-queued", {
            "messageId": message_id,
            "leadId": lead_id,
            "accountPhone": account_phone,
            "userId": user_id
        })
    
    except Exception as e:
        self.send_log(f"Error queueing message: {str(e)}", "error")


async def handle_send_group_message(self, payload: Dict[str, Any]):
    """Handle send-group-message command - Send message to a group/chat"""
    import sys
    try:
        resource_id = payload.get('resourceId')
        telegram_id = payload.get('telegramId')
        content = payload.get('content')
        account_phone = payload.get('accountPhone')
        
        print(f"[Backend] send-group-message: resourceId={resource_id}, telegramId={telegram_id}, phone={account_phone}", file=sys.stderr)
        
        if not content:
            self.send_log("消息內容不能為空", "error")
            self.send_event("group-message-sent", {
                "success": False,
                "resourceId": resource_id,
                "error": "消息內容不能為空"
            })
            return
        
        if not account_phone:
            self.send_log("請選擇發送帳號", "error")
            self.send_event("group-message-sent", {
                "success": False,
                "resourceId": resource_id,
                "error": "請選擇發送帳號"
            })
            return
        
        # 獲取群組信息
        chat_id = telegram_id
        if not chat_id and resource_id:
            # 🔧 P2 修復: 優先檢查 resource_id 是否為 Telegram chat ID
            resource_id_str = str(resource_id)
            
            # Telegram chat ID 特徵：純數字或以負號開頭的數字（群組ID通常是負數）
            if resource_id_str.lstrip('-').isdigit():
                # 直接使用為 chat_id
                chat_id = int(resource_id_str)
                print(f"[Backend] 使用 resourceId 作為 chat_id: {chat_id}", file=sys.stderr)
            else:
                # 嘗試從數據庫獲取
                try:
                    from resource_discovery import ResourceDiscoverySystem
                    resource_service = ResourceDiscoverySystem()
                    resource = await resource_service.get_resource_by_telegram_id(resource_id_str)
                    
                    if resource:
                        chat_id = resource.get('telegram_id') or resource.get('username')
                except Exception as res_err:
                    print(f"[Backend] 獲取資源失敗: {res_err}", file=sys.stderr)
        
        if not chat_id:
            self.send_log("無法獲取群組 ID", "error")
            self.send_event("group-message-sent", {
                "success": False,
                "resourceId": resource_id,
                "error": "無法獲取群組 ID"
            })
            return
        
        # 獲取客戶端
        if account_phone not in self.telegram_manager.clients:
            self.send_log(f"帳號 {account_phone} 未連接", "error")
            self.send_event("group-message-sent", {
                "success": False,
                "resourceId": resource_id,
                "error": f"帳號 {account_phone} 未連接"
            })
            return
        
        client = self.telegram_manager.clients[account_phone]
        
        if not client.is_connected:
            await client.connect()
        
        self.send_log(f"📨 正在發送消息到群組...", "info")
        
        # 發送消息
        try:
            # 解析 chat_id
            target_chat = chat_id
            if isinstance(chat_id, str) and chat_id.lstrip('-').isdigit():
                target_chat = int(chat_id)
            
            message = await client.send_message(target_chat, content)
            
            self.send_log(f"✅ 消息已發送到群組", "success")
            self.send_event("group-message-sent", {
                "success": True,
                "resourceId": resource_id,
                "messageId": message.id
            })
            
        except Exception as send_error:
            error_msg = str(send_error)
            print(f"[Backend] Error sending message: {send_error}", file=sys.stderr)
            
            # 檢查是否是權限問題
            if "CHAT_WRITE_FORBIDDEN" in error_msg:
                error_msg = "沒有發送消息的權限（可能是頻道或禁言群組）"
            elif "CHAT_RESTRICTED" in error_msg:
                error_msg = "群組已被限制"
            elif "USER_BANNED" in error_msg:
                error_msg = "帳號已被該群組封禁"
            elif "SLOWMODE_WAIT" in error_msg:
                error_msg = "慢速模式限制，請稍後再試"
            
            self.send_log(f"❌ 發送失敗: {error_msg}", "error")
            self.send_event("group-message-sent", {
                "success": False,
                "resourceId": resource_id,
                "error": error_msg
            })
    
    except Exception as e:
        import traceback
        traceback.print_exc(file=sys.stderr)
        self.send_log(f"❌ 發送群組消息失敗: {str(e)}", "error")
        self.send_event("group-message-sent", {
            "success": False,
            "resourceId": payload.get('resourceId'),
            "error": str(e)
        })


async def handle_get_queue_length_history(self, payload: Dict[str, Any]):
    """Handle get-queue-length-history command"""
    try:
        days = payload.get('days', 7)
        
        history = await db.get_queue_length_history(days)
        self.send_event("queue-length-history", {"history": history, "days": days})
    except Exception as e:
        handle_error(e, {"command": "get-queue-length-history", "payload": payload})
        self.send_log(f"Error getting queue length history: {str(e)}", "error")


async def handle_validate_spintax(self, payload: Dict[str, Any]):
    """驗證 Spintax 語法"""
    try:
        content = payload.get('content', '')
        SpintaxGenerator = get_SpintaxGenerator()
        result = SpintaxGenerator.preview_variants(content, 5)
        result['success'] = result.get('valid', False)
        
        self.send_event("spintax-validated", result)
        
    except Exception as e:
        self.send_event("spintax-validated", {"success": False, "error": str(e)})


async def handle_predict_send_time(self, payload: Dict[str, Any]):
    """預測最佳發送時間"""
    try:
        from send_time_predictor import predict_best_send_time
        
        user_id = payload.get("userId")
        urgency = payload.get("urgency", "normal")
        
        result = await predict_best_send_time(
            user_id=user_id,
            urgency=urgency
        )
        
        self.send_event("send-time-prediction", {
            "success": True,
            **result
        })
    except Exception as e:
        print(f"[Backend] Error predicting send time: {e}", file=sys.stderr)
        self.send_event("send-time-prediction", {
            "success": False,
            "error": str(e)
        })


async def handle_batch_send_start(self, payload: Dict[str, Any]):
    """開始批量發送 - 🔧 修復：作為後台任務運行，立即返回 HTTP 響應"""
    import sys
    import asyncio
    
    targets = payload.get('targets', [])
    if not targets:
        self.send_event("batch-send:complete", {
            "success": 0, "failed": 0,
            "error": "沒有選擇發送目標"
        })
        return {'success': False, 'error': '沒有選擇發送目標'}
    
    print(f"[BatchSend] 收到批量發送請求: {len(targets)} 個目標", file=sys.stderr)
    
    # 🔧 核心修復：啟動後台任務，立即返回 HTTP 響應
    # 這解決了 HTTP 超時導致前端卡住的問題
    self._batch_send_active = True
    self._batch_send_cancelled = False
    
    asyncio.ensure_future(_batch_send_worker(self, payload))
    
    return {'success': True, 'message': f'批量發送已啟動: {len(targets)} 個目標'}


async def _batch_send_worker(self, payload: Dict[str, Any]):
    """🔧 後台批量發送 worker - 獨立於 HTTP 請求運行"""
    import sys
    import random
    
    targets = payload.get('targets', [])
    message_template = payload.get('message', '')
    messages = payload.get('messages', [])
    send_strategy = payload.get('sendStrategy', 'random')
    attachments = payload.get('attachments', [])
    cfg = payload.get('config', {})
    
    min_interval = cfg.get('minInterval', 30)
    max_interval = cfg.get('maxInterval', 60)
    account_rotation = cfg.get('accountRotation', True)
    
    is_multi_template = len(messages) > 1
    
    try:
        if is_multi_template:
            print(f"[BatchSend] 多模板模式: {len(messages)} 個模板, 策略: {send_strategy}", file=sys.stderr)
            self.send_log(f"📨 開始批量發送: {len(targets)} 個目標, {len(messages)} 個模板 ({send_strategy})", "info")
        else:
            print(f"[BatchSend] 開始批量發送: {len(targets)} 個目標", file=sys.stderr)
            self.send_log(f"📨 開始批量發送: {len(targets)} 個目標", "info")
        
        # 獲取可用帳號（檢查 Online 狀態 + 已連接的客戶端）
        accounts = await db.get_all_accounts()
        available_accounts = [a for a in accounts if a.get('status') in ('Online', 'active')]
        
        if not available_accounts:
            connected_phones = list(self.telegram_manager.clients.keys()) if hasattr(self.telegram_manager, 'clients') else []
            if connected_phones:
                available_accounts = [a for a in accounts if a.get('phone') in connected_phones]
                print(f"[BatchSend] 通過 TelegramManager 找到 {len(available_accounts)} 個已連接帳號", file=sys.stderr)
        
        print(f"[BatchSend] 可用帳號: {len(available_accounts)} 個", file=sys.stderr)
        for acc in available_accounts:
            print(f"[BatchSend]   - {acc.get('phone')} ({acc.get('status')})", file=sys.stderr)
        
        if not available_accounts:
            error_msg = "沒有可用的發送帳號，請先登入帳號"
            self.send_log(f"⚠️ {error_msg}", "warning")
            self.send_event("batch-send:complete", {
                "success": 0,
                "failed": len(targets),
                "error": error_msg,
                "failureReasons": {"no_account": len(targets)}
            })
            self._batch_send_active = False
            return
        
        success_count = 0
        failed_count = 0
        failure_reasons = {}
        failed_targets = []
        
        for idx, target in enumerate(targets):
            if self._batch_send_cancelled:
                print(f"[BatchSend] 用戶取消", file=sys.stderr)
                remaining = len(targets) - idx
                failure_reasons['cancelled'] = failure_reasons.get('cancelled', 0) + remaining
                break
            
            # 提取目標信息
            user_id = target.get('telegramId')
            username = target.get('username', '')
            first_name = target.get('firstName', target.get('first_name', ''))
            last_name = target.get('lastName', target.get('last_name', ''))
            display_name = target.get('displayName', target.get('name', first_name or username or '朋友'))
            full_name = f"{first_name} {last_name}".strip() or display_name
            group_name = target.get('groupName', target.get('sourceGroup', target.get('source', '')))
            keyword = target.get('keyword', target.get('triggeredKeyword', target.get('matchedKeyword', '')))
            source = target.get('source', target.get('sourceType', ''))
            
            try:
                # 選擇帳號
                if account_rotation:
                    account = available_accounts[idx % len(available_accounts)]
                else:
                    account = available_accounts[0]
                
                phone = account.get('phone')
                
                # 驗證目標用戶 ID
                if not user_id:
                    raise ValueError(f"目標用戶 ID 為空 (username={username})")
                
                # 時間相關變量
                now = datetime.now()
                hour = now.hour
                if 5 <= hour < 12:
                    greeting = '早上好'
                elif 12 <= hour < 14:
                    greeting = '中午好'
                elif 14 <= hour < 18:
                    greeting = '下午好'
                elif 18 <= hour < 22:
                    greeting = '晚上好'
                else:
                    greeting = '夜深了'
                
                days = ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日']
                date_str = f"{now.month}月{now.day}日"
                time_str = now.strftime('%H:%M')
                day_str = days[now.weekday()]
                
                # 選擇消息模板
                ab_test_id = cfg.get('abTestId')
                ab_variant_idx = None
                
                if ab_test_id:
                    try:
                        from core.template_ab_test import get_ab_test_manager
                        ab_mgr = get_ab_test_manager()
                        variant = ab_mgr.select_template(ab_test_id)
                        if variant and messages:
                            ab_variant_idx = variant.get('variant_index', 0)
                            tmpl_idx = min(ab_variant_idx, len(messages) - 1)
                            selected_template = messages[tmpl_idx]
                        else:
                            selected_template = messages[0] if messages else message_template
                    except Exception as ab_err:
                        print(f"[BatchSend] A/B 測試回退: {ab_err}", file=sys.stderr)
                        selected_template = messages[0] if messages else message_template
                elif is_multi_template and messages:
                    if send_strategy == 'random':
                        selected_template = random.choice(messages)
                    elif send_strategy == 'rotate':
                        selected_template = messages[idx % len(messages)]
                    else:
                        selected_template = messages[idx % len(messages)]
                else:
                    selected_template = message_template
                
                # 替換變量
                message = selected_template
                message = message.replace('{firstName}', first_name)
                message = message.replace('{first_name}', first_name)
                message = message.replace('{lastName}', last_name)
                message = message.replace('{last_name}', last_name)
                message = message.replace('{username}', username)
                message = message.replace('{displayName}', display_name)
                message = message.replace('{name}', display_name)
                message = message.replace('{fullName}', full_name)
                message = message.replace('{full_name}', full_name)
                message = message.replace('{groupName}', group_name)
                message = message.replace('{group_name}', group_name)
                message = message.replace('{keyword}', keyword)
                message = message.replace('{source}', source)
                message = message.replace('{greeting}', greeting)
                message = message.replace('{date}', date_str)
                message = message.replace('{time}', time_str)
                message = message.replace('{day}', day_str)
                
                print(f"[BatchSend] 發送 {idx + 1}/{len(targets)}: {phone} -> {user_id} ({username})", file=sys.stderr)
                
                # 🔧 核心修復：直接調用 telegram_manager.send_message
                # 不再通過 message_queue（隊列是異步的，無法得到即時反饋）
                send_result = await self.telegram_manager.send_message(
                    phone=phone,
                    user_id=str(user_id),
                    text=message,
                    attachment=attachments[0] if attachments else None,
                    source_group=group_name or None,
                    target_username=username or None
                )
                
                if send_result.get('success'):
                    success_count += 1
                    print(f"[BatchSend] ✓ 發送成功: {user_id}", file=sys.stderr)
                else:
                    raise Exception(send_result.get('error', '發送失敗'))
                
                # A/B 測試記錄
                if ab_test_id and ab_variant_idx is not None:
                    try:
                        from core.template_ab_test import get_ab_test_manager
                        ab_mgr = get_ab_test_manager()
                        test_obj = ab_mgr.get_test(ab_test_id)
                        if test_obj:
                            test_obj.record_result(ab_variant_idx, success=True)
                    except Exception:
                        pass
                
            except Exception as e:
                error_str = str(e).lower()
                print(f"[BatchSend] ✗ 發送失敗 ({user_id}): {e}", file=sys.stderr)
                failed_count += 1
                
                if ab_test_id and ab_variant_idx is not None:
                    try:
                        from core.template_ab_test import get_ab_test_manager
                        ab_mgr = get_ab_test_manager()
                        test_obj = ab_mgr.get_test(ab_test_id)
                        if test_obj:
                            test_obj.record_result(ab_variant_idx, success=False)
                    except Exception:
                        pass
                
                # 分類失敗原因
                if 'privacy' in error_str or 'private' in error_str:
                    reason = 'privacy_restricted'
                elif 'flood' in error_str:
                    reason = 'flood_wait'
                elif 'peer' in error_str or 'not found' in error_str:
                    reason = 'user_not_found'
                elif 'blocked' in error_str:
                    reason = 'user_blocked'
                elif 'id' in error_str and '為空' in str(e):
                    reason = 'invalid_id'
                else:
                    reason = 'other'
                
                failure_reasons[reason] = failure_reasons.get(reason, 0) + 1
                failed_targets.append({
                    'target': target,
                    'reason': reason,
                    'error': str(e)
                })
            
            # 🔧 立即發送進度事件
            self.send_event("batch-send:progress", {
                "sent": idx + 1,
                "success": success_count,
                "failed": failed_count,
                "total": len(targets),
                "currentTarget": display_name or username or str(user_id),
                "failureReasons": failure_reasons
            })
            
            # 間隔（只在還有下一個目標時）
            if idx < len(targets) - 1 and not self._batch_send_cancelled:
                interval = random.randint(min_interval, max_interval)
                print(f"[BatchSend] 等待 {interval}s 再發送下一條...", file=sys.stderr)
                await asyncio.sleep(interval)
        
        # 完成
        self._batch_send_active = False
        
        reason_summary = []
        reason_labels = {
            'privacy_restricted': '隱私限制',
            'flood_wait': 'API 限制',
            'user_not_found': '用戶不存在',
            'user_blocked': '被封鎖',
            'invalid_id': '無效 ID',
            'cancelled': '已取消',
            'other': '其他錯誤'
        }
        for reason, count in failure_reasons.items():
            label = reason_labels.get(reason, reason)
            reason_summary.append(f"{label}: {count}")
        
        self.send_event("batch-send:complete", {
            "success": success_count,
            "failed": failed_count,
            "failureReasons": failure_reasons,
            "failureSummary": ", ".join(reason_summary) if reason_summary else None,
            "failedTargets": failed_targets[:10]
        })
        
        if failed_count > 0:
            self.send_log(f"⚠️ 批量發送完成: 成功 {success_count}, 失敗 {failed_count} ({', '.join(reason_summary)})", "warning")
        else:
            self.send_log(f"✅ 批量發送完成: 成功 {success_count}", "success")
        
    except Exception as e:
        print(f"[BatchSend] 錯誤: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc(file=sys.stderr)
        self._batch_send_active = False
        self.send_event("batch-send:complete", {
            "success": 0, "failed": len(targets),
            "error": str(e)
        })
        self.send_log(f"❌ 批量發送錯誤: {e}", "error")


async def handle_batch_send_cancel(self, payload: Dict[str, Any]):
    """取消批量發送"""
    self._batch_send_cancelled = True
    self.send_log("⏹️ 批量發送已取消", "info")


# ====================================================================
# 🔧 P7-3: 缺失 handler 补充实现
# ====================================================================

async def handle_send_greeting(self, payload: Dict[str, Any]):
    """发送问候消息（委托到 handle_send_message）"""
    if not payload.get('text'):
        payload['text'] = payload.get('greeting', '你好！')
    return await handle_send_message(self, payload)


async def handle_add_to_queue(self, payload: Dict[str, Any]):
    """添加消息到队列（委托到 handle_send_message）"""
    return await handle_send_message(self, payload)
