"""
Extracted handler implementations: msg_templates
Auto-generated by refactor_main.py
"""
import json
import sys
import time
import asyncio
import traceback
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

from service_context import get_service_context
from database import db

from error_handler import handle_error, AppError, ErrorType
from validators import validate_template, TemplateValidator, ValidationError
# All handlers receive (self, payload) where self is BackendService instance.
# They are called via: await handler_impl(self, payload)
# Inside, use self.db, self.send_event(), self.telegram_manager, etc.
# This is a transitional pattern - later, replace self.xxx with ctx.xxx


async def handle_add_template(self, payload: Dict[str, Any]):
    """Handle add-template command"""
    try:
        # Validate template data
        is_valid, errors = validate_template(payload)
        if not is_valid:
            error_message = "Validation failed: " + "; ".join(errors)
            self.send_log(error_message, "error")
            self.send_event("template-validation-error", {
                "errors": errors,
                "template_data": payload
            })
            handle_error(
                AppError(ErrorType.VALIDATION_ERROR, error_message, {"errors": errors}),
                {"command": "add-template", "payload": payload}
            )
            return
        
        name = payload.get('name')
        prompt = payload.get('prompt')
        
        # Check if template with same name already exists
        existing = await db.get_template_by_name(name)
        if existing:
            # Template already exists, don't create duplicate
            self.send_log(f"Template '{name}' already exists (ID: {existing['id']})", "warning")
            self.send_event("template-already-exists", {
                "templateId": existing['id'],
                "name": name,
                "message": f"模板 '{name}' 已存在，未創建重複模板"
            })
        else:
            # Add new template
            template_id = await db.add_template(name, prompt)
            await db.add_log(f"Template '{name}' added", "success")
        
        await self.send_templates_update()
    
    except ValidationError as e:
        self.send_log(f"Validation error: {e.message}", "error")
        self.send_event("template-validation-error", {
            "errors": [e.message],
            "field": e.field
        })
    except Exception as e:
        self.send_log(f"Error adding template: {str(e)}", "error")
        handle_error(e, {"command": "add-template", "payload": payload})


async def handle_remove_template(self, payload: Dict[str, Any]):
    """Handle remove-template command"""
    try:
        template_id = payload.get('id')
        await db.remove_template(template_id)
        await db.add_log(f"Template {template_id} removed", "success")
        await self.send_templates_update()
    
    except Exception as e:
        self.send_log(f"Error removing template: {str(e)}", "error")


async def handle_toggle_template_status(self, payload: Dict[str, Any]):
    """Handle toggle-template-status command"""
    try:
        template_id = payload.get('id')
        await db.toggle_template_status(template_id)
        await db.add_log(f"Template {template_id} status toggled", "success")
        await self.send_templates_update()
    
    except Exception as e:
        self.send_log(f"Error toggling template status: {str(e)}", "error")

