"""
Extracted handler implementations: funnel
Auto-generated by refactor_main.py
"""
import json
import sys
import time
import asyncio
import traceback
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

from service_context import get_service_context
from database import db

from service_locator import auto_funnel, get_batch_ops, get_multi_channel_stats
# All handlers receive (self, payload) where self is BackendService instance.
# They are called via: await handler_impl(self, payload)
# Inside, use self.db, self.send_event(), self.telegram_manager, etc.
# This is a transitional pattern - later, replace self.xxx with ctx.xxx


# ==================== Auto Funnel Handlers ====================

async def handle_get_funnel_overview(self):
    """獲取漏斗總覽"""
    try:
        overview = await auto_funnel.get_funnel_overview()
        self.send_event("funnel-overview", {
            "success": True,
            **overview
        })
    except Exception as e:
        self.send_event("funnel-overview", {
            "success": False,
            "error": str(e)
        })


async def handle_transition_funnel_stage(self, payload: Dict[str, Any]):
    """手動轉換漏斗階段"""
    try:
        user_id = payload.get('userId', '')
        new_stage = payload.get('stage', '')
        reason = payload.get('reason', '手動設置')
        
        result = await auto_funnel.transition_stage(user_id, new_stage, reason)
        
        self.send_event("stage-transitioned", result)
    except Exception as e:
        self.send_event("stage-transitioned", {
            "success": False,
            "error": str(e)
        })


async def handle_batch_update_stages(self, payload: Dict[str, Any]):
    """批量更新用戶階段"""
    try:
        user_ids = payload.get('userIds', [])
        new_stage = payload.get('stage', '')
        reason = payload.get('reason', '批量更新')
        
        result = await auto_funnel.batch_update_stages(user_ids, new_stage, reason)
        
        self.send_event("batch-stages-updated", {
            "success": True,
            **result
        })
    except Exception as e:
        self.send_event("batch-stages-updated", {
            "success": False,
            "error": str(e)
        })


# ==================== Analytics Handlers ====================

async def handle_analyze_funnel(self, payload: Dict[str, Any]):
    """分析轉化漏斗"""
    try:
        from analytics_engine import AnalyticsEngine
        
        days = payload.get('days', 30)
        start_date = payload.get('startDate')
        end_date = payload.get('endDate')
        
        # 轉換日期
        start_dt = None
        end_dt = None
        if start_date:
            try:
                start_dt = datetime.fromisoformat(start_date.replace('Z', '+00:00'))
            except:
                pass
        if end_date:
            try:
                end_dt = datetime.fromisoformat(end_date.replace('Z', '+00:00'))
            except:
                pass
        
        engine = AnalyticsEngine(db)
        result = await engine.analyze_funnel(
            days=days,
            start_date=start_dt,
            end_date=end_dt
        )
        
        self.send_event("funnel-analysis", {
            "success": True,
            **result
        })
    except Exception as e:
        self.send_event("funnel-analysis", {
            "success": False,
            "error": str(e)
        })


async def handle_get_funnel_stats(self, payload: Dict[str, Any] = None):
    """獲取漏斗統計"""
    try:
        stats = await db.get_detailed_funnel_stats()
        self.send_event("funnel-stats", stats)
        
    except Exception as e:
        import traceback
        traceback.print_exc(file=sys.stderr)
        self.send_event("funnel-stats", {
            "stages": {},
            "tags": [],
            "interest_distribution": {},
            "error": str(e)
        })


async def handle_bulk_update_user_stage(self, payload: Dict[str, Any]):
    """批量更新用戶階段"""
    try:
        user_ids = payload.get('userIds', [])
        stage = payload.get('stage', '')
        
        if not user_ids:
            raise ValueError("請選擇要更新的用戶")
        if not stage:
            raise ValueError("請選擇目標階段")
        
        await db.bulk_update_user_stage(user_ids, stage)
        
        self.send_log(f"已將 {len(user_ids)} 個用戶更新為 {stage} 階段", "success")
        self.send_event("bulk-update-complete", {
            "success": True,
            "type": "stage",
            "count": len(user_ids)
        })
        
    except Exception as e:
        self.send_log(f"批量更新階段失敗: {str(e)}", "error")
        self.send_event("bulk-update-complete", {
            "success": False,
            "error": str(e)
        })


async def handle_batch_update_funnel_stage(self, payload: Dict[str, Any]):
    """批量更新漏斗階段"""
    try:
        lead_ids = payload.get('leadIds', [])
        new_stage = payload.get('newStage')
        
        if not lead_ids:
            self.send_event("batch-operation-result", {
                "success": False,
                "error": "未選擇任何 Lead"
            })
            return
        
        if not new_stage:
            self.send_event("batch-operation-result", {
                "success": False,
                "error": "未指定新階段"
            })
            return
        
        batch_ops = get_batch_ops()
        if not batch_ops:
            self.send_event("batch-operation-result", {
                "success": False,
                "error": "批量操作系統未初始化"
            })
            return
        
        result = await batch_ops.batch_update_funnel_stage(lead_ids, new_stage)
        
        if result.get('success'):
            self.send_log(f"批量更新漏斗階段完成: {result.get('successCount')}/{len(lead_ids)} 成功", "success")
        else:
            self.send_log(f"批量更新漏斗階段失敗: {result.get('error')}", "error")
        
        self.send_event("batch-operation-result", result)
        
    except Exception as e:
        self.send_log(f"批量更新漏斗階段失敗: {str(e)}", "error")
        self.send_event("batch-operation-result", {
            "success": False,
            "error": str(e)
        })


async def handle_get_funnel_analysis(self, payload: Dict[str, Any]):
    """獲取漏斗分析"""
    try:
        stats = get_multi_channel_stats()
        if not stats:
            self.send_event("funnel-analysis", {"success": False, "error": "統計系統未初始化"})
            return
        
        result = await stats.get_funnel_analysis()
        
        self.send_event("funnel-analysis", result)
        
    except Exception as e:
        self.send_event("funnel-analysis", {"success": False, "error": str(e)})


async def handle_process_stage_event(self, payload: Dict[str, Any]):
    """處理階段流轉事件"""
    try:
        from stage_flow import process_stage_event
        
        result = await process_stage_event(
            lead_id=payload.get("leadId"),
            current_stage=payload.get("currentStage"),
            trigger=payload.get("trigger"),
            event_data=payload.get("eventData", {})
        )
        
        self.send_event("stage-event-processed", {
            "success": True,
            "transition": result
        })
    except Exception as e:
        print(f"[Backend] Error processing stage event: {e}", file=sys.stderr)
        self.send_event("stage-event-processed", {"success": False, "error": str(e)})


async def handle_get_stage_flow(self, payload: Dict[str, Any]):
    """獲取階段流轉配置"""
    try:
        from stage_flow import get_stage_flow_manager
        
        manager = get_stage_flow_manager()
        visualization = manager.get_flow_visualization()
        
        self.send_event("stage-flow", {"success": True, **visualization})
    except Exception as e:
        print(f"[Backend] Error getting stage flow: {e}", file=sys.stderr)
        self.send_event("stage-flow", {"success": False, "error": str(e)})


# ====================================================================
# 🔧 P7-3: 缺失 handler 补充实现
# ====================================================================

async def handle_get_detailed_funnel_stats(self, payload: Dict[str, Any] = None):
    """获取详细漏斗统计（委托到 handle_get_funnel_stats）"""
    return await handle_get_funnel_stats(self, payload)

