"""
Extracted handler implementations: members
Auto-generated by refactor_main.py
"""
import json
import sys
import time
import asyncio
import traceback
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

from service_context import get_service_context

from database import db
import re
from service_locator import member_extraction_service
# All handlers receive (self, payload) where self is BackendService instance.
# They are called via: await handler_impl(self, payload)
# Inside, use self.db, self.send_event(), self.telegram_manager, etc.
# This is a transitional pattern - later, replace self.xxx with ctx.xxx


# ==================== 成員提取處理器 ====================

async def handle_batch_refresh_member_counts(self, payload: Dict[str, Any]):
    """🆕 批量刷新群組成員數"""
    import sys
    print(f"[Backend] handle_batch_refresh_member_counts called", file=sys.stderr)
    
    groups = payload.get('groups', [])
    if not groups:
        self.send_event("batch-refresh-member-counts-complete", {
            "success": True,
            "total": 0,
            "updated": 0,
            "failed": 0
        })
        return
    
    try:
        # 找到可用的客戶端
        client = None
        for c in self.telegram_manager._clients.values():
            if c and c.is_connected:
                client = c
                break
        
        if not client:
            self.send_event("batch-refresh-member-counts-complete", {
                "success": False,
                "error": "沒有可用的在線帳號"
            })
            return
        
        updated_count = 0
        failed_count = 0
        
        for i, group in enumerate(groups):
            try:
                group_id = group.get('id')
                url = group.get('url', '')
                
                # 解析群組標識
                chat_identifier = url
                if url.startswith('https://t.me/'):
                    chat_identifier = url.replace('https://t.me/', '')
                if not chat_identifier.startswith('@') and not chat_identifier.startswith('+'):
                    chat_identifier = f"@{chat_identifier}"
                
                # 獲取成員數
                chat = await client.get_chat(chat_identifier)
                member_count = chat.members_count or 0
                
                # 更新數據庫
                if member_count > 0:
                    await db.update_group_member_count(url, member_count)
                    updated_count += 1
                
                # 發送進度
                self.send_event("batch-refresh-member-counts-progress", {
                    "current": i + 1,
                    "total": len(groups),
                    "groupId": str(group_id),
                    "memberCount": member_count
                })
                
                # 避免觸發速率限制
                await asyncio.sleep(0.5)
                
            except Exception as e:
                print(f"[Backend] Error refreshing member count for group {group.get('id')}: {e}", file=sys.stderr)
                failed_count += 1
                
                # 仍然發送進度
                self.send_event("batch-refresh-member-counts-progress", {
                    "current": i + 1,
                    "total": len(groups),
                    "groupId": str(group.get('id')),
                    "memberCount": 0
                })
        
        self.send_event("batch-refresh-member-counts-complete", {
            "success": True,
            "total": len(groups),
            "updated": updated_count,
            "failed": failed_count
        })
        
    except Exception as e:
        import traceback
        traceback.print_exc()
        self.send_event("batch-refresh-member-counts-complete", {
            "success": False,
            "error": str(e)
        })


async def handle_get_group_member_count(self, payload: Dict[str, Any]):
    """🆕 獲取群組成員數（支持重新獲取）"""
    import sys
    print(f"[Backend] handle_get_group_member_count called with payload: {payload}", file=sys.stderr)
    
    group_id = payload.get('groupId')
    url = payload.get('url', '')
    account_phone = payload.get('accountPhone')
    
    try:
        # 找到可用的客戶端
        client = None
        phone = account_phone
        
        if account_phone:
            client = self.telegram_manager.get_client(account_phone)
        
        if not client or not client.is_connected:
            # 嘗試使用任意在線帳號
            for acc_phone, c in self.telegram_manager._clients.items():
                if c and c.is_connected:
                    client = c
                    phone = acc_phone
                    break
        
        if not client or not client.is_connected:
            self.send_event("group-member-count-result", {
                "success": False,
                "groupId": group_id,
                "error": "沒有可用的在線帳號"
            })
            return
        
        # 🔧 修復：解析群組標識，支持多種格式
        telegram_id = payload.get('telegramId') or payload.get('telegram_id')
        chat_identifier = None
        
        # 優先使用 telegram_id（數字 ID）
        if telegram_id:
            try:
                chat_identifier = int(telegram_id)
                print(f"[Backend] Using telegram_id: {chat_identifier}", file=sys.stderr)
            except (ValueError, TypeError):
                chat_identifier = None
        
        # 其次使用 url
        if not chat_identifier and url:
            chat_identifier = url
            if url.startswith('https://t.me/'):
                chat_identifier = url.replace('https://t.me/', '')
            if isinstance(chat_identifier, str):
                if chat_identifier.startswith('+'):
                    # 私有群組邀請鏈接
                    chat_identifier = url
                elif chat_identifier and not chat_identifier.startswith('@'):
                    chat_identifier = f"@{chat_identifier}"
        
        if not chat_identifier:
            self.send_event("group-member-count-result", {
                "success": False,
                "groupId": group_id,
                "error": "缺少群組標識（URL 或 Telegram ID）"
            })
            return
        
        print(f"[Backend] Getting member count for: {chat_identifier}", file=sys.stderr)
        
        # 獲取群組信息
        try:
            chat = await client.get_chat(chat_identifier)
            member_count = chat.members_count or 0
            
            print(f"[Backend] Got member count: {member_count}", file=sys.stderr)
            
            # 更新數據庫
            if member_count > 0:
                await db.update_group_member_count(url, member_count)
            
            self.send_event("group-member-count-result", {
                "success": True,
                "groupId": group_id,
                "memberCount": member_count,
                "chatTitle": chat.title
            })
            
        except Exception as chat_err:
            error_str = str(chat_err).lower()
            if 'not found' in error_str or 'invalid' in error_str:
                error_msg = "群組不存在或無法訪問"
            elif 'banned' in error_str or 'kicked' in error_str:
                error_msg = "帳號被踢出該群組"
            elif 'private' in error_str:
                error_msg = "這是私有群組，需要邀請鏈接"
            else:
                error_msg = f"獲取失敗：{str(chat_err)}"
            
            print(f"[Backend] Error getting chat: {chat_err}", file=sys.stderr)
            self.send_event("group-member-count-result", {
                "success": False,
                "groupId": group_id,
                "error": error_msg
            })
            
    except Exception as e:
        import traceback
        traceback.print_exc()
        self.send_event("group-member-count-result", {
            "success": False,
            "groupId": group_id,
            "error": f"獲取成員數失敗：{str(e)}"
        })


async def handle_collect_users_from_history_advanced(self, payload: Dict[str, Any]):
    """🆕 從歷史消息收集用戶（進階版，支持更多配置）"""
    import sys
    from datetime import datetime, timedelta
    print(f"[Backend] handle_collect_users_from_history_advanced: {payload}", file=sys.stderr)
    
    group_id = payload.get('groupId')
    telegram_id = payload.get('telegramId')
    config = payload.get('config', {})
    
    # 解析配置
    limit = config.get('limit', 200)
    time_range = config.get('timeRange', '30d')
    min_messages = config.get('minMessages', 1)
    skip_duplicates = config.get('skipDuplicates', True)
    exclude_bots = config.get('excludeBots', True)
    require_username = config.get('requireUsername', False)
    auto_sync = config.get('autoSync', True)
    
    try:
        from database import db
        from config import config
        await db.connect()
        
        chat_id = str(telegram_id) if telegram_id else str(group_id)
        
        # 構建時間條件
        time_condition = ""
        if time_range == '7d':
            cutoff = (datetime.now() - timedelta(days=7)).isoformat()
            time_condition = f"AND timestamp >= '{cutoff}'"
        elif time_range == '30d':
            cutoff = (datetime.now() - timedelta(days=30)).isoformat()
            time_condition = f"AND timestamp >= '{cutoff}'"
        elif time_range == '90d':
            cutoff = (datetime.now() - timedelta(days=90)).isoformat()
            time_condition = f"AND timestamp >= '{cutoff}'"
        
        # 發送進度更新
        self.send_event("history-collection-progress", {
            "groupId": group_id,
            "current": 0,
            "total": 100,
            "status": "正在查詢歷史消息..."
        })
        
        # 構建查詢
        limit_clause = f"LIMIT {limit}" if limit > 0 else ""
        
        query = f"""
            SELECT 
                sender_id,
                sender_name,
                sender_username,
                COUNT(*) as message_count,
                MAX(timestamp) as last_message_at
            FROM chat_history 
            WHERE chat_id = ? 
              AND sender_id IS NOT NULL 
              AND sender_id != ''
              {time_condition}
            GROUP BY sender_id
            HAVING message_count >= ?
            ORDER BY message_count DESC
            {limit_clause}
        """
        
        results = await db.fetch_all(query, (chat_id, min_messages))
        
        if not results:
            self.send_event("history-collection-result", {
                "groupId": group_id,
                "success": False,
                "error": "未找到符合條件的用戶"
            })
            return
        
        total = len(results)
        collected_count = 0
        new_count = 0
        updated_count = 0
        skipped_count = 0
        
        # 質量統計
        high_activity = 0
        medium_activity = 0
        low_activity = 0
        
        for idx, row in enumerate(results):
            try:
                sender_id = row['sender_id'] if hasattr(row, '__getitem__') else row[0]
                sender_name = row['sender_name'] if hasattr(row, '__getitem__') else row[1]
                sender_username = row['sender_username'] if hasattr(row, '__getitem__') else row[2]
                message_count = row['message_count'] if hasattr(row, '__getitem__') else row[3]
                last_message = row['last_message_at'] if hasattr(row, '__getitem__') else row[4]
                
                if not sender_id:
                    continue
                
                # 檢查是否需要用戶名
                if require_username and not sender_username:
                    skipped_count += 1
                    continue
                
                # 檢查是否是機器人（簡單判斷）
                if exclude_bots:
                    if sender_username and sender_username.lower().endswith('bot'):
                        skipped_count += 1
                        continue
                
                # 檢查是否已存在
                if skip_duplicates:
                    existing = await db.fetch_one(
                        "SELECT id FROM collected_users WHERE telegram_id = ?",
                        (str(sender_id),)
                    )
                    if existing:
                        updated_count += 1
                        # 更新現有記錄
                        await db.execute(
                            """UPDATE collected_users 
                               SET message_count = ?, last_message_at = ?, updated_at = CURRENT_TIMESTAMP
                               WHERE telegram_id = ?""",
                            (message_count, last_message, str(sender_id))
                        )
                        continue
                
                # 插入新用戶
                user_data = {
                    'telegram_id': str(sender_id),
                    'username': sender_username or '',
                    'first_name': sender_name or '',
                    'last_name': '',
                    'source_groups': [chat_id],
                    'collected_by': 'history_scan',
                    'message_count': message_count,
                    'last_message_at': last_message
                }
                
                user_id = await db.upsert_collected_user(user_data)
                collected_count += 1
                if user_id > 0:
                    new_count += 1
                
                # 統計質量
                if message_count >= 10:
                    high_activity += 1
                elif message_count >= 3:
                    medium_activity += 1
                else:
                    low_activity += 1
                
                # 發送進度
                if idx % 10 == 0:
                    self.send_event("history-collection-progress", {
                        "groupId": group_id,
                        "current": idx + 1,
                        "total": total,
                        "status": f"已處理 {idx + 1}/{total} 位用戶"
                    })
                    
            except Exception as row_err:
                print(f"[Backend] Error processing row: {row_err}", file=sys.stderr)
                continue
        
        self.send_log(f"✅ 歷史消息收集完成: 共 {collected_count} 位用戶，新增 {new_count} 位", "success")
        
        self.send_event("history-collection-result", {
            "groupId": group_id,
            "success": True,
            "result": {
                "success": True,
                "collected": collected_count,
                "newUsers": new_count,
                "updated": updated_count,
                "skipped": skipped_count,
                "quality": {
                    "highActivity": high_activity,
                    "mediumActivity": medium_activity,
                    "lowActivity": low_activity
                }
            }
        })
        
    except Exception as e:
        import traceback
        traceback.print_exc(file=sys.stderr)
        self.send_log(f"❌ 收集失敗: {str(e)}", "error")
        self.send_event("history-collection-result", {
            "groupId": group_id,
            "success": False,
            "error": str(e)
        })


async def handle_collect_users_from_history(self, payload: Dict[str, Any]):
    """🆕 從歷史消息中收集用戶（替代成員提取）"""
    import sys
    print(f"[Backend] ========== handle_collect_users_from_history CALLED ==========", file=sys.stderr)
    
    group_id = payload.get('groupId')
    telegram_id = payload.get('telegramId')
    limit = payload.get('limit', 500)
    
    try:
        from database import db
        await db.connect()
        
        self.send_log(f"🔄 正在從歷史消息中收集用戶...", "info")
        
        # 查詢群組的歷史消息中的唯一發送者
        chat_id = str(telegram_id) if telegram_id else str(group_id)
        
        # 從 chat_history 表獲取唯一發送者
        query = """
            SELECT DISTINCT 
                sender_id,
                sender_name,
                sender_username,
                COUNT(*) as message_count,
                MAX(timestamp) as last_message_at
            FROM chat_history 
            WHERE chat_id = ? AND sender_id IS NOT NULL AND sender_id != ''
            GROUP BY sender_id
            ORDER BY message_count DESC
            LIMIT ?
        """
        
        results = await db.fetch_all(query, (chat_id, limit))
        
        if not results:
            self.send_log(f"⚠️ 未找到歷史消息，請先開啟群組監控", "warning")
            self.send_event("collect-from-history-result", {
                "groupId": group_id,
                "success": False,
                "error": "未找到歷史消息，請先開啟群組監控一段時間",
                "collected": 0,
                "total": 0
            })
            return
        
        # 🔧 Phase8-P1: 帶進度反饋的收集循環
        collected_count = 0
        new_count = 0
        total = len(results)
        
        # 初始進度
        self.send_event("collect-from-history-progress", {
            "groupId": group_id,
            "current": 0,
            "total": total,
            "collected": 0,
            "newUsers": 0,
            "status": f"開始處理 {total} 位用戶..."
        })
        
        for idx, row in enumerate(results):
            try:
                sender_id = row['sender_id'] if hasattr(row, '__getitem__') else row[0]
                sender_name = row['sender_name'] if hasattr(row, '__getitem__') else row[1]
                sender_username = row['sender_username'] if hasattr(row, '__getitem__') else row[2]
                message_count = row['message_count'] if hasattr(row, '__getitem__') else row[3]
                last_message = row['last_message_at'] if hasattr(row, '__getitem__') else row[4]
                
                if not sender_id:
                    continue
                
                user_data = {
                    'telegram_id': str(sender_id),
                    'username': sender_username or '',
                    'first_name': sender_name or '',
                    'last_name': '',
                    'source_groups': [chat_id],
                    'collected_by': 'history_scan',
                    'message_count': message_count,
                    'last_message_at': last_message
                }
                
                user_id = await db.upsert_collected_user(user_data)
                collected_count += 1
                if user_id > 0:
                    new_count += 1
                
                # 每 5 個用戶發送進度更新（比每 10 個更精細）
                if (idx + 1) % 5 == 0 or idx == total - 1:
                    self.send_event("collect-from-history-progress", {
                        "groupId": group_id,
                        "current": idx + 1,
                        "total": total,
                        "collected": collected_count,
                        "newUsers": new_count,
                        "status": f"已處理 {idx + 1}/{total}"
                    })
                    
            except Exception as row_err:
                print(f"[Backend] Error processing row: {row_err}", file=sys.stderr)
                continue
        
        # 🔧 Phase8-P1-2: 收集完成後更新緩存統計
        try:
            await db.execute(
                "UPDATE monitored_groups SET cached_user_count = ?, cached_msg_count = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? OR telegram_id = ?",
                (collected_count, total, group_id, chat_id)
            )
        except Exception:
            pass  # 列可能還未添加
        
        self.send_log(f"✅ 從歷史消息收集完成: 共 {collected_count} 位用戶，新增 {new_count} 位", "success")
        
        self.send_event("collect-from-history-result", {
            "groupId": group_id,
            "success": True,
            "collected": collected_count,
            "newUsers": new_count,
            "total": len(results)
        })
        
    except Exception as e:
        import traceback
        traceback.print_exc(file=sys.stderr)
        self.send_log(f"❌ 收集失敗: {str(e)}", "error")
        self.send_event("collect-from-history-result", {
            "groupId": group_id,
            "success": False,
            "error": str(e),
            "collected": 0
        })


async def handle_extract_members(self, payload: Dict[str, Any]):
    """提取群組成員"""
    import sys
    print(f"[Backend] ========== handle_extract_members CALLED ==========", file=sys.stderr)
    print(f"[Backend] Payload: {payload}", file=sys.stderr)
    self.send_log("📥 收到成員提取請求", "info")
    
    try:
        # 🔧 FIX: 優先使用 telegramId（數字 ID），支持私有群組
        telegram_id = payload.get('telegramId')
        chat_id = payload.get('chatId')
        username = payload.get('username')
        phone = payload.get('phone')
        resource_id = payload.get('resourceId') or payload.get('groupId')
        group_name = payload.get('groupName') or payload.get('groupTitle') or ''
        limit = payload.get('limit', 100)
        
        # 🆕 Phase5: 每日提取配額檢查（防止過度使用被 Telegram 封號）
        DAILY_EXTRACT_LIMIT = 5000  # 每日最多提取 5000 人
        daily_quota = None
        try:
            from database import db as quota_db
            await quota_db.connect()
            today_count_row = await quota_db.fetch_one(
                """SELECT COALESCE(SUM(extracted_count), 0) as total 
                   FROM member_extraction_logs 
                   WHERE status = 'success' AND date(created_at) = date('now')""",
                ()
            )
            today_extracted = 0
            if today_count_row:
                today_extracted = today_count_row.get('total') if hasattr(today_count_row, 'get') else today_count_row[0]
                today_extracted = today_extracted or 0
            
            remaining = max(0, DAILY_EXTRACT_LIMIT - today_extracted)
            daily_quota = {
                "used": today_extracted,
                "limit": DAILY_EXTRACT_LIMIT,
                "remaining": remaining
            }
            
            if remaining <= 0:
                self.send_log(f"⚠️ 今日提取配額已用完 ({today_extracted}/{DAILY_EXTRACT_LIMIT})", "warning")
                self.send_event("members-extracted", {
                    "resourceId": resource_id,
                    "success": False,
                    "error": f"今日提取配額已達上限 ({DAILY_EXTRACT_LIMIT} 人)，明天將自動重置",
                    "error_code": "E4005_QUOTA_EXCEEDED",
                    "error_details": {
                        "code": "E4005",
                        "reason": f"今日已提取 {today_extracted} 人，達到每日上限 {DAILY_EXTRACT_LIMIT}",
                        "suggestion": "請明天再試，或升級帳戶提高配額",
                        "action": "quota_exceeded",
                        "daily_quota": daily_quota
                    },
                    "members": [], "extracted": 0, "total": 0
                })
                return
            
            # 自動限制 limit 不超過剩餘配額
            if limit > remaining:
                limit = remaining
                self.send_log(f"⚠️ 已調整提取上限為 {limit}（今日剩餘配額）", "info")
                
        except Exception as quota_err:
            print(f"[Backend] Quota check error (non-fatal): {quota_err}", file=sys.stderr)
        
        # 🆕 Phase: Payload 自動補全 — 5 個前端入口 payload 不一致，從 DB 填充缺失字段
        if resource_id and (not telegram_id or not username or not phone):
            try:
                from database import db as _autofill_db
                await _autofill_db.connect()
                full_resource = await _autofill_db.fetch_one(
                    "SELECT telegram_id, username, title, joined_by_phone FROM discovered_resources WHERE id = ?",
                    (resource_id,)
                )
                if full_resource:
                    db_tg_id = full_resource.get('telegram_id') if hasattr(full_resource, 'get') else full_resource[0]
                    db_username = full_resource.get('username') if hasattr(full_resource, 'get') else full_resource[1]
                    db_phone = full_resource.get('joined_by_phone') if hasattr(full_resource, 'get') else full_resource[3]
                    if not telegram_id and db_tg_id:
                        telegram_id = db_tg_id
                    if not username and db_username:
                        username = db_username
                    if not phone and db_phone:
                        phone = db_phone
                    print(f"[Backend] ✓ Payload auto-filled: telegramId={telegram_id}, username={username}, phone={phone}", file=sys.stderr)
            except Exception as autofill_err:
                print(f"[Backend] Payload auto-fill error: {autofill_err}", file=sys.stderr)
        
        # 從 filters 獲取過濾選項
        filters = payload.get('filters', {})
        filter_bots = filters.get('bots', True) if filters else payload.get('filterBots', True)
        
        # 🔧 修復：優先使用 onlineStatus 字符串
        online_status = None
        if filters:
            # 優先使用明確的 onlineStatus 字符串
            online_status = filters.get('onlineStatus')
            
            # 回退：使用布爾值
            if not online_status:
                if filters.get('online') == True:
                    online_status = 'online'
                elif filters.get('offline') == True:
                    online_status = 'offline'
        
        # 默認值
        if not online_status:
            online_status = 'all'
        
        filter_offline = filters.get('offline', False) if filters else payload.get('filterOffline', False)
        chinese_only = filters.get('chinese', False) if filters else False
        premium_only = filters.get('isPremium', False) if filters else False
        has_username = filters.get('hasUsername', False) if filters else False
        
        print(f"[Backend] Online status filter: {online_status}", file=sys.stderr)
        
        # 🔧 FIX: 決定使用哪個 ID
        # 優先級: telegramId > 有效的 username > 從數據庫查詢
        effective_chat_id = None
        
        # 1. 優先使用 telegramId（對私有群組有效）
        if telegram_id and str(telegram_id).lstrip('-').isdigit():
            effective_chat_id = int(telegram_id)
            print(f"[Backend] Using telegramId: {effective_chat_id}", file=sys.stderr)
        
        # 2. 如果 chatId 是數字 ID，使用它
        elif chat_id and str(chat_id).lstrip('-').isdigit():
            effective_chat_id = int(chat_id)
            print(f"[Backend] Using numeric chatId: {effective_chat_id}", file=sys.stderr)
        
        # 3. 如果 chatId 是有效的 username（不是邀請鏈接格式），使用它
        elif chat_id and not str(chat_id).startswith('+'):
            effective_chat_id = chat_id
            print(f"[Backend] Using username chatId: {effective_chat_id}", file=sys.stderr)
        
        # 4. 從數據庫查詢 telegram_id
        if not effective_chat_id:
            print(f"[Backend] No valid chat_id, trying to fetch from database...", file=sys.stderr)
            if resource_id:
                # 嘗試從 monitored_groups 表查詢
                from database import db
                await db.connect()
                group = await db.fetch_one(
                    "SELECT telegram_id, link FROM monitored_groups WHERE id = ?",
                    (resource_id,)
                )
                if group:
                    db_telegram_id = group.get('telegram_id') if hasattr(group, 'get') else (group[0] if group else None)
                    if db_telegram_id:
                        effective_chat_id = int(db_telegram_id) if str(db_telegram_id).lstrip('-').isdigit() else db_telegram_id
                        print(f"[Backend] Found telegram_id from database: {effective_chat_id}", file=sys.stderr)
        
        print(f"[Backend] extract-members: effective_chat_id={effective_chat_id}, resource_id={resource_id}, limit={limit}", file=sys.stderr)
        print(f"[Backend] Filters: bots={filter_bots}, offline={filter_offline}, chinese={chinese_only}", file=sys.stderr)
        
        if not effective_chat_id:
            self.send_event("members-extracted", {
                "resourceId": resource_id,
                "success": False,
                "error": "群組 ID 不能為空。對於私有群組，需要先獲取其 Telegram ID。",
                "error_code": "E4004_NO_CHAT_ID",
                "error_details": {
                    "code": "E4004",
                    "reason": "無法確定群組標識",
                    "suggestion": "請先通過搜索發現或手動輸入群組鏈接來獲取群組信息",
                    "action": "go_to_search"
                },
                "members": [],
                "extracted": 0,
                "total": 0
            })
            return
        
        chat_id = effective_chat_id
        
        # 🔧 P0 FIX: 優先使用已加入群組的帳號
        if not phone:
            from database import db
            await db.connect()
            
            # 1. 嘗試從 discovered_resources 獲取 joined_by_phone 和 joined_at
            # 🔧 P1 優化：同時獲取 joined_at 用於智能延遲
            try:
                resource = None
                joined_at_str = None
                
                # 1a. 按 resource_id 查詢
                if resource_id:
                    resource = await db.fetch_one(
                        "SELECT joined_by_phone, telegram_id, joined_at FROM discovered_resources WHERE id = ?",
                        (resource_id,)
                    )
                    print(f"[Backend] Query by resource_id={resource_id}: found={resource is not None}", file=sys.stderr)
                
                # 1b. 按 telegram_id 查詢 — 🆕 嘗試兩種格式（原始 ID + -100 前綴）
                if not resource and telegram_id:
                    tid_str = str(telegram_id)
                    resource = await db.fetch_one(
                        "SELECT joined_by_phone, telegram_id, joined_at FROM discovered_resources WHERE telegram_id = ?",
                        (tid_str,)
                    )
                    # 🆕 如果沒找到，嘗試 -100 前綴（超級群組 ID 格式轉換）
                    if not resource and tid_str.lstrip('-').isdigit():
                        tid_int = int(tid_str)
                        if tid_int > 1000000000:
                            alt_tid = f"-100{tid_int}"
                            resource = await db.fetch_one(
                                "SELECT joined_by_phone, telegram_id, joined_at FROM discovered_resources WHERE telegram_id = ?",
                                (alt_tid,)
                            )
                            if resource:
                                print(f"[Backend] ✓ Found with -100 prefix: {alt_tid}", file=sys.stderr)
                        elif tid_str.startswith('-100') and len(tid_str) > 4:
                            original_tid = tid_str[4:]
                            resource = await db.fetch_one(
                                "SELECT joined_by_phone, telegram_id, joined_at FROM discovered_resources WHERE telegram_id = ?",
                                (original_tid,)
                            )
                            if resource:
                                print(f"[Backend] ✓ Found with original ID: {original_tid}", file=sys.stderr)
                    print(f"[Backend] Query by telegram_id={telegram_id}: found={resource is not None}", file=sys.stderr)
                
                # 1c. 按 username 查詢
                if not resource and username:
                    resource = await db.fetch_one(
                        "SELECT joined_by_phone, telegram_id, joined_at FROM discovered_resources WHERE username = ?",
                        (username.lstrip('@'),)
                    )
                    print(f"[Backend] Query by username={username}: found={resource is not None}", file=sys.stderr)
                
                if resource:
                    joined_phone = resource.get('joined_by_phone') if hasattr(resource, 'get') else resource[0]
                    joined_at_str = resource.get('joined_at') if hasattr(resource, 'get') else (resource[2] if len(resource) > 2 else None)
                    print(f"[Backend] Found joined_by_phone={joined_phone}, joined_at={joined_at_str}", file=sys.stderr)
                    
                    # 🆕 Phase3: 自適應智能等待 — 先嘗試解析群組，失敗再等待
                    if joined_at_str and joined_phone and joined_phone in self.telegram_manager.clients:
                        try:
                            from datetime import datetime
                            if isinstance(joined_at_str, str):
                                joined_at = datetime.fromisoformat(joined_at_str.replace('Z', '+00:00'))
                            else:
                                joined_at = joined_at_str
                            
                            time_since_join = (datetime.now() - joined_at.replace(tzinfo=None)).total_seconds()
                            
                            # 只在最近 120 秒內加入的群組才需要智能等待
                            if time_since_join < 120:
                                # 先嘗試直接解析群組實體 — 如果成功說明已同步
                                test_client = self.telegram_manager.clients.get(joined_phone)
                                if test_client and test_client.is_connected:
                                    try:
                                        test_target = effective_chat_id
                                        test_chat = await test_client.get_chat(test_target)
                                        if test_chat:
                                            # 解析成功 — 無需等待
                                            self.send_log(f"✓ 群組已同步 (加入 {int(time_since_join)}s 前)", "info")
                                            print(f"[Backend] Smart wait: chat resolved immediately after {int(time_since_join)}s", file=sys.stderr)
                                    except Exception as resolve_err:
                                        resolve_err_str = str(resolve_err)
                                        if 'PEER_ID_INVALID' in resolve_err_str or 'not found' in resolve_err_str.lower():
                                            # 解析失敗 — 需要等待，但用自適應延遲
                                            adaptive_wait = min(max(5, int(15 - time_since_join / 8)), 20)
                                            self.send_log(f"⏳ 群組同步中 (加入 {int(time_since_join)}s 前)，等待 {adaptive_wait}s...", "info")
                                            self.send_event("members-extraction-progress", {
                                                "resourceId": resource_id,
                                                "status": "waiting",
                                                "message": f"等待群組同步 ({adaptive_wait}s)...",
                                                "extracted": 0,
                                                "total": 0
                                            })
                                            await asyncio.sleep(adaptive_wait)
                                            self.send_log(f"✓ 同步等待完成", "info")
                                        else:
                                            print(f"[Backend] Smart wait: unexpected error: {resolve_err}", file=sys.stderr)
                        except Exception as dt_err:
                            print(f"[Backend] Error in smart wait: {dt_err}", file=sys.stderr)
                    
                    if joined_phone and joined_phone in self.telegram_manager.clients:
                        phone = joined_phone
                        print(f"[Backend] ✓ Using joined_by_phone from discovered_resources: {phone}", file=sys.stderr)
                    elif joined_phone:
                        print(f"[Backend] ⚠ joined_by_phone {joined_phone} not in connected clients", file=sys.stderr)
            except Exception as e:
                print(f"[Backend] Error fetching joined_by_phone: {e}", file=sys.stderr)
            
            # 2. 嘗試從 monitored_groups 獲取 phone — 🆕 兼容兩種 telegram_id 格式
            if not phone:
                try:
                    chat_id_str = str(effective_chat_id)
                    # 🆕 構建可能的 telegram_id 格式列表
                    tid_variants = [chat_id_str]
                    if chat_id_str.lstrip('-').isdigit():
                        tid_int = int(chat_id_str)
                        if tid_int > 1000000000:
                            tid_variants.append(f"-100{tid_int}")
                        elif chat_id_str.startswith('-100') and len(chat_id_str) > 4:
                            tid_variants.append(chat_id_str[4:])
                    
                    group = None
                    for tid in tid_variants:
                        group = await db.fetch_one(
                            """SELECT phone FROM monitored_groups 
                               WHERE telegram_id = ? OR link LIKE ?""",
                            (tid, f"%{tid}%")
                        )
                        if group:
                            break
                    
                    # 也嘗試用 username 匹配
                    if not group and username:
                        group = await db.fetch_one(
                            """SELECT phone FROM monitored_groups 
                               WHERE link LIKE ? OR name LIKE ?""",
                            (f"%{username}%", f"%{username}%")
                        )
                    
                    if group:
                        group_phone = group.get('phone') if hasattr(group, 'get') else group[0]
                        if group_phone and group_phone in self.telegram_manager.clients:
                            phone = group_phone
                            print(f"[Backend] ✓ Using phone from monitored_groups: {phone}", file=sys.stderr)
                except Exception as e:
                    print(f"[Backend] Error fetching phone from monitored_groups: {e}", file=sys.stderr)
            
            # 3. 🆕 Phase3: 智能角色回退 — 優先 Listener > Explorer > any
            if not phone and self.telegram_manager.clients:
                try:
                    from database import db as _db
                    connected_phones = [p for p, c in self.telegram_manager.clients.items() if c and c.is_connected]
                    if connected_phones:
                        # 統一使用 get_all_accounts，多租戶安全，然後按連接中的 phone 過濾
                        all_accounts = await _db.get_all_accounts()
                        accounts = [a for a in all_accounts if a.get('phone') in connected_phones]
                        role_map = {a['phone']: a.get('role', 'Unassigned') for a in accounts} if accounts else {}
                        
                        # 優先 Listener（監控號通常已加入群組）
                        for pref_role in ['Listener', 'Explorer', 'Unassigned', 'Sender']:
                            for p in connected_phones:
                                if role_map.get(p, 'Unassigned') == pref_role:
                                    phone = p
                                    break
                            if phone:
                                break
                except Exception as role_err:
                    print(f"[Backend] Role-based selection failed: {role_err}", file=sys.stderr)
                
                if not phone:
                    phone = list(self.telegram_manager.clients.keys())[0]
                
                role_info = role_map.get(phone, '未知') if 'role_map' in locals() else '未知'
                print(f"[Backend] ⚠ Using fallback phone: {phone} (role: {role_info})", file=sys.stderr)
                self.send_log(f"⚠️ 未找到已加入群組的帳號，使用 {phone[:4]}**** (角色: {role_info})", "warning")
                self.send_log(f"💡 如提取失敗，請先使用該帳號加入此群組", "info")
        
        self.send_log(f"🔍 開始提取成員: {chat_id} (帳號: {phone})", "info")
        
        # 設置客戶端
        member_extraction_service.set_clients(self.telegram_manager.clients)
        member_extraction_service.set_event_callback(self.send_event)
        
        # 🆕 清除結果緩存（強制重新提取，不返回舊數據）
        member_extraction_service.clear_result_cache(str(chat_id))
        # 也清除 -100 前綴格式的緩存
        if isinstance(chat_id, int) and chat_id > 0:
            member_extraction_service.clear_result_cache(str(int(f"-100{chat_id}")))
        
        # 🆕 預驗證：快速檢查帳號是否可以訪問此群組
        pre_check_passed = False
        if phone and phone in self.telegram_manager.clients:
            test_client = self.telegram_manager.clients[phone]
            if test_client and test_client.is_connected:
                try:
                    # 快速 get_chat 驗證（member_extraction_service 內部會處理 -100 前綴）
                    test_target = chat_id
                    try:
                        await test_client.get_chat(test_target)
                        pre_check_passed = True
                    except Exception as pre_err:
                        pre_err_str = str(pre_err)
                        if 'PEER_ID_INVALID' in pre_err_str or 'ChannelInvalid' in pre_err_str:
                            # 嘗試 -100 前綴
                            if isinstance(test_target, int) and test_target > 1000000000:
                                try:
                                    alt_target = int(f"-100{test_target}")
                                    await test_client.get_chat(alt_target)
                                    pre_check_passed = True
                                    chat_id = alt_target  # 更新 chat_id
                                    self.send_log(f"✓ 使用超級群組 ID 格式: {alt_target}", "info")
                                except Exception:
                                    pass
                        elif 'PEER_ID_INVALID' not in pre_err_str:
                            # 其他非 PeerIdInvalid 錯誤，可能仍然可用
                            pre_check_passed = True
                    
                    if not pre_check_passed:
                        # 當前帳號無法訪問，嘗試找一個可以的
                        self.send_log(f"⚠️ 帳號 {phone[:4]}**** 無法訪問群組，嘗試其他帳號...", "warning")
                        for alt_phone, alt_client in self.telegram_manager.clients.items():
                            if alt_phone == phone or not alt_client or not alt_client.is_connected:
                                continue
                            try:
                                test_target_2 = chat_id if isinstance(chat_id, int) and chat_id < 0 else (int(f"-100{chat_id}") if isinstance(chat_id, int) and chat_id > 1000000000 else chat_id)
                                await alt_client.get_chat(test_target_2)
                                phone = alt_phone
                                chat_id = test_target_2
                                pre_check_passed = True
                                self.send_log(f"✓ 切換到帳號 {phone[:4]}**** (可訪問群組)", "info")
                                break
                            except Exception:
                                continue
                except Exception as pre_check_err:
                    print(f"[Backend] Pre-check error (non-fatal): {pre_check_err}", file=sys.stderr)
        
        # 發送開始事件
        self.send_event("members-extraction-progress", {
            "resourceId": resource_id,
            "status": "starting",
            "extracted": 0,
            "total": 0
        })
        
        # 🆕 智能重試機制 — 現在會嘗試不同帳號 + 自動 -100 前綴（在 extraction_service 層處理）
        MAX_RETRIES = 3
        RETRY_DELAYS = [2, 4, 6]
        result = None
        last_error = None
        tried_phones = {phone}  # 記錄已嘗試的帳號，避免重複
        current_phone = phone
        
        for attempt in range(MAX_RETRIES):
            try:
                if attempt > 0:
                    self.send_event("members-extraction-progress", {
                        "resourceId": resource_id,
                        "status": "retrying",
                        "message": f"正在重試 ({attempt + 1}/{MAX_RETRIES})...",
                        "extracted": 0,
                        "total": 0
                    })
                    await asyncio.sleep(RETRY_DELAYS[attempt - 1])
                    
                    # 🆕 第 2 次及之後：嘗試切換到其他帳號
                    if self.telegram_manager.clients:
                        for alt_phone, alt_client in self.telegram_manager.clients.items():
                            if alt_phone not in tried_phones and alt_client and alt_client.is_connected:
                                self.send_log(f"🔄 切換帳號: {current_phone[:4]}**** → {alt_phone[:4]}****", "info")
                                current_phone = alt_phone
                                tried_phones.add(alt_phone)
                                break
                
                # 提取成員（member_extraction_service 內部已自動處理 -100 前綴）
                result = await member_extraction_service.extract_members(
                    chat_id=chat_id,
                    phone=current_phone,
                    limit=limit,
                    filter_bots=filter_bots,
                    filter_offline=filter_offline,
                    online_status=online_status,
                    save_to_db=True
                )
                
                if result.get('success'):
                    if attempt > 0:
                        self.send_log(f"✓ 第 {attempt + 1} 次重試成功 (帳號: {current_phone[:4]}****)", "success")
                    break
                
                error_code = result.get('error_code', '')
                if error_code in ['PEER_ID_INVALID', 'NOT_PARTICIPANT', 'USER_NOT_PARTICIPANT', 'CHANNEL_PRIVATE']:
                    last_error = result.get('error')
                    print(f"[Backend] Retryable error: {error_code}, attempt {attempt + 1}/{MAX_RETRIES}, phone={current_phone}", file=sys.stderr)
                    
                    if attempt >= MAX_RETRIES - 1:
                        # 所有重試都失敗 — 提供精確的錯誤信息
                        actual_reason = {
                            'PEER_ID_INVALID': '當前帳號未加入此群組，或群組 ID 無法解析',
                            'NOT_PARTICIPANT': '帳號不是此群組的成員',
                            'USER_NOT_PARTICIPANT': '帳號不是此群組的成員',
                            'CHANNEL_PRIVATE': '這是私有群組，需要先加入'
                        }.get(error_code, '帳號無法訪問此群組')
                        
                        result['error'] = f"提取失敗：{actual_reason}"
                        result['error_code'] = 'E4001_NOT_SYNCED'
                        result['error_details'] = {
                            'code': 'E4001',
                            'reason': actual_reason,
                            'suggestion': '請先使用「加入群組」功能，確保帳號已加入此群組後再提取',
                            'action': 'auto_join',
                            'retry_after_seconds': 10,
                            'attempts': attempt + 1,
                            'tried_phones': list(tried_phones),
                            'can_auto_join': True
                        }
                        break
                else:
                    # 其他錯誤不重試 — 附加結構化錯誤碼
                    if not result.get('error_code'):
                        err_msg = result.get('error', '')
                        if 'CHAT_ADMIN_REQUIRED' in err_msg or '管理員' in err_msg:
                            result['error_code'] = 'E4002_ADMIN_REQUIRED'
                            result['error_details'] = {
                                'code': 'E4002',
                                'reason': '群組限制了成員列表訪問權限',
                                'suggestion': '可嘗試使用「監控群組消息」方式收集活躍用戶',
                                'action': 'suggest_monitor'
                            }
                        elif 'FLOOD' in err_msg.upper():
                            actual_wait = 120
                            try:
                                from flood_wait_handler import flood_handler as _fh
                                parsed_wait = _fh.get_wait_time_from_error(Exception(err_msg))
                                if parsed_wait:
                                    actual_wait = parsed_wait
                                    _fh.record_flood_wait(current_phone, actual_wait)
                            except Exception:
                                pass
                            result['error_code'] = 'E4003_RATE_LIMITED'
                            result['error_details'] = {
                                'code': 'E4003',
                                'reason': 'Telegram 速率限制，請求過於頻繁',
                                'suggestion': f'請等待 {actual_wait} 秒後再試',
                                'action': 'retry_later',
                                'retry_after_seconds': actual_wait
                            }
                    break
                    
            except Exception as retry_err:
                last_error = str(retry_err)
                print(f"[Backend] Extraction attempt {attempt + 1} failed: {retry_err}", file=sys.stderr)
                if attempt >= MAX_RETRIES - 1:
                    raise
        
        # 如果所有重試都失敗且沒有結果
        if result is None:
            result = {
                'success': False,
                'error': last_error or '提取失敗',
                'members': [],
                'extracted': 0
            }
        
        # 🆕 Phase2: 自動加入並重試 — 當所有帳號都返回 PEER_ID_INVALID 時
        if not result.get('success') and result.get('error_code') == 'E4001_NOT_SYNCED':
            can_join = bool(username or (telegram_id and str(telegram_id).lstrip('-').isdigit()))
            if can_join:
                self.send_log(f"🚀 所有帳號均無法訪問群組，嘗試自動加入...", "info")
                self.send_event("members-extraction-progress", {
                    "resourceId": resource_id,
                    "status": "auto_joining",
                    "message": "帳號未加入群組，正在自動加入...",
                    "extracted": 0, "total": 0
                })
                
                try:
                    # 構建加入 URL
                    if username:
                        join_url = f"https://t.me/{username.lstrip('@')}"
                    else:
                        join_url = str(telegram_id)
                    
                    # 選擇最佳帳號加入
                    from domain.groups.handlers_impl import select_best_account
                    join_phone = await select_best_account(self.telegram_manager, db, operation='join')
                    if not join_phone:
                        join_phone = current_phone
                    
                    # 加入群組
                    join_result = await self.telegram_manager.join_group(join_phone, join_url)
                    
                    if join_result.get('success') or 'already' in str(join_result.get('error', '')).lower():
                        self.send_log(f"✅ 帳號 {join_phone[:4]}**** 已加入群組", "success")
                        
                        # 更新 discovered_resources
                        try:
                            from database import db as _join_db
                            await _join_db.connect()
                            if resource_id:
                                tg_id = str(join_result.get('chat_id', '')) or str(telegram_id or '')
                                await _join_db.execute(
                                    """UPDATE discovered_resources 
                                       SET status = 'joined', joined_by_phone = ?, joined_at = CURRENT_TIMESTAMP,
                                           telegram_id = COALESCE(telegram_id, ?)
                                       WHERE id = ?""",
                                    (join_phone, tg_id, resource_id)
                                )
                        except Exception as db_err:
                            print(f"[Backend] Auto-join DB update error: {db_err}", file=sys.stderr)
                        
                        # 等待 Telegram 同步
                        self.send_log(f"⏳ 等待 5 秒讓 Telegram 同步...", "info")
                        await asyncio.sleep(5)
                        
                        # 最終重試提取
                        self.send_event("members-extraction-progress", {
                            "resourceId": resource_id,
                            "status": "retrying",
                            "message": "加入成功，正在重新提取...",
                            "extracted": 0, "total": 0
                        })
                        
                        final_result = await member_extraction_service.extract_members(
                            chat_id=chat_id,
                            phone=join_phone,
                            limit=limit,
                            filter_bots=filter_bots,
                            filter_offline=filter_offline,
                            online_status=online_status,
                            save_to_db=True
                        )
                        
                        if final_result.get('success'):
                            result = final_result
                            current_phone = join_phone
                            self.send_log(f"✅ 自動加入後提取成功！", "success")
                        else:
                            # 加入成功但提取仍失敗，更新錯誤信息
                            result['error'] = f"已加入群組但提取仍失敗：{final_result.get('error', '未知錯誤')}"
                            result['error_details']['suggestion'] = '帳號已成功加入群組，請等待 30 秒後手動重試'
                            result['error_details']['action'] = 'retry_later'
                            result['error_details']['retry_after_seconds'] = 30
                            self.send_log(f"⚠️ 已加入但提取失敗：{final_result.get('error_code', '')}", "warning")
                    else:
                        join_error = join_result.get('error', '加入失敗')
                        self.send_log(f"❌ 自動加入失敗: {join_error}", "error")
                        result['error_details']['suggestion'] = f'自動加入失敗（{join_error}），請手動加入後重試'
                        result['error_details']['can_auto_join'] = False
                        
                except Exception as auto_join_err:
                    print(f"[Backend] Auto-join error: {auto_join_err}", file=sys.stderr)
                    self.send_log(f"❌ 自動加入異常: {auto_join_err}", "error")
        
        if result['success']:
            members = result.get('members', [])
            
            # 應用額外的過濾器
            filtered_members = []
            for member in members:
                # 華人過濾
                if chinese_only:
                    name = (member.get('first_name', '') or '') + (member.get('last_name', '') or '')
                    bio = member.get('bio', '') or ''
                    # 檢查是否有中文字符
                    import re
                    if not re.search(r'[\u4e00-\u9fff]', name + bio):
                        continue
                
                # Premium 過濾
                if premium_only and not member.get('is_premium'):
                    continue
                
                # 用戶名過濾
                if has_username and not member.get('username'):
                    continue
                
                filtered_members.append(member)
            
            result['members'] = filtered_members
            result['extracted'] = len(filtered_members)
            
            self.send_log(f"✅ 提取完成: {len(filtered_members)} 成員 (總計: {len(members)})", "success")
            
            # 🆕 Phase3: 大群組上限提醒 — Telegram API 最多返回 10,000 成員
            total_in_group = result.get('total_members', 0)
            if total_in_group > 10000:
                extracted_count = len(filtered_members)
                self.send_log(
                    f"⚠️ 此群組有 {total_in_group:,} 成員，Telegram 限制最多提取 10,000。"
                    f"已提取 {extracted_count:,}，建議使用「監控群組消息」方式持續收集活躍用戶。",
                    "warning"
                )
                result['limit_warning'] = {
                    'total_in_group': total_in_group,
                    'api_limit': 10000,
                    'extracted': extracted_count,
                    'suggestion': 'monitor_messages',
                    'message': f'此群組有 {total_in_group:,} 成員，Telegram API 限制最多提取 10,000。建議結合「監控消息」收集更多活躍用戶。'
                }
            
            # 🆕 Phase3: 增量同步到 unified_contacts（替代全表掃描）
            sync_stats = {'new': 0, 'updated': 0, 'duplicate': 0}
            try:
                from unified_contacts import get_unified_contacts_manager
                from database import db as sync_db
                await sync_db.connect()
                manager = get_unified_contacts_manager(sync_db)
                
                # 使用增量同步 — 只處理剛提取的成員（性能提升 10-100x）
                chat_title = result.get('chat_title', group_name or '')
                sync_stats = await manager.sync_members_batch(
                    members=filtered_members,
                    source_chat_id=str(chat_id or telegram_id or ''),
                    source_chat_title=chat_title
                )
                print(f"[Backend] Incremental sync: {sync_stats}", file=sys.stderr)
                
                if sync_stats['new'] > 0:
                    self.send_log(f"✅ 資源中心: 新增 {sync_stats['new']}，更新 {sync_stats['updated']}", "info")
                elif sync_stats['updated'] > 0:
                    self.send_log(f"♻️ 資源中心: 更新 {sync_stats['updated']} 個已有聯繫人", "info")
                
                self.send_event("unified-contacts:updated", {
                    "reason": "extract-members",
                    "new": sync_stats.get('new', 0),
                    "updated": sync_stats.get('updated', 0),
                    "total_extracted": len(filtered_members)
                })
            except Exception as sync_err:
                print(f"[Backend] Incremental sync error: {sync_err}", file=sys.stderr)
            
            # 🆕 Phase3: 記錄提取歷史到 member_extraction_logs
            try:
                from database import db as log_db
                await log_db.connect()
                await log_db.execute('''
                    INSERT INTO member_extraction_logs 
                    (chat_id, chat_title, total_members, extracted_count, online_count, 
                     recently_count, new_count, updated_count, duration_ms, account_phone, status)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                ''', (
                    str(chat_id or telegram_id or ''),
                    result.get('chat_title', group_name or ''),
                    result.get('total_members', 0),
                    len(filtered_members),
                    result.get('online_count', 0),
                    result.get('recently_count', 0),
                    sync_stats.get('new', 0),
                    sync_stats.get('updated', 0),
                    0,  # duration_ms — 可後續補充
                    current_phone if 'current_phone' in locals() else phone,
                    'success'
                ))
                print(f"[Backend] Extraction log recorded", file=sys.stderr)
            except Exception as log_err:
                print(f"[Backend] Extraction log error: {log_err}", file=sys.stderr)
        else:
            self.send_log(f"❌ 提取失敗: {result['error']}", "error")
        
        # 🆕 Phase3: 查詢上次提取記錄（用於前端顯示增量信息）
        last_extraction = None
        if result.get('success'):
            try:
                from database import db as hist_db
                await hist_db.connect()
                chat_id_str = str(chat_id or telegram_id or '')
                last_log = await hist_db.fetch_one(
                    """SELECT extracted_count, new_count, created_at 
                       FROM member_extraction_logs 
                       WHERE chat_id = ? AND status = 'success'
                       ORDER BY created_at DESC LIMIT 1 OFFSET 1""",
                    (chat_id_str,)
                )
                if last_log:
                    last_extraction = {
                        "lastCount": last_log.get('extracted_count') if hasattr(last_log, 'get') else last_log[0],
                        "lastNewCount": last_log.get('new_count') if hasattr(last_log, 'get') else last_log[1],
                        "lastTime": last_log.get('created_at') if hasattr(last_log, 'get') else last_log[2]
                    }
            except Exception:
                pass
        
        # 🆕 Phase5: 智能分析 — 分析群組特徵並生成建議
        insights = None
        if result.get('success') and 'filtered_members' in dir() and filtered_members:
            try:
                import re as _re
                total = len(filtered_members)
                online_cnt = sum(1 for m in filtered_members if m.get('online_status') in ('online', 'recently'))
                premium_cnt = sum(1 for m in filtered_members if m.get('is_premium'))
                username_cnt = sum(1 for m in filtered_members if m.get('username'))
                bot_cnt = sum(1 for m in filtered_members if m.get('is_bot'))
                chinese_cnt = 0
                for m in filtered_members:
                    name = (m.get('first_name', '') or '') + (m.get('last_name', '') or '')
                    if _re.search(r'[\u4e00-\u9fff]', name):
                        chinese_cnt += 1
                
                # 評級分布
                level_dist = {'S': 0, 'A': 0, 'B': 0, 'C': 0, 'D': 0}
                for m in filtered_members:
                    lv = m.get('value_level', 'C')
                    if lv in level_dist:
                        level_dist[lv] += 1
                
                high_value = level_dist['S'] + level_dist['A']
                
                # 生成建議
                recommendations = []
                if total > 0:
                    chinese_pct = round(chinese_cnt / total * 100)
                    premium_pct = round(premium_cnt / total * 100)
                    online_pct = round(online_cnt / total * 100)
                    username_pct = round(username_cnt / total * 100)
                    
                    if chinese_pct >= 50:
                        recommendations.append(f"🇨🇳 {chinese_pct}% 華人用戶，適合中文內容營銷")
                    elif chinese_pct >= 20:
                        recommendations.append(f"🌏 {chinese_pct}% 華人用戶，建議中英雙語推送")
                    
                    if premium_pct >= 30:
                        recommendations.append(f"⭐ {premium_pct}% Premium 用戶，群組質量較高")
                    
                    if online_pct >= 40:
                        recommendations.append(f"🟢 {online_pct}% 近期活躍，建議立即發送營銷消息")
                    elif online_pct < 15:
                        recommendations.append(f"⚠️ 僅 {online_pct}% 近期活躍，群組活躍度較低")
                    
                    if username_pct < 30:
                        recommendations.append(f"📛 僅 {username_pct}% 有用戶名，私信觸達率有限")
                    
                    if high_value >= 10:
                        recommendations.append(f"💎 {high_value} 個 S/A 級高價值用戶，建議優先觸達")
                    
                    if bot_cnt > total * 0.1:
                        recommendations.append(f"🤖 {round(bot_cnt / total * 100)}% 是 Bot，建議開啟排除 Bot 篩選")
                
                insights = {
                    "chinesePercent": round(chinese_cnt / max(total, 1) * 100),
                    "premiumPercent": round(premium_cnt / max(total, 1) * 100),
                    "onlinePercent": round(online_cnt / max(total, 1) * 100),
                    "usernamePercent": round(username_cnt / max(total, 1) * 100),
                    "botPercent": round(bot_cnt / max(total, 1) * 100),
                    "highValueCount": high_value,
                    "valueLevelDistribution": level_dist,
                    "recommendations": recommendations
                }
            except Exception as insight_err:
                print(f"[Backend] Insight analysis error: {insight_err}", file=sys.stderr)
        
        # 發送完成事件 — 🆕 Phase5: 包含智能分析
        extraction_event = {
            "resourceId": resource_id,
            "telegramId": str(telegram_id) if telegram_id else None,
            "success": result.get('success', False),
            "members": result.get('members', []),
            "extracted": result.get('extracted', 0),
            "total": result.get('total', 0),
            "onlineCount": result.get('online_count', 0),
            "error": result.get('error'),
            "error_code": result.get('error_code'),
            "error_details": result.get('error_details'),
            "limit_warning": result.get('limit_warning'),
            "usedPhone": current_phone if 'current_phone' in locals() else phone,
            "syncStats": {
                "new": sync_stats.get('new', 0) if 'sync_stats' in locals() else 0,
                "updated": sync_stats.get('updated', 0) if 'sync_stats' in locals() else 0,
                "duplicate": sync_stats.get('duplicate', 0) if 'sync_stats' in locals() else 0
            } if result.get('success') else None,
            "lastExtraction": last_extraction,
            # 🆕 Phase5: 智能分析
            "insights": insights,
            # 🆕 Phase5: 配額信息
            "dailyQuota": daily_quota if 'daily_quota' in locals() else None
        }
        self.send_event("members-extracted", extraction_event)
        
    except Exception as e:
        import traceback
        traceback.print_exc(file=sys.stderr)
        self.send_log(f"❌ 提取成員失敗: {e}", "error")
        self.send_event("members-extracted", {
            "resourceId": payload.get('resourceId'),
            "success": False,
            "error": str(e),
            "members": [],
            "extracted": 0,
            "total": 0
        })


async def handle_extract_active_users(self, payload: Dict[str, Any]):
    """
    Phase4: 從消息歷史中提取活躍用戶
    
    與 extract-members 互補的提取方式：
    - extract-members: 使用 get_chat_members API (上限 10,000)
    - extract-active-users: 遍歷消息歷史，發現活躍發言者
    
    適用場景：
    1. 群組超過 10,000 成員
    2. 管理員限制了成員列表
    3. 需要按活躍度篩選高價值用戶
    """
    try:
        resource_id = payload.get('resourceId')
        chat_id = payload.get('chatId') or payload.get('telegramId')
        username = payload.get('username')
        phone = payload.get('phone')
        message_limit = payload.get('messageLimit', 2000)
        
        # 構建 chat_id
        effective_chat_id = chat_id
        if not effective_chat_id and username:
            effective_chat_id = f"@{username.lstrip('@')}"
        
        if not effective_chat_id:
            self.send_event("active-users-extracted", {
                "resourceId": resource_id,
                "success": False,
                "error": "無法確定群組標識",
                "members": [],
                "extracted": 0
            })
            return
        
        # 獲取手機號
        if not phone:
            from database import db as _db
            await _db.connect()
            if resource_id:
                resource = await _db.fetch_one(
                    "SELECT joined_by_phone FROM discovered_resources WHERE id = ?",
                    (resource_id,)
                )
                if resource:
                    phone = resource.get('joined_by_phone') if hasattr(resource, 'get') else resource[0]
        
        self.send_log(f"🔍 從消息歷史中提取活躍用戶: {effective_chat_id}", "info")
        self.send_event("active-users-extraction-progress", {
            "resourceId": resource_id,
            "status": "starting",
            "message": f"開始掃描最近 {message_limit} 條消息..."
        })
        
        # 設置客戶端
        member_extraction_service.set_clients(self.telegram_manager.clients)
        member_extraction_service.set_event_callback(self.send_event)
        
        result = await member_extraction_service.extract_active_from_history(
            chat_id=effective_chat_id,
            phone=phone,
            message_limit=message_limit,
            save_to_db=True
        )
        
        if result['success']:
            new_users = [m for m in result.get('members', []) if m.get('is_new')]
            self.send_log(
                f"✅ 活躍用戶提取完成: 掃描 {result['messages_scanned']} 條消息，"
                f"發現 {result['unique_users']} 用戶 (新增 {len(new_users)})",
                "success"
            )
            
            # 自動同步到統一聯繫人
            try:
                from unified_contacts import get_unified_contacts_manager
                from database import db as sync_db
                await sync_db.connect()
                manager = get_unified_contacts_manager(sync_db)
                sync_stats = await manager.sync_from_sources()
                self.send_event("unified-contacts:updated", {
                    "reason": "extract-active-users",
                    "synced": sync_stats.get('synced', 0),
                    "updated": sync_stats.get('updated', 0)
                })
            except Exception as sync_err:
                print(f"[Backend] Auto-sync after active extraction: {sync_err}", file=sys.stderr)
        else:
            self.send_log(f"❌ 活躍用戶提取失敗: {result.get('error')}", "error")
        
        self.send_event("active-users-extracted", {
            "resourceId": resource_id,
            "success": result.get('success', False),
            "method": "history",
            "members": result.get('members', []),
            "extracted": result.get('extracted', 0),
            "unique_users": result.get('unique_users', 0),
            "messages_scanned": result.get('messages_scanned', 0),
            "new_members": result.get('new_members', 0),
            "error": result.get('error')
        })
        
    except Exception as e:
        import traceback
        traceback.print_exc(file=sys.stderr)
        self.send_log(f"❌ 活躍用戶提取失敗: {e}", "error")
        self.send_event("active-users-extracted", {
            "resourceId": payload.get('resourceId'),
            "success": False,
            "error": str(e),
            "members": [],
            "extracted": 0
        })


async def handle_get_extracted_members(self, payload: Dict[str, Any]):
    """獲取已提取的成員列表 - 🆕 P3 優化：支持完整分頁"""
    import time
    start_time = time.time()
    print(f"[Backend] handle_get_extracted_members started, payload: {payload}", file=sys.stderr)
    
    try:
        online_only = payload.get('onlineOnly', False)
        min_value_level = payload.get('minValueLevel')
        source_chat_id = payload.get('sourceChatId')
        not_contacted = payload.get('notContacted', False)
        limit = payload.get('limit', 100)
        offset = payload.get('offset', 0)
        page = payload.get('page', 1)
        page_size = payload.get('pageSize', limit)
        
        # 🆕 P3：支持頁碼方式分頁
        if page > 1:
            offset = (page - 1) * page_size
            limit = page_size
        
        print(f"[Backend] Fetching members with limit={limit}, offset={offset}...", file=sys.stderr)
        
        # 🆕 P3：獲取總數（用於分頁）
        total_count = await member_extraction_service.count_members_filtered(
            online_only=online_only,
            min_value_level=min_value_level,
            source_chat_id=source_chat_id,
            not_contacted=not_contacted
        )
        
        members = await member_extraction_service.get_members(
            online_only=online_only,
            min_value_level=min_value_level,
            source_chat_id=source_chat_id,
            not_contacted=not_contacted,
            limit=limit,
            offset=offset
        )
        
        elapsed = time.time() - start_time
        print(f"[Backend] Fetched {len(members)} members (total: {total_count}) in {elapsed:.2f}s", file=sys.stderr)
        
        # 🆕 P3：返回分頁信息
        total_pages = (total_count + page_size - 1) // page_size if page_size > 0 else 1
        
        self.send_event("extracted-members-list", {
            "success": True,
            "members": members,
            "count": len(members),
            # 🆕 P3：分頁元數據
            "pagination": {
                "total": total_count,
                "page": page,
                "pageSize": page_size,
                "totalPages": total_pages,
                "hasMore": offset + len(members) < total_count
            }
        })
        print(f"[Backend] Sent extracted-members-list event with {len(members)} members", file=sys.stderr)
        
    except Exception as e:
        import traceback
        traceback.print_exc(file=sys.stderr)
        self.send_log(f"❌ 獲取成員列表失敗: {e}", "error")
        self.send_event("extracted-members-list", {
            "success": False,
            "error": str(e)
        })


async def handle_get_member_stats(self, payload: Dict[str, Any]):
    """獲取成員統計"""
    try:
        source_chat_id = payload.get('sourceChatId')
        
        stats = await member_extraction_service.count_members(source_chat_id)
        
        self.send_event("member-stats", {
            "success": True,
            **stats
        })
        
    except Exception as e:
        self.send_log(f"❌ 獲取成員統計失敗: {e}", "error")
        self.send_event("member-stats", {
            "success": False,
            "error": str(e)
        })


async def handle_get_online_members(self, payload: Dict[str, Any]):
    """獲取在線成員"""
    try:
        limit = payload.get('limit', 100)
        
        members = await member_extraction_service.get_online_members(limit)
        
        self.send_event("online-members-list", {
            "success": True,
            "members": members,
            "count": len(members)
        })
        
    except Exception as e:
        self.send_log(f"❌ 獲取在線成員失敗: {e}", "error")
        self.send_event("online-members-list", {
            "success": False,
            "error": str(e)
        })


async def handle_update_member(self, payload: Dict[str, Any]):
    """更新成員信息"""
    try:
        user_id = payload.get('userId')
        updates = payload.get('updates', {})
        
        if not user_id:
            raise ValueError("用戶 ID 不能為空")
        
        # 構建更新語句
        set_clauses = []
        params = []
        
        allowed_fields = ['tags', 'notes', 'contacted', 'contacted_at', 'response_status', 'converted', 'value_level']
        
        for field, value in updates.items():
            if field in allowed_fields:
                set_clauses.append(f"{field} = ?")
                params.append(value if not isinstance(value, bool) else (1 if value else 0))
        
        if not set_clauses:
            self.send_event("member-updated", {
                "success": True,
                "userId": user_id,
                "message": "無需更新"
            })
            return
        
        # 添加更新時間
        set_clauses.append("updated_at = ?")
        params.append(datetime.now().isoformat())
        
        # 添加 user_id 參數
        params.append(user_id)
        
        query = f"UPDATE extracted_members SET {', '.join(set_clauses)} WHERE user_id = ?"
        
        await db.execute(query, tuple(params))
        
        self.send_log(f"✅ 更新成員 {user_id} 成功", "success")
        self.send_event("member-updated", {
            "success": True,
            "userId": user_id
        })
        
    except Exception as e:
        self.send_log(f"❌ 更新成員失敗: {e}", "error")
        self.send_event("member-updated", {
            "success": False,
            "error": str(e)
        })


# ==================== P2 優化：統計與背景提取 ====================

async def handle_get_extraction_stats(self, payload: Dict[str, Any]):
    """獲取提取統計信息"""
    import sys
    print(f"[Backend] handle_get_extraction_stats called", file=sys.stderr)
    
    try:
        stats = member_extraction_service.get_stats()
        
        self.send_event("extraction-stats", {
            "success": True,
            **stats
        })
        
    except Exception as e:
        import traceback
        traceback.print_exc(file=sys.stderr)
        self.send_event("extraction-stats", {
            "success": False,
            "error": str(e)
        })


async def handle_start_background_extraction(self, payload: Dict[str, Any]):
    """啟動背景提取"""
    import sys
    print(f"[Backend] handle_start_background_extraction called: {payload}", file=sys.stderr)
    
    try:
        chat_id = payload.get('chatId') or payload.get('telegramId')
        phone = payload.get('phone')
        limit = payload.get('limit', 100)
        filters = payload.get('filters', {})
        
        if not chat_id:
            raise ValueError("群組 ID 不能為空")
        
        # 設置客戶端
        member_extraction_service.set_clients(self.telegram_manager.clients)
        member_extraction_service.set_event_callback(self.send_event)
        
        # 啟動背景任務
        task_id = await member_extraction_service.start_background_extraction(
            chat_id=chat_id,
            phone=phone,
            limit=limit,
            filter_bots=filters.get('bots', True),
            online_status=filters.get('onlineStatus', 'all')
        )
        
        self.send_log(f"🔄 背景提取已啟動: {task_id}", "info")
        self.send_event("background-extraction-started", {
            "success": True,
            "taskId": task_id,
            "chatId": chat_id
        })
        
    except Exception as e:
        import traceback
        traceback.print_exc(file=sys.stderr)
        self.send_log(f"❌ 啟動背景提取失敗: {e}", "error")
        self.send_event("background-extraction-started", {
            "success": False,
            "error": str(e)
        })


async def handle_clear_extraction_cache(self, payload: Dict[str, Any]):
    """清除提取緩存"""
    try:
        chat_id = payload.get('chatId')
        member_extraction_service.clear_result_cache(chat_id)
        
        self.send_event("cache-cleared", {
            "success": True,
            "chatId": chat_id
        })
        
    except Exception as e:
        self.send_event("cache-cleared", {
            "success": False,
            "error": str(e)
        })


# ==================== P4 優化：數據導出與管理 ====================

async def handle_export_members(self, payload: Dict[str, Any]):
    """導出成員數據"""
    import sys
    print(f"[Backend] handle_export_members called: {payload}", file=sys.stderr)
    
    try:
        format_type = payload.get('format', 'csv')  # csv 或 json
        filters = payload.get('filters', {})
        
        if format_type == 'json':
            content = await member_extraction_service.export_members_json(filters)
            filename = f"members_export_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
        else:
            content = await member_extraction_service.export_members_csv(filters)
            filename = f"members_export_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
        
        self.send_log(f"✅ 導出完成: {filename}", "success")
        self.send_event("members-exported", {
            "success": True,
            "content": content,
            "filename": filename,
            "format": format_type
        })
        
    except Exception as e:
        import traceback
        traceback.print_exc(file=sys.stderr)
        self.send_log(f"❌ 導出失敗: {e}", "error")
        self.send_event("members-exported", {
            "success": False,
            "error": str(e)
        })


async def handle_join_and_extract(self, payload: Dict[str, Any]):
    """
    🆕 Phase3: 一鍵加入群組並提取成員
    
    前端只需發送一個命令，後端自動完成：
    1. 加入群組
    2. 等待 Telegram 同步
    3. 提取成員
    4. 同步到 unified_contacts
    """
    import sys
    print(f"[Backend] handle_join_and_extract called: {list(payload.keys())}", file=sys.stderr)
    
    resource_id = payload.get('resourceId') or payload.get('groupId')
    telegram_id = payload.get('telegramId')
    username = payload.get('username')
    phone = payload.get('phone')
    group_name = payload.get('groupName') or payload.get('groupTitle') or ''
    limit = payload.get('limit', 200)
    
    try:
        # Step 1: 構建加入 URL
        if username:
            join_url = f"https://t.me/{username.lstrip('@')}"
        elif telegram_id:
            join_url = str(telegram_id)
        else:
            self.send_event("members-extracted", {
                "resourceId": resource_id,
                "success": False,
                "error": "缺少群組標識（username 或 telegramId）",
                "members": [], "extracted": 0, "total": 0
            })
            return
        
        # Step 2: 選擇帳號
        if not phone:
            from database import db as _jae_db
            await _jae_db.connect()
            from domain.groups.handlers_impl import select_best_account
            phone = await select_best_account(self.telegram_manager, _jae_db, operation='join')
        
        if not phone:
            self.send_event("members-extracted", {
                "resourceId": resource_id,
                "success": False,
                "error": "沒有可用的在線帳號",
                "members": [], "extracted": 0, "total": 0
            })
            return
        
        # Step 3: 加入群組
        self.send_event("members-extraction-progress", {
            "resourceId": resource_id,
            "status": "joining",
            "message": f"正在加入群組 {group_name or username or ''}...",
            "extracted": 0, "total": 0
        })
        
        join_result = await self.telegram_manager.join_group(phone, join_url)
        
        if not join_result.get('success') and 'already' not in str(join_result.get('error', '')).lower():
            self.send_event("members-extracted", {
                "resourceId": resource_id,
                "success": False,
                "error": f"加入群組失敗: {join_result.get('error', '未知錯誤')}",
                "members": [], "extracted": 0, "total": 0
            })
            return
        
        # Step 4: 更新數據庫
        actual_chat_id = join_result.get('chat_id', telegram_id)
        try:
            from database import db as _jae_db2
            await _jae_db2.connect()
            if resource_id:
                await _jae_db2.execute(
                    """UPDATE discovered_resources 
                       SET status = 'joined', joined_by_phone = ?, joined_at = CURRENT_TIMESTAMP,
                           telegram_id = COALESCE(telegram_id, ?)
                       WHERE id = ?""",
                    (phone, str(actual_chat_id or ''), resource_id)
                )
        except Exception as db_err:
            print(f"[Backend] join-and-extract DB update error: {db_err}", file=sys.stderr)
        
        self.send_log(f"✅ 已加入群組 {group_name}", "success")
        
        # Step 5: 等待同步
        self.send_event("members-extraction-progress", {
            "resourceId": resource_id,
            "status": "syncing",
            "message": "已加入群組，等待 Telegram 同步...",
            "extracted": 0, "total": 0
        })
        import asyncio
        await asyncio.sleep(5)
        
        # Step 6: 調用 extract-members（復用已有邏輯）
        extract_payload = {
            'resourceId': resource_id,
            'telegramId': str(actual_chat_id or telegram_id or ''),
            'username': username,
            'phone': phone,
            'groupName': group_name,
            'limit': limit,
            'chatId': str(actual_chat_id or telegram_id or '')
        }
        # 合併前端傳入的額外參數（filters 等）
        for key in ['filters', 'autoSave', 'skipDuplicates']:
            if key in payload:
                extract_payload[key] = payload[key]
        
        await handle_extract_members(self, extract_payload)
        
    except Exception as e:
        import traceback
        traceback.print_exc(file=sys.stderr)
        self.send_log(f"❌ 加入並提取失敗: {e}", "error")
        self.send_event("members-extracted", {
            "resourceId": resource_id,
            "success": False,
            "error": str(e),
            "members": [], "extracted": 0, "total": 0
        })


async def handle_batch_extract_members(self, payload: Dict[str, Any]):
    """
    🆕 Phase4: 批量提取多個群組的成員
    
    串行執行避免 FloodWait，每個群組完成後發送進度事件。
    前端已有 openBatchMemberExtractDialog() 發送此命令。
    """
    import sys
    print(f"[Backend] handle_batch_extract_members called", file=sys.stderr)
    
    resource_ids = payload.get('resourceIds', [])
    limit_per_group = payload.get('limit', 100)
    safe_mode = payload.get('safeMode', True)
    
    if not resource_ids:
        self.send_event("batch-members-extracted", {
            "success": False, "error": "未提供群組 ID 列表"
        })
        return
    
    total_groups = len(resource_ids)
    completed = 0
    failed = 0
    total_members = 0
    results = []
    
    self.send_log(f"🚀 開始批量提取 {total_groups} 個群組的成員", "info")
    self.send_event("batch-extraction-progress", {
        "status": "starting",
        "totalGroups": total_groups,
        "completed": 0,
        "currentGroup": "",
        "totalMembers": 0
    })
    
    from database import db as batch_db
    await batch_db.connect()
    
    for i, rid in enumerate(resource_ids):
        try:
            # 查詢群組信息
            resource = await batch_db.fetch_one(
                "SELECT id, telegram_id, username, title, joined_by_phone, status FROM discovered_resources WHERE id = ?",
                (rid,)
            )
            
            if not resource:
                self.send_log(f"⚠️ [{i+1}/{total_groups}] 群組 ID={rid} 不存在，跳過", "warning")
                failed += 1
                continue
            
            title = resource.get('title') if hasattr(resource, 'get') else resource[3]
            telegram_id = resource.get('telegram_id') if hasattr(resource, 'get') else resource[1]
            username = resource.get('username') if hasattr(resource, 'get') else resource[2]
            phone = resource.get('joined_by_phone') if hasattr(resource, 'get') else resource[4]
            status = resource.get('status') if hasattr(resource, 'get') else resource[5]
            
            self.send_log(f"📦 [{i+1}/{total_groups}] 正在提取: {title}", "info")
            self.send_event("batch-extraction-progress", {
                "status": "extracting",
                "totalGroups": total_groups,
                "completed": completed,
                "currentGroup": title or str(rid),
                "currentIndex": i + 1,
                "totalMembers": total_members
            })
            
            # 構建提取 payload
            extract_payload = {
                'resourceId': rid,
                'telegramId': telegram_id,
                'username': username,
                'phone': phone,
                'groupName': title,
                'limit': limit_per_group,
                'chatId': telegram_id
            }
            
            # 對未加入的群組使用 join-and-extract
            if status not in ('joined', 'monitoring') and (username or telegram_id):
                self.send_log(f"  ↳ 未加入，嘗試自動加入...", "info")
                await handle_join_and_extract(self, extract_payload)
            else:
                await handle_extract_members(self, extract_payload)
            
            # 統計（members-extracted 事件已由上面的函數發送）
            completed += 1
            
            # 從最近的提取日誌獲取本次提取數量
            try:
                last_log = await batch_db.fetch_one(
                    """SELECT extracted_count FROM member_extraction_logs 
                       WHERE chat_id = ? ORDER BY created_at DESC LIMIT 1""",
                    (str(telegram_id or rid),)
                )
                if last_log:
                    cnt = last_log.get('extracted_count') if hasattr(last_log, 'get') else last_log[0]
                    total_members += (cnt or 0)
            except Exception:
                pass
            
            results.append({
                "resourceId": rid,
                "title": title,
                "success": True
            })
            
            # 安全模式：群組間等待避免 FloodWait
            if safe_mode and i < total_groups - 1:
                wait = 8 if total_groups > 5 else 5
                self.send_log(f"  ↳ 等待 {wait}s 避免速率限制...", "info")
                await asyncio.sleep(wait)
                
        except Exception as e:
            failed += 1
            self.send_log(f"❌ [{i+1}/{total_groups}] {title if 'title' in dir() else rid} 失敗: {e}", "error")
            results.append({
                "resourceId": rid,
                "title": title if 'title' in dir() else str(rid),
                "success": False,
                "error": str(e)
            })
    
    # 發送最終結果
    self.send_log(f"✅ 批量提取完成: {completed}/{total_groups} 成功，共 {total_members} 成員", "success")
    self.send_event("batch-members-extracted", {
        "success": failed < total_groups,
        "totalGroups": total_groups,
        "completed": completed,
        "failed": failed,
        "totalMembers": total_members,
        "results": results
    })


async def handle_deduplicate_members(self, payload: Dict[str, Any]):
    """去重成員數據"""
    import sys
    print(f"[Backend] handle_deduplicate_members called", file=sys.stderr)
    
    try:
        result = await member_extraction_service.deduplicate_members()
        
        self.send_log(f"✅ 去重完成: 合併 {result['merged']} 個，刪除 {result['deleted']} 條", "success")
        self.send_event("members-deduplicated", {
            "success": True,
            **result
        })
        
    except Exception as e:
        import traceback
        traceback.print_exc(file=sys.stderr)
        self.send_event("members-deduplicated", {
            "success": False,
            "error": str(e)
        })

